Halide: Halide::Func Class Reference
Halide::Func Class Reference
A halide function.
#include <Func.h>
Public Member Functions
Func (const std::string &name)
Declare a new undefined function with the given name.
Func ()
Declare a new undefined function with an automatically-generated unique name.
Func (Expr e)
Declare a new function with an automatically-generated unique name, and define it to return the given expression (which may not contain free variables).
Func (Internal::Function f)
Construct a new Func to wrap an existing, already-define Function object.
template<typename T >
HALIDE_NO_USER_CODE_INLINE Func (Buffer< T > &im)
Construct a new Func to wrap a Buffer.
void realize (Pipeline::RealizationArg outputs, const Target &target=Target(), const ParamMap &param_map=ParamMap::empty_map())
Evaluate this function into an existing allocated buffer or buffers.
void compile_to_header (const std::string &filename, const std::vector< Argument > &, const std::string &fn_name="", const Target &target=get_target_from_environment())
Emit a header file with the given filename for this function.
void compile_to_c (const std::string &filename, const std::vector< Argument > &, const std::string &fn_name="", const Target &target=get_target_from_environment())
Statically compile this function to C source code.
void compile_to_lowered_stmt (const std::string &filename, const std::vector< Argument > &args, StmtOutputFormat fmt=Text, const Target &target=get_target_from_environment())
Write out an internal representation of lowered code.
void compile_to_python_extension (const std::string &filename_prefix, const std::vector< Argument > &args, const std::string &fn_name, const Target &target=get_target_from_environment())
Emit a Python Extension glue .c file.
void print_loop_nest ()
Write out the loop nests specified by the schedule for this Function.
void compile_to_file (const std::string &filename_prefix, const std::vector< Argument > &args, const std::string &fn_name="", const Target &target=get_target_from_environment())
Compile to object file and header pair, with the given arguments.
void compile_to_static_library (const std::string &filename_prefix, const std::vector< Argument > &args, const std::string &fn_name="", const Target &target=get_target_from_environment())
Compile to static-library file and header pair, with the given arguments.
void compile_to_multitarget_static_library (const std::string &filename_prefix, const std::vector< Argument > &args, const std::vector< Target > &targets)
Compile to static-library file and header pair once for each target; each resulting function will be considered (in order) via halide_can_use_target_features() at runtime, with the first appropriate match being selected for subsequent use.
Module compile_to_module (const std::vector< Argument > &args, const std::string &fn_name="", const Target &target=get_target_from_environment())
Store an internal representation of lowered code as a self contained Module suitable for further compilation.
void compile_to (const Outputs &output_files, const std::vector< Argument > &args, const std::string &fn_name, const Target &target=get_target_from_environment())
Compile and generate multiple target files with single call.
void * compile_jit (const Target &target=get_jit_target_from_environment())
Eagerly jit compile the function to machine code.
void set_error_handler (void(*handler)(void *, const char *))
Set the error handler function that be called in the case of runtime errors during halide pipelines.
void set_custom_allocator (void *(*malloc)(void *, size_t), void(*free)(void *, void *))
void set_custom_do_task (int(*custom_do_task)(void *, int(*)(void *, int, uint8_t *), int, uint8_t *))
Set a custom task handler to be called by the parallel for loop.
void set_custom_do_par_for (int(*custom_do_par_for)(void *, int(*)(void *, int, uint8_t *), int, int, uint8_t *))
Set a custom parallel for loop launcher.
void set_custom_trace (int(*trace_fn)(void *, const halide_trace_event_t *))
Set custom routines to call when tracing is enabled.
void set_custom_print (void(*handler)(void *, const char *))
Set the function called to print messages from the runtime.
const Internal::JITHandlers & jit_handlers ()
Get a struct containing the currently set custom functions used by JIT.
template<typename T >
void add_custom_lowering_pass (T *pass)
Add a custom pass to be used during lowering.
void add_custom_lowering_pass (Internal::IRMutator2 *pass, std::function< void()> deleter)
Add a custom pass to be used during lowering, with the function that will be called to delete it also passed in.
void clear_custom_lowering_passes ()
Remove all previously-set custom lowering passes.
const std::vector< CustomLoweringPass > & custom_lowering_passes ()
Get the custom lowering passes.
void debug_to_file (const std::string &filename)
When this function is compiled, include code that dumps its values to a file after it is realized, for the purpose of debugging.
const std::string & name () const
The name of this function, either given during construction, or automatically generated.
std::vector< Var > args () const
Get the pure arguments.
Expr value () const
The right-hand-side value of the pure definition of this function.
Tuple values () const
The values returned by this function.
bool defined () const
Does this function have at least a pure definition.
const std::vector< Expr > & update_args (int idx=0) const
Get the left-hand-side of the update definition.
Expr update_value (int idx=0) const
Get the right-hand-side of an update definition.
Tuple update_values (int idx=0) const
Get the right-hand-side of an update definition for functions that returns multiple values.
std::vector< RVar > rvars (int idx=0) const
Get the RVars of the reduction domain for an update definition, if there is one.
bool has_update_definition () const
Does this function have at least one update definition?
int num_update_definitions () const
How many update definitions does this function have?
bool is_extern () const
Is this function an external stage? That is, was it defined using define_extern?
const std::vector< Type > & output_types () const
Get the types of the outputs of this Func.
int outputs () const
Get the number of outputs of this Func.
const std::string & extern_function_name () const
Get the name of the extern function called for an extern definition.
int dimensions () const
The dimensionality (number of arguments) of this function.
Func in (const Func &f)
Creates and returns a new identity Func that wraps this Func.
Func in (const std::vector< Func > &fs)
Create and return an identity wrapper shared by all the Funcs in 'fs'.
Func in ()
Create and return a global identity wrapper, which wraps all calls to this Func by any other Func.
Func copy_to_device (DeviceAPI d=DeviceAPI::Default_GPU)
Declare that this function should be implemented by a call to halide_buffer_copy with the given target device API.
Func copy_to_host ()
Declare that this function should be implemented by a call to halide_buffer_copy with a NULL target device API.
Func & split (VarOrRVar old, VarOrRVar outer, VarOrRVar inner, Expr factor, TailStrategy tail=TailStrategy::Auto)
Split a dimension into inner and outer subdimensions with the given names, where the inner dimension iterates from 0 to factor-1.
Func & fuse (VarOrRVar inner, VarOrRVar outer, VarOrRVar fused)
Join two dimensions into a single fused dimenion.
Func & serial (VarOrRVar var)
Mark a dimension to be traversed serially.
Func & parallel (VarOrRVar var)
Mark a dimension to be traversed in parallel.
Func & parallel (VarOrRVar var, Expr task_size, TailStrategy tail=TailStrategy::Auto)
Split a dimension by the given task_size, and the parallelize the outer dimension.
Func & vectorize (VarOrRVar var)
Mark a dimension to be computed all-at-once as a single vector.
Func & unroll (VarOrRVar var)
Mark a dimension to be completely unrolled.
Func & vectorize (VarOrRVar var, Expr factor, TailStrategy tail=TailStrategy::Auto)
Split a dimension by the given factor, then vectorize the inner dimension.
Func & unroll (VarOrRVar var, Expr factor, TailStrategy tail=TailStrategy::Auto)
Split a dimension by the given factor, then unroll the inner dimension.
Func & bound (Var var, Expr min, Expr extent)
Statically declare that the range over which a function should be evaluated is given by the second and third arguments.
Func & estimate (Var var, Expr min, Expr extent)
Statically declare the range over which the function will be evaluated in the general case.
Func & align_bounds (Var var, Expr modulus, Expr remainder=0)
Expand the region computed so that the min coordinates is congruent to 'remainder' modulo 'modulus', and the extent is a multiple of 'modulus'.
Func & bound_extent (Var var, Expr extent)
Bound the extent of a Func's realization, but not its min.
Func & tile (VarOrRVar x, VarOrRVar y, VarOrRVar xo, VarOrRVar yo, VarOrRVar xi, VarOrRVar yi, Expr xfactor, Expr yfactor, TailStrategy tail=TailStrategy::Auto)
Split two dimensions at once by the given factors, and then reorder the resulting dimensions to be xi, yi, xo, yo from innermost outwards.
Func & tile (VarOrRVar x, VarOrRVar y, VarOrRVar xi, VarOrRVar yi, Expr xfactor, Expr yfactor, TailStrategy tail=TailStrategy::Auto)
A shorter form of tile, which reuses the old variable names as the new outer dimensions.
Func & reorder (const std::vector< VarOrRVar > &vars)
Reorder variables to have the given nesting order, from innermost out.
template<typename... Args>
HALIDE_NO_USER_CODE_INLINE std::enable_if< Internal::all_are_convertible< VarOrRVar, Args... >::value, Func & >::type reorder (VarOrRVar x, VarOrRVar y, Args &&...args)
Func & rename (VarOrRVar old_name, VarOrRVar new_name)
Rename a dimension.
Func & allow_race_conditions ()
Specify that race conditions are permitted for this Func, which enables parallelizing over RVars even when Halide cannot prove that it is safe to do so.
Stage specialize (Expr condition)
Specialize a Func.
void specialize_fail (const std::string &message)
Add a specialization to a Func that always terminates execution with a call to halide_error().
Func & gpu_lanes (VarOrRVar thread_x, DeviceAPI device_api=DeviceAPI::Default_GPU)
The given dimension corresponds to the lanes in a GPU warp.
Func & gpu_single_thread (DeviceAPI device_api=DeviceAPI::Default_GPU)
Tell Halide to run this stage using a single gpu thread and block.
Func & shader (Var x, Var y, Var c, DeviceAPI device_api)
Schedule for execution using coordinate-based hardware api.
Func & glsl (Var x, Var y, Var c)
Schedule for execution as GLSL kernel.
Func & hexagon (VarOrRVar x=Var::outermost())
Schedule for execution on Hexagon.
Func & align_storage (Var dim, Expr alignment)
Pad the storage extent of a particular dimension of realizations of this function up to be a multiple of the specified alignment.
Func & fold_storage (Var dim, Expr extent, bool fold_forward=true)
Store realizations of this function in a circular buffer of a given extent.
Func & compute_at (Func f, Var var)
Compute this function as needed for each unique value of the given var for the given calling function f.
Func & compute_at (Func f, RVar var)
Schedule a function to be computed within the iteration over some dimension of an update domain.
Func & compute_at (LoopLevel loop_level)
Schedule a function to be computed within the iteration over a given LoopLevel.
operator ExternFuncArgument () const
Use a Func as an argument to an external stage.
std::vector< Argument > infer_arguments () const
Infer the arguments to the Func, sorted into a canonical order: all buffers (sorted alphabetically by name), followed by all non-buffers (sorted alphabetically by name).
std::string source_location () const
Get the source location of the pure definition of this Func.
Realization realize (std::vector< int32_t > sizes, const Target &target=Target(), const ParamMap &param_map=ParamMap::empty_map())
Evaluate this function over some rectangular domain and return the resulting buffer or buffers.
Realization realize (int x_size, int y_size, int z_size, int w_size, const Target &target=Target(), const ParamMap &param_map=ParamMap::empty_map())
Evaluate this function over some rectangular domain and return the resulting buffer or buffers.
Realization realize (int x_size, int y_size, int z_size, const Target &target=Target(), const ParamMap &param_map=ParamMap::empty_map())
Evaluate this function over some rectangular domain and return the resulting buffer or buffers.
Realization realize (int x_size, int y_size, const Target &target=Target(), const ParamMap &param_map=ParamMap::empty_map())
Evaluate this function over some rectangular domain and return the resulting buffer or buffers.
Realization realize (int x_size, const Target &target=Target(), const ParamMap &param_map=ParamMap::empty_map())
Evaluate this function over some rectangular domain and return the resulting buffer or buffers.
Realization realize (const Target &target=Target(), const ParamMap &param_map=ParamMap::empty_map())
Evaluate this function over some rectangular domain and return the resulting buffer or buffers.
void infer_input_bounds (int x_size=0, int y_size=0, int z_size=0, int w_size=0, const ParamMap &param_map=ParamMap::empty_map())
For a given size of output, or a given output buffer, determine the bounds required of all unbound ImageParams referenced.
void infer_input_bounds (Pipeline::RealizationArg outputs, const ParamMap &param_map=ParamMap::empty_map())
For a given size of output, or a given output buffer, determine the bounds required of all unbound ImageParams referenced.
void compile_to_bitcode (const std::string &filename, const std::vector< Argument > &, const std::string &fn_name, const Target &target=get_target_from_environment())
Statically compile this function to llvm bitcode, with the given filename (which should probably end in .bc), type signature, and C function name (which defaults to the same name as this halide function.
void compile_to_bitcode (const std::string &filename, const std::vector< Argument > &, const Target &target=get_target_from_environment())
Statically compile this function to llvm bitcode, with the given filename (which should probably end in .bc), type signature, and C function name (which defaults to the same name as this halide function.
void compile_to_llvm_assembly (const std::string &filename, const std::vector< Argument > &, const std::string &fn_name, const Target &target=get_target_from_environment())
Statically compile this function to llvm assembly, with the given filename (which should probably end in .ll), type signature, and C function name (which defaults to the same name as this halide function.
void compile_to_llvm_assembly (const std::string &filename, const std::vector< Argument > &, const Target &target=get_target_from_environment())
Statically compile this function to llvm assembly, with the given filename (which should probably end in .ll), type signature, and C function name (which defaults to the same name as this halide function.
void compile_to_object (const std::string &filename, const std::vector< Argument > &, const std::string &fn_name, const Target &target=get_target_from_environment())
Statically compile this function to an object file, with the given filename (which should probably end in .o or .obj), type signature, and C function name (which defaults to the same name as this halide function.
void compile_to_object (const std::string &filename, const std::vector< Argument > &, const Target &target=get_target_from_environment())
Statically compile this function to an object file, with the given filename (which should probably end in .o or .obj), type signature, and C function name (which defaults to the same name as this halide function.
void compile_to_assembly (const std::string &filename, const std::vector< Argument > &, const std::string &fn_name, const Target &target=get_target_from_environment())
Statically compile this function to text assembly equivalent to the object file generated by compile_to_object.
void compile_to_assembly (const std::string &filename, const std::vector< Argument > &, const Target &target=get_target_from_environment())
Statically compile this function to text assembly equivalent to the object file generated by compile_to_object.
void define_extern (const std::string &function_name, const std::vector< ExternFuncArgument > &params, Type t, int dimensionality, NameMangling mangling, bool uses_old_buffer_t)
Add an extern definition for this Func.
void define_extern (const std::string &function_name, const std::vector< ExternFuncArgument > &params, Type t, int dimensionality, NameMangling mangling=NameMangling::Default, DeviceAPI device_api=DeviceAPI::Host, bool uses_old_buffer_t=false)
Add an extern definition for this Func.
void define_extern (const std::string &function_name, const std::vector< ExternFuncArgument > &params, const std::vector< Type > &types, int dimensionality, NameMangling mangling, bool uses_old_buffer_t)
Add an extern definition for this Func.
void define_extern (const std::string &function_name, const std::vector< ExternFuncArgument > &params, const std::vector< Type > &types, int dimensionality, NameMangling mangling=NameMangling::Default, DeviceAPI device_api=DeviceAPI::Host, bool uses_old_buffer_t=false)
Add an extern definition for this Func.
void define_extern (const std::string &function_name, const std::vector< ExternFuncArgument > &params, Type t, const std::vector< Var > &arguments, NameMangling mangling, bool uses_old_buffer_t)
Add an extern definition for this Func.
void define_extern (const std::string &function_name, const std::vector< ExternFuncArgument > &params, Type t, const std::vector< Var > &arguments, NameMangling mangling=NameMangling::Default, DeviceAPI device_api=DeviceAPI::Host, bool uses_old_buffer_t=false)
Add an extern definition for this Func.
void define_extern (const std::string &function_name, const std::vector< ExternFuncArgument > &params, const std::vector< Type > &types, const std::vector< Var > &arguments, NameMangling mangling, bool uses_old_buffer_t)
Add an extern definition for this Func.
void define_extern (const std::string &function_name, const std::vector< ExternFuncArgument > &params, const std::vector< Type > &types, const std::vector< Var > &arguments, NameMangling mangling=NameMangling::Default, DeviceAPI device_api=DeviceAPI::Host, bool uses_old_buffer_t=false)
Add an extern definition for this Func.
FuncRef operator() (std::vector< Var >) const
Construct either the left-hand-side of a definition, or a call to a functions that happens to only contain vars as arguments.
template<typename... Args>
HALIDE_NO_USER_CODE_INLINE std::enable_if< Internal::all_are_convertible< Var, Args... >::value, FuncRef >::type operator() (Args &&...args) const
Construct either the left-hand-side of a definition, or a call to a functions that happens to only contain vars as arguments.
FuncRef operator() (std::vector< Expr >) const
Either calls to the function, or the left-hand-side of an update definition (see RDom).
template<typename... Args>
HALIDE_NO_USER_CODE_INLINE std::enable_if< Internal::all_are_convertible< Expr, Args... >::value, FuncRef >::type operator() (Expr x, Args &&...args) const
Either calls to the function, or the left-hand-side of an update definition (see RDom).
Func clone_in (const Func &f)
Similar to Func::in; however, instead of replacing the call to this Func with an identity Func that refers to it, this replaces the call with a clone of this Func.
Func clone_in (const std::vector< Func > &fs)
Similar to Func::in; however, instead of replacing the call to this Func with an identity Func that refers to it, this replaces the call with a clone of this Func.
Func & gpu_threads (VarOrRVar thread_x, DeviceAPI device_api=DeviceAPI::Default_GPU)
Tell Halide that the following dimensions correspond to GPU thread indices.
Func & gpu_threads (VarOrRVar thread_x, VarOrRVar thread_y, DeviceAPI device_api=DeviceAPI::Default_GPU)
Tell Halide that the following dimensions correspond to GPU thread indices.
Func & gpu_threads (VarOrRVar thread_x, VarOrRVar thread_y, VarOrRVar thread_z, DeviceAPI device_api=DeviceAPI::Default_GPU)
Tell Halide that the following dimensions correspond to GPU thread indices.
Func & gpu_blocks (VarOrRVar block_x, DeviceAPI device_api=DeviceAPI::Default_GPU)
Tell Halide that the following dimensions correspond to GPU block indices.
Func & gpu_blocks (VarOrRVar block_x, VarOrRVar block_y, DeviceAPI device_api=DeviceAPI::Default_GPU)
Tell Halide that the following dimensions correspond to GPU block indices.
Func & gpu_blocks (VarOrRVar block_x, VarOrRVar block_y, VarOrRVar block_z, DeviceAPI device_api=DeviceAPI::Default_GPU)
Tell Halide that the following dimensions correspond to GPU block indices.
Func & gpu (VarOrRVar block_x, VarOrRVar thread_x, DeviceAPI device_api=DeviceAPI::Default_GPU)
Tell Halide that the following dimensions correspond to GPU block indices and thread indices.
Func & gpu (VarOrRVar block_x, VarOrRVar block_y, VarOrRVar thread_x, VarOrRVar thread_y, DeviceAPI device_api=DeviceAPI::Default_GPU)
Tell Halide that the following dimensions correspond to GPU block indices and thread indices.
Func & gpu (VarOrRVar block_x, VarOrRVar block_y, VarOrRVar block_z, VarOrRVar thread_x, VarOrRVar thread_y, VarOrRVar thread_z, DeviceAPI device_api=DeviceAPI::Default_GPU)
Tell Halide that the following dimensions correspond to GPU block indices and thread indices.
Func & gpu_tile (VarOrRVar x, VarOrRVar bx, VarOrRVar tx, Expr x_size, TailStrategy tail=TailStrategy::Auto, DeviceAPI device_api=DeviceAPI::Default_GPU)
Short-hand for tiling a domain and mapping the tile indices to GPU block indices and the coordinates within each tile to GPU thread indices.
Func & gpu_tile (VarOrRVar x, VarOrRVar tx, Expr x_size, TailStrategy tail=TailStrategy::Auto, DeviceAPI device_api=DeviceAPI::Default_GPU)
Short-hand for tiling a domain and mapping the tile indices to GPU block indices and the coordinates within each tile to GPU thread indices.
Func & gpu_tile (VarOrRVar x, VarOrRVar y, VarOrRVar bx, VarOrRVar by, VarOrRVar tx, VarOrRVar ty, Expr x_size, Expr y_size, TailStrategy tail=TailStrategy::Auto, DeviceAPI device_api=DeviceAPI::Default_GPU)
Short-hand for tiling a domain and mapping the tile indices to GPU block indices and the coordinates within each tile to GPU thread indices.
Func & gpu_tile (VarOrRVar x, VarOrRVar y, VarOrRVar tx, VarOrRVar ty, Expr x_size, Expr y_size, TailStrategy tail=TailStrategy::Auto, DeviceAPI device_api=DeviceAPI::Default_GPU)
Short-hand for tiling a domain and mapping the tile indices to GPU block indices and the coordinates within each tile to GPU thread indices.
Func & gpu_tile (VarOrRVar x, VarOrRVar y, VarOrRVar z, VarOrRVar bx, VarOrRVar by, VarOrRVar bz, VarOrRVar tx, VarOrRVar ty, VarOrRVar tz, Expr x_size, Expr y_size, Expr z_size, TailStrategy tail=TailStrategy::Auto, DeviceAPI device_api=DeviceAPI::Default_GPU)
Short-hand for tiling a domain and mapping the tile indices to GPU block indices and the coordinates within each tile to GPU thread indices.
Func & gpu_tile (VarOrRVar x, VarOrRVar y, VarOrRVar z, VarOrRVar tx, VarOrRVar ty, VarOrRVar tz, Expr x_size, Expr y_size, Expr z_size, TailStrategy tail=TailStrategy::Auto, DeviceAPI device_api=DeviceAPI::Default_GPU)
Short-hand for tiling a domain and mapping the tile indices to GPU block indices and the coordinates within each tile to GPU thread indices.
Func & prefetch (const Func &f, VarOrRVar var, Expr offset=1, PrefetchBoundStrategy strategy=PrefetchBoundStrategy::GuardWithIf)
Prefetch data written to or read from a Func or an ImageParam by a subsequent loop iteration, at an optionally specified iteration offset.
Func & prefetch (const Internal::Parameter &param, VarOrRVar var, Expr offset=1, PrefetchBoundStrategy strategy=PrefetchBoundStrategy::GuardWithIf)
Prefetch data written to or read from a Func or an ImageParam by a subsequent loop iteration, at an optionally specified iteration offset.
template<typename T >
Func & prefetch (const T &image, VarOrRVar var, Expr offset=1, PrefetchBoundStrategy strategy=PrefetchBoundStrategy::GuardWithIf)
Prefetch data written to or read from a Func or an ImageParam by a subsequent loop iteration, at an optionally specified iteration offset.
Func & reorder_storage (const std::vector< Var > &dims)
Specify how the storage for the function is laid out.
Func & reorder_storage (Var x, Var y)
Specify how the storage for the function is laid out.
template<typename... Args>
HALIDE_NO_USER_CODE_INLINE std::enable_if< Internal::all_are_convertible< Var, Args... >::value, Func & >::type reorder_storage (Var x, Var y, Args &&...args)
Specify how the storage for the function is laid out.
Func & compute_with (Stage s, VarOrRVar var, const std::vector< std::pair< VarOrRVar, LoopAlignStrategy >> &align)
Schedule the iteration over the initial definition of this function to be fused with another stage 's' from outermost loop to a given LoopLevel.
Func & compute_with (Stage s, VarOrRVar var, LoopAlignStrategy align=LoopAlignStrategy::Auto)
Schedule the iteration over the initial definition of this function to be fused with another stage 's' from outermost loop to a given LoopLevel.
Func & compute_with (LoopLevel loop_level, const std::vector< std::pair< VarOrRVar, LoopAlignStrategy >> &align)
Schedule the iteration over the initial definition of this function to be fused with another stage 's' from outermost loop to a given LoopLevel.
Func & compute_with (LoopLevel loop_level, LoopAlignStrategy align=LoopAlignStrategy::Auto)
Schedule the iteration over the initial definition of this function to be fused with another stage 's' from outermost loop to a given LoopLevel.
Func & compute_root ()
Compute all of this function once ahead of time.
Func & memoize ()
Use the halide_memoization_cache_...
Func & store_at (Func f, Var var)
Allocate storage for this function within f's loop over var.
Func & store_at (Func f, RVar var)
Equivalent to the version of store_at that takes a Var, but schedules storage within the loop over a dimension of a reduction domain.
Func & store_at (LoopLevel loop_level)
Equivalent to the version of store_at that takes a Var, but schedules storage at a given LoopLevel.
Func & store_root ()
Equivalent to Func::store_at, but schedules storage outside the outermost loop.
Func & compute_inline ()
Aggressively inline all uses of this function.
Stage update (int idx=0)
Get a handle on an update step for the purposes of scheduling it.
Func & store_in (MemoryType memory_type)
Set the type of memory this Func should be stored in.
Func & trace_loads ()
Trace all loads from this Func by emitting calls to halide_trace.
Func & trace_stores ()
Trace all stores to the buffer backing this Func by emitting calls to halide_trace.
Func & trace_realizations ()
Trace all realizations of this Func by emitting calls to halide_trace.
Func & add_trace_tag (const std::string &trace_tag)
Add a string of arbitrary text that will be passed thru to trace inspection code if the Func is realized in trace mode.
Internal::Function function () const
Get a handle on the internal halide function that this Func represents.
operator Stage () const
You can cast a Func to its pure stage for the purposes of scheduling it.
OutputImageParam output_buffer () const
Get a handle on the output buffer for this Func.
std::vector< OutputImageParam > output_buffers () const
Schedule the iteration over the initial definition of this function to be fused with another stage 's' from outermost loop to a given LoopLevel.
Detailed Description
A halide function.
This class represents one stage in a Halide pipeline, and is the unit by which we schedule things. By default they are aggressively inlined, so you are encouraged to make lots of little functions, rather than storing things in Exprs.
Definition at line 616 of file Func.h.
Constructor & Destructor Documentation
Halide::Func::Func (const std::string & name) explicit
Declare a new undefined function with the given name.
Halide::Func::Func ()
Declare a new undefined function with an automatically-generated unique name.
Halide::Func::Func (Expr e) explicit
Declare a new function with an automatically-generated unique name, and define it to return the given expression (which may not contain free variables).
Halide::Func::Func (Internal::Function f) explicit
Construct a new Func to wrap an existing, already-define Function object.
template<typename T > HALIDE_NO_USER_CODE_INLINE Halide::Func::Func (Buffer< T > & im) inline explicit
Construct a new Func to wrap a Buffer.
Definition at line 663 of file Func.h.
References Halide::_, Halide::Runtime::Internal::custom_do_par_for, Halide::Runtime::Internal::custom_do_task, Halide::ParamMap::empty_map(), free(), Halide::get_jit_target_from_environment(), Halide::get_target_from_environment(), malloc(), Halide::Internal::print_loop_nest(), and Halide::Text.
Member Function Documentation
Realization Halide::Func::realize (std::vector< int32_t > sizes, const Target & target = Target(), const ParamMap & param_map = ParamMap::empty_map())
Evaluate this function over some rectangular domain and return the resulting buffer or buffers.
Performs compilation if the Func has not previously been realized and jit_compile has not been called. If the final stage of the pipeline is on the GPU, data is copied back to the host before being returned. The returned Realization should probably be instantly converted to a Buffer class of the appropriate type. That is, do this:
f(x) = sin(x);
Buffer<float> im = f.realize(...);
If your Func has multiple values, because you defined it using a Tuple, then casting the result of a realize call to a buffer or image will produce a run-time error. Instead you should do the following:
f(x) = Tuple(x, sin(x));
Realization r = f.realize(...);
Buffer<int> im0 = r[0];
Buffer<float> im1 = r[1];
In Halide formal arguments of a computation are specified using Param<T> and ImageParam objects in the expressions defining the computation. The param_map argument to realize allows specifying a set of per-call parameters to be used for a specific computation. This method is thread-safe where the globals used by Param<T> and ImageParam are not. Any parameters that are not in the param_map are taken from the global values, so those can continue to be used if they are not changing per-thread.
One can explicitly construct a ParamMap and use its set method to insert Parameter to scalar or Buffer value mappings:
Param<int32> p(42);
ImageParam img(Int(32), 1);
f(x) = img(x) + p;
Buffer<int32_t) arg_img(10, 10);
<fill in arg_img...>
ParamMap params;
params.set(p, 17);
params.set(img, arg_img);
Target t = get_jit_target_from_environment();
Buffer<int32_t> result = f.realize(10, 10, t, params);
Alternatively, an initializer list can be used directly in the realize call to pass this information:
Param<int32> p(42);
ImageParam img(Int(32), 1);
f(x) = img(x) + p;
Buffer<int32_t) arg_img(10, 10);
<fill in arg_img...>
Target t = get_jit_target_from_environment();
Buffer<int32_t> result = f.realize(10, 10, t, { { p, 17 }, { img, arg_img } });
Referenced by Halide::evaluate(), Halide::evaluate_may_gpu(), and Halide::Internal::StubOutputBufferBase::realize().
Realization Halide::Func::realize (int x_size, int y_size, int z_size, int w_size, const Target & target = Target(), const ParamMap & param_map = ParamMap::empty_map())
Evaluate this function over some rectangular domain and return the resulting buffer or buffers.
Performs compilation if the Func has not previously been realized and jit_compile has not been called. If the final stage of the pipeline is on the GPU, data is copied back to the host before being returned. The returned Realization should probably be instantly converted to a Buffer class of the appropriate type. That is, do this:
f(x) = sin(x);
Buffer<float> im = f.realize(...);
If your Func has multiple values, because you defined it using a Tuple, then casting the result of a realize call to a buffer or image will produce a run-time error. Instead you should do the following:
f(x) = Tuple(x, sin(x));
Realization r = f.realize(...);
Buffer<int> im0 = r[0];
Buffer<float> im1 = r[1];
In Halide formal arguments of a computation are specified using Param<T> and ImageParam objects in the expressions defining the computation. The param_map argument to realize allows specifying a set of per-call parameters to be used for a specific computation. This method is thread-safe where the globals used by Param<T> and ImageParam are not. Any parameters that are not in the param_map are taken from the global values, so those can continue to be used if they are not changing per-thread.
One can explicitly construct a ParamMap and use its set method to insert Parameter to scalar or Buffer value mappings:
Param<int32> p(42);
ImageParam img(Int(32), 1);
f(x) = img(x) + p;
Buffer<int32_t) arg_img(10, 10);
<fill in arg_img...>
ParamMap params;
params.set(p, 17);
params.set(img, arg_img);
Target t = get_jit_target_from_environment();
Buffer<int32_t> result = f.realize(10, 10, t, params);
Alternatively, an initializer list can be used directly in the realize call to pass this information:
Param<int32> p(42);
ImageParam img(Int(32), 1);
f(x) = img(x) + p;
Buffer<int32_t) arg_img(10, 10);
<fill in arg_img...>
Target t = get_jit_target_from_environment();
Buffer<int32_t> result = f.realize(10, 10, t, { { p, 17 }, { img, arg_img } });
Realization Halide::Func::realize (int x_size, int y_size, int z_size, const Target & target = Target(), const ParamMap & param_map = ParamMap::empty_map())
Evaluate this function over some rectangular domain and return the resulting buffer or buffers.
Performs compilation if the Func has not previously been realized and jit_compile has not been called. If the final stage of the pipeline is on the GPU, data is copied back to the host before being returned. The returned Realization should probably be instantly converted to a Buffer class of the appropriate type. That is, do this:
f(x) = sin(x);
Buffer<float> im = f.realize(...);
If your Func has multiple values, because you defined it using a Tuple, then casting the result of a realize call to a buffer or image will produce a run-time error. Instead you should do the following:
f(x) = Tuple(x, sin(x));
Realization r = f.realize(...);
Buffer<int> im0 = r[0];
Buffer<float> im1 = r[1];
In Halide formal arguments of a computation are specified using Param<T> and ImageParam objects in the expressions defining the computation. The param_map argument to realize allows specifying a set of per-call parameters to be used for a specific computation. This method is thread-safe where the globals used by Param<T> and ImageParam are not. Any parameters that are not in the param_map are taken from the global values, so those can continue to be used if they are not changing per-thread.
One can explicitly construct a ParamMap and use its set method to insert Parameter to scalar or Buffer value mappings:
Param<int32> p(42);
ImageParam img(Int(32), 1);
f(x) = img(x) + p;
Buffer<int32_t) arg_img(10, 10);
<fill in arg_img...>
ParamMap params;
params.set(p, 17);
params.set(img, arg_img);
Target t = get_jit_target_from_environment();
Buffer<int32_t> result = f.realize(10, 10, t, params);
Alternatively, an initializer list can be used directly in the realize call to pass this information:
Param<int32> p(42);
ImageParam img(Int(32), 1);
f(x) = img(x) + p;
Buffer<int32_t) arg_img(10, 10);
<fill in arg_img...>
Target t = get_jit_target_from_environment();
Buffer<int32_t> result = f.realize(10, 10, t, { { p, 17 }, { img, arg_img } });
Realization Halide::Func::realize (int x_size, int y_size, const Target & target = Target(), const ParamMap & param_map = ParamMap::empty_map())
Evaluate this function over some rectangular domain and return the resulting buffer or buffers.
Performs compilation if the Func has not previously been realized and jit_compile has not been called. If the final stage of the pipeline is on the GPU, data is copied back to the host before being returned. The returned Realization should probably be instantly converted to a Buffer class of the appropriate type. That is, do this:
f(x) = sin(x);
Buffer<float> im = f.realize(...);
If your Func has multiple values, because you defined it using a Tuple, then casting the result of a realize call to a buffer or image will produce a run-time error. Instead you should do the following:
f(x) = Tuple(x, sin(x));
Realization r = f.realize(...);
Buffer<int> im0 = r[0];
Buffer<float> im1 = r[1];
In Halide formal arguments of a computation are specified using Param<T> and ImageParam objects in the expressions defining the computation. The param_map argument to realize allows specifying a set of per-call parameters to be used for a specific computation. This method is thread-safe where the globals used by Param<T> and ImageParam are not. Any parameters that are not in the param_map are taken from the global values, so those can continue to be used if they are not changing per-thread.
One can explicitly construct a ParamMap and use its set method to insert Parameter to scalar or Buffer value mappings:
Param<int32> p(42);
ImageParam img(Int(32), 1);
f(x) = img(x) + p;
Buffer<int32_t) arg_img(10, 10);
<fill in arg_img...>
ParamMap params;
params.set(p, 17);
params.set(img, arg_img);
Target t = get_jit_target_from_environment();
Buffer<int32_t> result = f.realize(10, 10, t, params);
Alternatively, an initializer list can be used directly in the realize call to pass this information:
Param<int32> p(42);
ImageParam img(Int(32), 1);
f(x) = img(x) + p;
Buffer<int32_t) arg_img(10, 10);
<fill in arg_img...>
Target t = get_jit_target_from_environment();
Buffer<int32_t> result = f.realize(10, 10, t, { { p, 17 }, { img, arg_img } });
Realization Halide::Func::realize (int x_size, const Target & target = Target(), const ParamMap & param_map = ParamMap::empty_map())
Evaluate this function over some rectangular domain and return the resulting buffer or buffers.
Performs compilation if the Func has not previously been realized and jit_compile has not been called. If the final stage of the pipeline is on the GPU, data is copied back to the host before being returned. The returned Realization should probably be instantly converted to a Buffer class of the appropriate type. That is, do this:
f(x) = sin(x);
Buffer<float> im = f.realize(...);
If your Func has multiple values, because you defined it using a Tuple, then casting the result of a realize call to a buffer or image will produce a run-time error. Instead you should do the following:
f(x) = Tuple(x, sin(x));
Realization r = f.realize(...);
Buffer<int> im0 = r[0];
Buffer<float> im1 = r[1];
In Halide formal arguments of a computation are specified using Param<T> and ImageParam objects in the expressions defining the computation. The param_map argument to realize allows specifying a set of per-call parameters to be used for a specific computation. This method is thread-safe where the globals used by Param<T> and ImageParam are not. Any parameters that are not in the param_map are taken from the global values, so those can continue to be used if they are not changing per-thread.
One can explicitly construct a ParamMap and use its set method to insert Parameter to scalar or Buffer value mappings:
Param<int32> p(42);
ImageParam img(Int(32), 1);
f(x) = img(x) + p;
Buffer<int32_t) arg_img(10, 10);
<fill in arg_img...>
ParamMap params;
params.set(p, 17);
params.set(img, arg_img);
Target t = get_jit_target_from_environment();
Buffer<int32_t> result = f.realize(10, 10, t, params);
Alternatively, an initializer list can be used directly in the realize call to pass this information:
Param<int32> p(42);
ImageParam img(Int(32), 1);
f(x) = img(x) + p;
Buffer<int32_t) arg_img(10, 10);
<fill in arg_img...>
Target t = get_jit_target_from_environment();
Buffer<int32_t> result = f.realize(10, 10, t, { { p, 17 }, { img, arg_img } });
Realization Halide::Func::realize (const Target & target = Target(), const ParamMap & param_map = ParamMap::empty_map())
Evaluate this function over some rectangular domain and return the resulting buffer or buffers.
Performs compilation if the Func has not previously been realized and jit_compile has not been called. If the final stage of the pipeline is on the GPU, data is copied back to the host before being returned. The returned Realization should probably be instantly converted to a Buffer class of the appropriate type. That is, do this:
f(x) = sin(x);
Buffer<float> im = f.realize(...);
If your Func has multiple values, because you defined it using a Tuple, then casting the result of a realize call to a buffer or image will produce a run-time error. Instead you should do the following:
f(x) = Tuple(x, sin(x));
Realization r = f.realize(...);
Buffer<int> im0 = r[0];
Buffer<float> im1 = r[1];
In Halide formal arguments of a computation are specified using Param<T> and ImageParam objects in the expressions defining the computation. The param_map argument to realize allows specifying a set of per-call parameters to be used for a specific computation. This method is thread-safe where the globals used by Param<T> and ImageParam are not. Any parameters that are not in the param_map are taken from the global values, so those can continue to be used if they are not changing per-thread.
One can explicitly construct a ParamMap and use its set method to insert Parameter to scalar or Buffer value mappings:
Param<int32> p(42);
ImageParam img(Int(32), 1);
f(x) = img(x) + p;
Buffer<int32_t) arg_img(10, 10);
<fill in arg_img...>
ParamMap params;
params.set(p, 17);
params.set(img, arg_img);
Target t = get_jit_target_from_environment();
Buffer<int32_t> result = f.realize(10, 10, t, params);
Alternatively, an initializer list can be used directly in the realize call to pass this information:
Param<int32> p(42);
ImageParam img(Int(32), 1);
f(x) = img(x) + p;
Buffer<int32_t) arg_img(10, 10);
<fill in arg_img...>
Target t = get_jit_target_from_environment();
Buffer<int32_t> result = f.realize(10, 10, t, { { p, 17 }, { img, arg_img } });
void Halide::Func::realize (Pipeline::RealizationArg outputs, const Target & target = Target(), const ParamMap & param_map = ParamMap::empty_map())
Evaluate this function into an existing allocated buffer or buffers.
If the buffer is also one of the arguments to the function, strange things may happen, as the pipeline isn't necessarily safe to run in-place. If you pass multiple buffers, they must have matching sizes. This form of realize does not automatically copy data back from the GPU.
void Halide::Func::infer_input_bounds (int x_size = 0, int y_size = 0, int z_size = 0, int w_size = 0, const ParamMap & param_map = ParamMap::empty_map())
For a given size of output, or a given output buffer, determine the bounds required of all unbound ImageParams referenced.
Communicates the result by allocating new buffers of the appropriate size and binding them to the unbound ImageParams.
Set the documentation for Func::realize regarding the ParamMap. There is one difference in that input Buffer<> arguments that are being inferred are specified as a pointer to the Buffer<> in the ParamMap. E.g.
Param<int32> p(42);
ImageParam img(Int(32), 1);
f(x) = img(x) + p;
Target t = get_jit_target_from_environment();
Buffer<> in;
f.infer_input_bounds(10, 10, t, { { img, &in } });
On return, in will be an allocated buffer of the correct size to evaulate f over a 10x10 region.
void Halide::Func::infer_input_bounds (Pipeline::RealizationArg outputs, const ParamMap & param_map = ParamMap::empty_map())
For a given size of output, or a given output buffer, determine the bounds required of all unbound ImageParams referenced.
Communicates the result by allocating new buffers of the appropriate size and binding them to the unbound ImageParams.
Set the documentation for Func::realize regarding the ParamMap. There is one difference in that input Buffer<> arguments that are being inferred are specified as a pointer to the Buffer<> in the ParamMap. E.g.
Param<int32> p(42);
ImageParam img(Int(32), 1);
f(x) = img(x) + p;
Target t = get_jit_target_from_environment();
Buffer<> in;
f.infer_input_bounds(10, 10, t, { { img, &in } });
On return, in will be an allocated buffer of the correct size to evaulate f over a 10x10 region.
void Halide::Func::compile_to_bitcode (const std::string & filename, const std::vector< Argument > & , const std::string & fn_name, const Target & target = get_target_from_environment())
Statically compile this function to llvm bitcode, with the given filename (which should probably end in .bc), type signature, and C function name (which defaults to the same name as this halide function.
void Halide::Func::compile_to_bitcode (const std::string & filename, const std::vector< Argument > & , const Target & target = get_target_from_environment())
Statically compile this function to llvm bitcode, with the given filename (which should probably end in .bc), type signature, and C function name (which defaults to the same name as this halide function.
void Halide::Func::compile_to_llvm_assembly (const std::string & filename, const std::vector< Argument > & , const std::string & fn_name, const Target & target = get_target_from_environment())
Statically compile this function to llvm assembly, with the given filename (which should probably end in .ll), type signature, and C function name (which defaults to the same name as this halide function.
void Halide::Func::compile_to_llvm_assembly (const std::string & filename, const std::vector< Argument > & , const Target & target = get_target_from_environment())
Statically compile this function to llvm assembly, with the given filename (which should probably end in .ll), type signature, and C function name (which defaults to the same name as this halide function.
void Halide::Func::compile_to_object (const std::string & filename, const std::vector< Argument > & , const std::string & fn_name, const Target & target = get_target_from_environment())
Statically compile this function to an object file, with the given filename (which should probably end in .o or .obj), type signature, and C function name (which defaults to the same name as this halide function.
You probably don't want to use this directly; call compile_to_static_library or compile_to_file instead.
void Halide::Func::compile_to_object (const std::string & filename, const std::vector< Argument > & , const Target & target = get_target_from_environment())
Statically compile this function to an object file, with the given filename (which should probably end in .o or .obj), type signature, and C function name (which defaults to the same name as this halide function.
You probably don't want to use this directly; call compile_to_static_library or compile_to_file instead.
void Halide::Func::compile_to_header (const std::string & filename, const std::vector< Argument > & , const std::string & fn_name = "", const Target & target = get_target_from_environment())
Emit a header file with the given filename for this function.
The header will define a function with the type signature given by the second argument, and a name given by the third. The name defaults to the same name as this halide function. You don't actually have to have defined this function yet to call this. You probably don't want to use this directly; call compile_to_static_library or compile_to_file instead.
void Halide::Func::compile_to_assembly (const std::string & filename, const std::vector< Argument > & , const std::string & fn_name, const Target & target = get_target_from_environment())
Statically compile this function to text assembly equivalent to the object file generated by compile_to_object.
This is useful for checking what Halide is producing without having to disassemble anything, or if you need to feed the assembly into some custom toolchain to produce an object file (e.g. iOS)
void Halide::Func::compile_to_assembly (const std::string & filename, const std::vector< Argument > & , const Target & target = get_target_from_environment())
Statically compile this function to text assembly equivalent to the object file generated by compile_to_object.
This is useful for checking what Halide is producing without having to disassemble anything, or if you need to feed the assembly into some custom toolchain to produce an object file (e.g. iOS)
void Halide::Func::compile_to_c (const std::string & filename, const std::vector< Argument > & , const std::string & fn_name = "", const Target & target = get_target_from_environment())
Statically compile this function to C source code.
This is useful for providing fallback code paths that will compile on many platforms. Vectorization will fail, and parallelization will produce serial code.
void Halide::Func::compile_to_lowered_stmt (const std::string & filename, const std::vector< Argument > & args, StmtOutputFormat fmt = Text, const Target & target = get_target_from_environment())
Write out an internal representation of lowered code.
Useful for analyzing and debugging scheduling. Can emit html or plain text.
void Halide::Func::compile_to_python_extension (const std::string & filename_prefix, const std::vector< Argument > & args, const std::string & fn_name, const Target & target = get_target_from_environment())
Emit a Python Extension glue .c file.
void Halide::Func::print_loop_nest ()
Write out the loop nests specified by the schedule for this Function.
Helpful for understanding what a schedule is doing.
void Halide::Func::compile_to_file (const std::string & filename_prefix, const std::vector< Argument > & args, const std::string & fn_name = "", const Target & target = get_target_from_environment())
Compile to object file and header pair, with the given arguments.
The name defaults to the same name as this halide function.
void Halide::Func::compile_to_static_library (const std::string & filename_prefix, const std::vector< Argument > & args, const std::string & fn_name = "", const Target & target = get_target_from_environment())
Compile to static-library file and header pair, with the given arguments.
The name defaults to the same name as this halide function.
void Halide::Func::compile_to_multitarget_static_library (const std::string & filename_prefix, const std::vector< Argument > & args, const std::vector< Target > & targets)
Compile to static-library file and header pair once for each target; each resulting function will be considered (in order) via halide_can_use_target_features() at runtime, with the first appropriate match being selected for subsequent use.
This is typically useful for specializations that may vary unpredictably by machine (e.g., SSE4.1/AVX/AVX2 on x86 desktop machines). All targets must have identical arch-os-bits.
Module Halide::Func::compile_to_module (const std::vector< Argument > & args, const std::string & fn_name = "", const Target & target = get_target_from_environment())
Store an internal representation of lowered code as a self contained Module suitable for further compilation.
void Halide::Func::compile_to (const Outputs & output_files, const std::vector< Argument > & args, const std::string & fn_name, const Target & target = get_target_from_environment())
Compile and generate multiple target files with single call.
Deduces target files based on filenames specified in output_files struct.
void* Halide::Func::compile_jit (const Target & target = get_jit_target_from_environment())
Eagerly jit compile the function to machine code.
This normally happens on the first call to realize. If you're running your halide pipeline inside time-sensitive code and wish to avoid including the time taken to compile a pipeline, then you can call this ahead of time. Returns the raw function pointer to the compiled pipeline. Default is to use the Target returned from Halide::get_jit_target_from_environment()
void Halide::Func::set_error_handler (void(*)(void *, const char *) handler)
Set the error handler function that be called in the case of runtime errors during halide pipelines.
If you are compiling statically, you can also just define your own function with signature
extern "C" void halide_error(void *user_context, const char *);
This will clobber Halide's version.
void Halide::Func::set_custom_allocator (void *(*)(void *, size_t) malloc, void(*)(void *, void *) free)
void Halide::Func::set_custom_do_task (int(*)(void *, int(*)(void *, int, uint8_t *), int, uint8_t *) custom_do_task)
Set a custom task handler to be called by the parallel for loop.
It is useful to set this if you want to do some additional bookkeeping at the granularity of parallel tasks. The default implementation does this:
extern "C" int halide_do_task(void *user_context,
                              int (*f)(void *, int, uint8_t *),
                              int idx, uint8_t *state) {
    return f(user_context, idx, state);
}
If you are statically compiling, you can also just define your own version of the above function, and it will clobber Halide's version.
If you're trying to use a custom parallel runtime, you probably don't want to call this. See instead Func::set_custom_do_par_for .
void Halide::Func::set_custom_do_par_for (int(*)(void *, int(*)(void *, int, uint8_t *), int, int, uint8_t *) custom_do_par_for)
Set a custom parallel for loop launcher.
Useful if your app already manages a thread pool. The default implementation is equivalent to this:
extern "C" int halide_do_par_for(void *user_context,
                                 int (*f)(void *, int, uint8_t *),
                                 int min, int extent, uint8_t *state) {
    int exit_status = 0;
    parallel for (int idx = min; idx < min+extent; idx++) {
        int job_status = halide_do_task(user_context, f, idx, state);
        if (job_status) exit_status = job_status;
    }
    return exit_status;
}
However, notwithstanding the above example code, if one task fails, we may skip over other tasks, and if two tasks return different error codes, we may select one arbitrarily to return.
If you are statically compiling, you can also just define your own version of the above function, and it will clobber Halide's version.
void Halide::Func::set_custom_trace (int(*)(void *, const halide_trace_event_t *) trace_fn)
Set custom routines to call when tracing is enabled.
Call this on the output Func of your pipeline. This then sets custom routines for the entire pipeline, not just calls to this Func.
If you are statically compiling, you can also just define your own versions of the tracing functions (see HalideRuntime.h), and they will clobber Halide's versions.
void Halide::Func::set_custom_print (void(*)(void *, const char *) handler)
Set the function called to print messages from the runtime.
If you are compiling statically, you can also just define your own function with signature
extern "C" void halide_print(void *user_context, const char *);
This will clobber Halide's version.
const Internal::JITHandlers& Halide::Func::jit_handlers ()
Get a struct containing the currently set custom functions used by JIT.
template<typename T > void Halide::Func::add_custom_lowering_pass (T * pass) inline
Add a custom pass to be used during lowering.
It is run after all other lowering passes. Can be used to verify properties of the lowered Stmt, instrument it with extra code, or otherwise modify it. The Func takes ownership of the pass, and will call delete on it when the Func goes out of scope. So don't pass a stack object, or share pass instances between multiple Funcs.
Definition at line 1034 of file Func.h.
References Halide::Internal::debug_to_file(), and Halide::VarOrRVar::name().
void Halide::Func::add_custom_lowering_pass (Internal::IRMutator2 * pass, std::function< void()> deleter)
Add a custom pass to be used during lowering, with the function that will be called to delete it also passed in.
Set it to nullptr if you wish to retain ownership of the object.
void Halide::Func::clear_custom_lowering_passes ()
Remove all previously-set custom lowering passes.
const std::vector<CustomLoweringPass>& Halide::Func::custom_lowering_passes ()
Get the custom lowering passes.
void Halide::Func::debug_to_file (const std::string & filename)
When this function is compiled, include code that dumps its values to a file after it is realized, for the purpose of debugging.
If filename ends in ".tif" or ".tiff" (case insensitive) the file is in TIFF format and can be read by standard tools. Oherwise, the file format is as follows:
All data is in the byte-order of the target platform. First, a 20 byte-header containing four 32-bit ints, giving the extents of the first four dimensions. Dimensions beyond four are folded into the fourth. Then, a fifth 32-bit int giving the data type of the function. The typecodes are given by: float = 0, double = 1, uint8_t = 2, int8_t = 3, uint16_t = 4, int16_t = 5, uint32_t = 6, int32_t = 7, uint64_t = 8, int64_t = 9. The data follows the header, as a densely packed array of the given size and the given type. If given the extension .tmp, this file format can be natively read by the program ImageStack.
const std::string& Halide::Func::name () const
The name of this function, either given during construction, or automatically generated.
Referenced by Halide::Derivative::funcs(), and Halide::Derivative::operator()().
std::vector<Var> Halide::Func::args () const
Get the pure arguments.
Expr Halide::Func::value () const
The right-hand-side value of the pure definition of this function.
Causes an error if there's no pure definition, or if the function is defined to return multiple values.
Tuple Halide::Func::values () const
The values returned by this function.
An error if the function has not been been defined. Returns a Tuple with one element for functions defined to return a single value.
bool Halide::Func::defined () const
Does this function have at least a pure definition.
const std::vector<Expr>& Halide::Func::update_args (int idx = 0) const
Get the left-hand-side of the update definition.
An empty vector if there's no update definition. If there are multiple update definitions for this function, use the argument to select which one you want.
Expr Halide::Func::update_value (int idx = 0) const
Get the right-hand-side of an update definition.
An error if there's no update definition. If there are multiple update definitions for this function, use the argument to select which one you want.
Tuple Halide::Func::update_values (int idx = 0) const
Get the right-hand-side of an update definition for functions that returns multiple values.
An error if there's no update definition. Returns a Tuple with one element for functions that return a single value.
std::vector<RVar> Halide::Func::rvars (int idx = 0) const
Get the RVars of the reduction domain for an update definition, if there is one.
bool Halide::Func::has_update_definition () const
Does this function have at least one update definition?
int Halide::Func::num_update_definitions () const
How many update definitions does this function have?
Referenced by Halide::Derivative::funcs().
bool Halide::Func::is_extern () const
Is this function an external stage? That is, was it defined using define_extern?
void Halide::Func::define_extern (const std::string & function_name, const std::vector< ExternFuncArgument > & params, Type t, int dimensionality, NameMangling mangling, bool uses_old_buffer_t) inline
Add an extern definition for this Func.
This lets you define a Func that represents an external pipeline stage. You can, for example, use it to wrap a call to an extern library such as fftw.
Definition at line 1129 of file Func.h.
References Halide::Internal::make_argument_list().
void Halide::Func::define_extern (const std::string & function_name, const std::vector< ExternFuncArgument > & params, Type t, int dimensionality, NameMangling mangling = NameMangling::Default, DeviceAPI device_api = DeviceAPI::Host, bool uses_old_buffer_t = false) inline
Add an extern definition for this Func.
This lets you define a Func that represents an external pipeline stage. You can, for example, use it to wrap a call to an extern library such as fftw.
Definition at line 1140 of file Func.h.
References Halide::Internal::make_argument_list().
void Halide::Func::define_extern (const std::string & function_name, const std::vector< ExternFuncArgument > & params, const std::vector< Type > & types, int dimensionality, NameMangling mangling, bool uses_old_buffer_t) inline
Add an extern definition for this Func.
This lets you define a Func that represents an external pipeline stage. You can, for example, use it to wrap a call to an extern library such as fftw.
Definition at line 1152 of file Func.h.
References Halide::Internal::make_argument_list().
void Halide::Func::define_extern (const std::string & function_name, const std::vector< ExternFuncArgument > & params, const std::vector< Type > & types, int dimensionality, NameMangling mangling = NameMangling::Default, DeviceAPI device_api = DeviceAPI::Host, bool uses_old_buffer_t = false) inline
Add an extern definition for this Func.
This lets you define a Func that represents an external pipeline stage. You can, for example, use it to wrap a call to an extern library such as fftw.
Definition at line 1163 of file Func.h.
References Halide::Internal::make_argument_list().
void Halide::Func::define_extern (const std::string & function_name, const std::vector< ExternFuncArgument > & params, Type t, const std::vector< Var > & arguments, NameMangling mangling, bool uses_old_buffer_t) inline
Add an extern definition for this Func.
This lets you define a Func that represents an external pipeline stage. You can, for example, use it to wrap a call to an extern library such as fftw.
Definition at line 1175 of file Func.h.
void Halide::Func::define_extern (const std::string & function_name, const std::vector< ExternFuncArgument > & params, Type t, const std::vector< Var > & arguments, NameMangling mangling = NameMangling::Default, DeviceAPI device_api = DeviceAPI::Host, bool uses_old_buffer_t = false) inline
Add an extern definition for this Func.
This lets you define a Func that represents an external pipeline stage. You can, for example, use it to wrap a call to an extern library such as fftw.
Definition at line 1185 of file Func.h.
void Halide::Func::define_extern (const std::string & function_name, const std::vector< ExternFuncArgument > & params, const std::vector< Type > & types, const std::vector< Var > & arguments, NameMangling mangling, bool uses_old_buffer_t) inline
Add an extern definition for this Func.
This lets you define a Func that represents an external pipeline stage. You can, for example, use it to wrap a call to an extern library such as fftw.
Definition at line 1196 of file Func.h.
References Halide::Default, HALIDE_NO_USER_CODE_INLINE, and Halide::Host.
void Halide::Func::define_extern (const std::string & function_name, const std::vector< ExternFuncArgument > & params, const std::vector< Type > & types, const std::vector< Var > & arguments, NameMangling mangling = NameMangling::Default, DeviceAPI device_api = DeviceAPI::Host, bool uses_old_buffer_t = false)
Add an extern definition for this Func.
This lets you define a Func that represents an external pipeline stage. You can, for example, use it to wrap a call to an extern library such as fftw.
const std::vector<Type>& Halide::Func::output_types () const
Get the types of the outputs of this Func.
int Halide::Func::outputs () const
Get the number of outputs of this Func.
Corresponds to the size of the Tuple this Func was defined to return.
const std::string& Halide::Func::extern_function_name () const
Get the name of the extern function called for an extern definition.
int Halide::Func::dimensions () const
The dimensionality (number of arguments) of this function.
Zero if the function is not yet defined.
FuncRef Halide::Func::operator() (std::vector< Var >) const
Construct either the left-hand-side of a definition, or a call to a functions that happens to only contain vars as arguments.
If the function has already been defined, and fewer arguments are given than the function has dimensions, then enough implicit vars are added to the end of the argument list to make up the difference (see Var::implicit)
template<typename... Args> HALIDE_NO_USER_CODE_INLINE std::enable_if<Internal::all_are_convertible<Var, Args...>::value, FuncRef>::type Halide::Func::operator() (Args &&... args) const inline
Construct either the left-hand-side of a definition, or a call to a functions that happens to only contain vars as arguments.
If the function has already been defined, and fewer arguments are given than the function has dimensions, then enough implicit vars are added to the end of the argument list to make up the difference (see Var::implicit)
Definition at line 1241 of file Func.h.
References HALIDE_NO_USER_CODE_INLINE.
FuncRef Halide::Func::operator() (std::vector< Expr >) const
Either calls to the function, or the left-hand-side of an update definition (see RDom).
If the function has already been defined, and fewer arguments are given than the function has dimensions, then enough implicit vars are added to the end of the argument list to make up the difference. (see Var::implicit)
template<typename... Args> HALIDE_NO_USER_CODE_INLINE std::enable_if<Internal::all_are_convertible<Expr, Args...>::value, FuncRef>::type Halide::Func::operator() (Expr x, Args &&... args) const inline
Either calls to the function, or the left-hand-side of an update definition (see RDom).
If the function has already been defined, and fewer arguments are given than the function has dimensions, then enough implicit vars are added to the end of the argument list to make up the difference. (see Var::implicit)
Definition at line 1258 of file Func.h.
References Halide::Auto, Halide::Default_GPU, HALIDE_NO_USER_CODE_INLINE, Halide::min(), Halide::VarOrRVar::var, and Halide::VarOrRVar::VarOrRVar().
Func Halide::Func::in (const Func & f)
Creates and returns a new identity Func that wraps this Func.
During compilation, Halide replaces all calls to this Func done by 'f' with calls to the wrapper. If this Func is already wrapped for use in 'f', will return the existing wrapper.
For example, g.in(f) would rewrite a pipeline like this:
g(x, y) = ...
f(x, y) = ... g(x, y) ...
into a pipeline like this:
g(x, y) = ...
g_wrap(x, y) = g(x, y)
f(x, y) = ... g_wrap(x, y)
This has a variety of uses. You can use it to schedule this Func differently in the different places it is used:
g(x, y) = ...
f1(x, y) = ... g(x, y) ...
f2(x, y) = ... g(x, y) ...
g.in(f1).compute_at(f1, y).vectorize(x, 8);
g.in(f2).compute_at(f2, x).unroll(x);
You can also use it to stage loads from this Func via some intermediate buffer (perhaps on the stack as in test/performance/block_transpose.cpp, or in shared GPU memory as in test/performance/wrap.cpp). In this we compute the wrapper at tiles of the consuming Funcs like so:
g.compute_root()...
g.in(f).compute_at(f, tiles)...
Func::in() can also be used to compute pieces of a Func into a smaller scratch buffer (perhaps on the GPU) and then copy them into a larger output buffer one tile at a time. See apps/interpolate/interpolate.cpp for an example of this. In this case we compute the Func at tiles of its own wrapper:
f.in(g).compute_root().gpu_tile(...)...
f.compute_at(f.in(g), tiles)...
A similar use of Func::in() wrapping Funcs with multiple update stages in a pure wrapper. The following code:
f(x, y) = x + y;
f(x, y) += 5;
g(x, y) = f(x, y);
f.compute_root();
Is equivalent to:
for y:
  for x:
    f(x, y) = x + y;
for y:
  for x:
    f(x, y) += 5
for y:
  for x:
    g(x, y) = f(x, y)
using Func::in(), we can write:
f(x, y) = x + y;
f(x, y) += 5;
g(x, y) = f(x, y);
f.in(g).compute_root();
which instead produces:
for y:
  for x:
    f(x, y) = x + y;
    f(x, y) += 5
    f_wrap(x, y) = f(x, y)
for y:
  for x:
    g(x, y) = f_wrap(x, y)
Referenced by Halide::Internal::GeneratorInput_Buffer< T >::in(), and Halide::Internal::GeneratorInput_Func< T >::in().
Func Halide::Func::in (const std::vector< Func > & fs)
Create and return an identity wrapper shared by all the Funcs in 'fs'.
If any of the Funcs in 'fs' already have a custom wrapper, this will throw an error.
Func Halide::Func::in ()
Create and return a global identity wrapper, which wraps all calls to this Func by any other Func.
If a global wrapper already exists, returns it. The global identity wrapper is only used by callers for which no custom wrapper has been specified.
Func Halide::Func::clone_in (const Func & f)
Similar to Func::in; however, instead of replacing the call to this Func with an identity Func that refers to it, this replaces the call with a clone of this Func.
For example, f.clone_in(g) would rewrite a pipeline like this:
f(x, y) = x + y;
g(x, y) = f(x, y) + 2;
h(x, y) = f(x, y) - 3;
into a pipeline like this:
f(x, y) = x + y;
f_clone(x, y) = x + y;
g(x, y) = f_clone(x, y) + 2;
h(x, y) = f(x, y) - 3;
Func Halide::Func::clone_in (const std::vector< Func > & fs)
Similar to Func::in; however, instead of replacing the call to this Func with an identity Func that refers to it, this replaces the call with a clone of this Func.
For example, f.clone_in(g) would rewrite a pipeline like this:
f(x, y) = x + y;
g(x, y) = f(x, y) + 2;
h(x, y) = f(x, y) - 3;
into a pipeline like this:
f(x, y) = x + y;
f_clone(x, y) = x + y;
g(x, y) = f_clone(x, y) + 2;
h(x, y) = f(x, y) - 3;
Func Halide::Func::copy_to_device (DeviceAPI d = DeviceAPI::Default_GPU)
Declare that this function should be implemented by a call to halide_buffer_copy with the given target device API.
Asserts that the Func has a pure definition which is a simple call to a single input, and no update definitions. The wrapper Funcs returned by in() are suitable candidates. Consumes all pure variables, and rewrites the Func to have an extern definition that calls halide_buffer_copy.
Func Halide::Func::copy_to_host ()
Declare that this function should be implemented by a call to halide_buffer_copy with a NULL target device API.
Equivalent to copy_to_device(DeviceAPI::Host). Asserts that the Func has a pure definition which is a simple call to a single input, and no update definitions. The wrapper Funcs returned by in() are suitable candidates. Consumes all pure variables, and rewrites the Func to have an extern definition that calls halide_buffer_copy.
Note that if the source Func is already valid in host memory, this compiles to code that does the minimum number of calls to memcpy.
Func& Halide::Func::split (VarOrRVar old, VarOrRVar outer, VarOrRVar inner, Expr factor, TailStrategy tail = TailStrategy::Auto)
Split a dimension into inner and outer subdimensions with the given names, where the inner dimension iterates from 0 to factor-1.
The inner and outer subdimensions can then be dealt with using the other scheduling calls. It's ok to reuse the old variable name as either the inner or outer variable. The final argument specifies how the tail should be handled if the split factor does not provably divide the extent.
Func& Halide::Func::fuse (VarOrRVar inner, VarOrRVar outer, VarOrRVar fused)
Join two dimensions into a single fused dimenion.
The fused dimension covers the product of the extents of the inner and outer dimensions given.
Func& Halide::Func::serial (VarOrRVar var)
Mark a dimension to be traversed serially.
This is the default.
Func& Halide::Func::parallel (VarOrRVar var)
Mark a dimension to be traversed in parallel.
Func& Halide::Func::parallel (VarOrRVar var, Expr task_size, TailStrategy tail = TailStrategy::Auto)
Split a dimension by the given task_size, and the parallelize the outer dimension.
This creates parallel tasks that have size task_size. After this call, var refers to the outer dimension of the split. The inner dimension has a new anonymous name. If you wish to mutate it, or schedule with respect to it, do the split manually.
Func& Halide::Func::vectorize (VarOrRVar var)
Mark a dimension to be computed all-at-once as a single vector.
The dimension should have constant extent - e.g. because it is the inner dimension following a split by a constant factor. For most uses of vectorize you want the two argument form. The variable to be vectorized should be the innermost one.
Func& Halide::Func::unroll (VarOrRVar var)
Mark a dimension to be completely unrolled.
The dimension should have constant extent - e.g. because it is the inner dimension following a split by a constant factor. For most uses of unroll you want the two-argument form.
Func& Halide::Func::vectorize (VarOrRVar var, Expr factor, TailStrategy tail = TailStrategy::Auto)
Split a dimension by the given factor, then vectorize the inner dimension.
This is how you vectorize a loop of unknown size. The variable to be vectorized should be the innermost one. After this call, var refers to the outer dimension of the split. 'factor' must be an integer.
Func& Halide::Func::unroll (VarOrRVar var, Expr factor, TailStrategy tail = TailStrategy::Auto)
Split a dimension by the given factor, then unroll the inner dimension.
This is how you unroll a loop of unknown size by some constant factor. After this call, var refers to the outer dimension of the split. 'factor' must be an integer.
Func& Halide::Func::bound (Var var, Expr min, Expr extent)
Statically declare that the range over which a function should be evaluated is given by the second and third arguments.
This can let Halide perform some optimizations. E.g. if you know there are going to be 4 color channels, you can completely vectorize the color channel dimension without the overhead of splitting it up. If bounds inference decides that it requires more of this function than the bounds you have stated, a runtime error will occur when you try to run your pipeline.
Func& Halide::Func::estimate (Var var, Expr min, Expr extent)
Statically declare the range over which the function will be evaluated in the general case.
This provides a basis for the auto scheduler to make trade-offs and scheduling decisions. The auto generated schedules might break when the sizes of the dimensions are very different from the estimates specified. These estimates are used only by the auto scheduler if the function is a pipeline output.
Referenced by Halide::Internal::GeneratorOutput_Func< T >::estimate().
Func& Halide::Func::align_bounds (Var var, Expr modulus, Expr remainder = 0)
Expand the region computed so that the min coordinates is congruent to 'remainder' modulo 'modulus', and the extent is a multiple of 'modulus'.
For example, f.align_bounds(x, 2) forces the min and extent realized to be even, and calling f.align_bounds(x, 2, 1) forces the min to be odd and the extent to be even. The region computed always contains the region that would have been computed without this directive, so no assertions are injected.
Func& Halide::Func::bound_extent (Var var, Expr extent)
Bound the extent of a Func's realization, but not its min.
This means the dimension can be unrolled or vectorized even when its min is not fixed (for example because it is compute_at tiles of another Func). This can also be useful for forcing a function's allocation to be a fixed size, which often means it can go on the stack.
Func& Halide::Func::tile (VarOrRVar x, VarOrRVar y, VarOrRVar xo, VarOrRVar yo, VarOrRVar xi, VarOrRVar yi, Expr xfactor, Expr yfactor, TailStrategy tail = TailStrategy::Auto)
Split two dimensions at once by the given factors, and then reorder the resulting dimensions to be xi, yi, xo, yo from innermost outwards.
This gives a tiled traversal.
Func& Halide::Func::tile (VarOrRVar x, VarOrRVar y, VarOrRVar xi, VarOrRVar yi, Expr xfactor, Expr yfactor, TailStrategy tail = TailStrategy::Auto)
A shorter form of tile, which reuses the old variable names as the new outer dimensions.
Func& Halide::Func::reorder (const std::vector< VarOrRVar > & vars)
Reorder variables to have the given nesting order, from innermost out.
template<typename... Args> HALIDE_NO_USER_CODE_INLINE std::enable_if<Internal::all_are_convertible<VarOrRVar, Args...>::value, Func &>::type Halide::Func::reorder (VarOrRVar x, VarOrRVar y, Args &&... args) inline
Definition at line 1526 of file Func.h.
References Halide::Auto, Halide::Default_GPU, Halide::GuardWithIf, Halide::Runtime::Internal::offset, and Halide::Var::outermost().
Func& Halide::Func::rename (VarOrRVar old_name, VarOrRVar new_name)
Rename a dimension.
Equivalent to split with a inner size of one.
Func& Halide::Func::allow_race_conditions ()
Specify that race conditions are permitted for this Func, which enables parallelizing over RVars even when Halide cannot prove that it is safe to do so.
Use this with great caution, and only if you can prove to yourself that this is safe, as it may result in a non-deterministic routine that returns different values at different times or on different machines.
Stage Halide::Func::specialize (Expr condition)
Specialize a Func.
This creates a special-case version of the Func where the given condition is true. The most effective conditions are those of the form param == value, and boolean Params. Consider a simple example:
f(x) = x + select(cond, 0, 1);
f.compute_root();
This is equivalent to:
for (int x = 0; x < width; x++) {
  f[x] = x + (cond ? 0 : 1);
}
Adding the scheduling directive:
f.specialize(cond)
makes it equivalent to:
if (cond) {
  for (int x = 0; x < width; x++) {
    f[x] = x;
  }
} else {
  for (int x = 0; x < width; x++) {
    f[x] = x + 1;
  }
}
Note that the inner loops have been simplified. In the first path Halide knows that cond is true, and in the second path Halide knows that it is false.
The specialized version gets its own schedule, which inherits every directive made about the parent Func's schedule so far except for its specializations. This method returns a handle to the new schedule. If you wish to retrieve the specialized sub-schedule again later, you can call this method with the same condition. Consider the following example of scheduling the specialized version:
f(x) = x;
f.compute_root();
f.specialize(width > 1).unroll(x, 2);
Assuming for simplicity that width is even, this is equivalent to:
if (width > 1) {
  for (int x = 0; x < width/2; x++) {
    f[2*x] = 2*x;
    f[2*x + 1] = 2*x + 1;
  }
} else {
  for (int x = 0; x < width/2; x++) {
    f[x] = x;
  }
}
For this case, it may be better to schedule the un-specialized case instead:
f(x) = x;
f.compute_root();
f.specialize(width == 1); // Creates a copy of the schedule so far.
f.unroll(x, 2); // Only applies to the unspecialized case.
This is equivalent to:
if (width == 1) {
  f[0] = 0;
} else {
  for (int x = 0; x < width/2; x++) {
    f[2*x] = 2*x;
    f[2*x + 1] = 2*x + 1;
  }
}
This can be a good way to write a pipeline that splits, vectorizes, or tiles, but can still handle small inputs.
If a Func has several specializations, the first matching one will be used, so the order in which you define specializations is significant. For example:
f(x) = x + select(cond1, a, b) - select(cond2, c, d);
f.specialize(cond1);
f.specialize(cond2);
is equivalent to:
if (cond1) {
  for (int x = 0; x < width; x++) {
    f[x] = x + a - (cond2 ? c : d);
  }
} else if (cond2) {
  for (int x = 0; x < width; x++) {
    f[x] = x + b - c;
  }
} else {
  for (int x = 0; x < width; x++) {
    f[x] = x + b - d;
  }
}
Specializations may in turn be specialized, which creates a nested if statement in the generated code.
f(x) = x + select(cond1, a, b) - select(cond2, c, d);
f.specialize(cond1).specialize(cond2);
This is equivalent to:
if (cond1) {
  if (cond2) {
    for (int x = 0; x < width; x++) {
      f[x] = x + a - c;
    }
  } else {
    for (int x = 0; x < width; x++) {
      f[x] = x + a - d;
    }
  }
} else {
  for (int x = 0; x < width; x++) {
    f[x] = x + b - (cond2 ? c : d);
  }
}
To create a 4-way if statement that simplifies away all of the ternary operators above, you could say:
f.specialize(cond1).specialize(cond2);
f.specialize(cond2);
or
f.specialize(cond1 && cond2);
f.specialize(cond1);
f.specialize(cond2);
Any prior Func which is compute_at some variable of this Func gets separately included in all paths of the generated if statement. The Var in the compute_at call to must exist in all paths, but it may have been generated via a different path of splits, fuses, and renames. This can be used somewhat creatively. Consider the following code:
g(x, y) = 8*x;
f(x, y) = g(x, y) + 1;
f.compute_root().specialize(cond);
Var g_loop;
f.specialize(cond).rename(y, g_loop);
f.rename(x, g_loop);
g.compute_at(f, g_loop);
When cond is true, this is equivalent to g.compute_at(f,y). When it is false, this is equivalent to g.compute_at(f,x).
void Halide::Func::specialize_fail (const std::string & message)
Add a specialization to a Func that always terminates execution with a call to halide_error().
By itself, this is of limited use, but can be useful to terminate chains of specialize() calls where no "default" case is expected (thus avoiding unnecessary code generation).
For instance, say we want to optimize a pipeline to process images in planar and interleaved format; we might typically do something like:
ImageParam im(UInt(8), 3);
Func f = do_something_with(im);
f.specialize(im.dim(0).stride() == 1).vectorize(x, 8);  // planar
f.specialize(im.dim(2).stride() == 1).reorder(c, x, y).vectorize(c);  // interleaved
This code will vectorize along rows for the planar case, and across pixel components for the interleaved case... but there is an implicit "else" for the unhandled cases, which generates unoptimized code. If we never anticipate passing any other sort of images to this, we code streamline our code by adding specialize_fail():
ImageParam im(UInt(8), 3);
Func f = do_something(im);
f.specialize(im.dim(0).stride() == 1).vectorize(x, 8);  // planar
f.specialize(im.dim(2).stride() == 1).reorder(c, x, y).vectorize(c);  // interleaved
f.specialize_fail("Unhandled image format");
Conceptually, this produces codes like:
if (im.dim(0).stride() == 1) {
   do_something_planar();
} else if (im.dim(2).stride() == 1) {
   do_something_interleaved();
} else {
   halide_error("Unhandled image format");
}
Note that calling specialize_fail() terminates the specialization chain for a given Func; you cannot create new specializations for the Func afterwards (though you can retrieve handles to previous specializations).
Func& Halide::Func::gpu_threads (VarOrRVar thread_x, DeviceAPI device_api = DeviceAPI::Default_GPU)
Tell Halide that the following dimensions correspond to GPU thread indices.
This is useful if you compute a producer function within the block indices of a consumer function, and want to control how that function's dimensions map to GPU threads. If the selected target is not an appropriate GPU, this just marks those dimensions as parallel.
Func& Halide::Func::gpu_threads (VarOrRVar thread_x, VarOrRVar thread_y, DeviceAPI device_api = DeviceAPI::Default_GPU)
Tell Halide that the following dimensions correspond to GPU thread indices.
This is useful if you compute a producer function within the block indices of a consumer function, and want to control how that function's dimensions map to GPU threads. If the selected target is not an appropriate GPU, this just marks those dimensions as parallel.
Func& Halide::Func::gpu_threads (VarOrRVar thread_x, VarOrRVar thread_y, VarOrRVar thread_z, DeviceAPI device_api = DeviceAPI::Default_GPU)
Tell Halide that the following dimensions correspond to GPU thread indices.
This is useful if you compute a producer function within the block indices of a consumer function, and want to control how that function's dimensions map to GPU threads. If the selected target is not an appropriate GPU, this just marks those dimensions as parallel.
Func& Halide::Func::gpu_lanes (VarOrRVar thread_x, DeviceAPI device_api = DeviceAPI::Default_GPU)
The given dimension corresponds to the lanes in a GPU warp.
GPU warp lanes are distinguished from GPU threads by the fact that all warp lanes run together in lockstep, which permits lightweight communication of data from one lane to another.
Func& Halide::Func::gpu_single_thread (DeviceAPI device_api = DeviceAPI::Default_GPU)
Tell Halide to run this stage using a single gpu thread and block.
This is not an efficient use of your GPU, but it can be useful to avoid copy-back for intermediate update stages that touch a very small part of your Func.
Referenced by Halide::Internal::schedule_scalar().
Func& Halide::Func::gpu_blocks (VarOrRVar block_x, DeviceAPI device_api = DeviceAPI::Default_GPU)
Tell Halide that the following dimensions correspond to GPU block indices.
This is useful for scheduling stages that will run serially within each GPU block. If the selected target is not ptx, this just marks those dimensions as parallel.
Func& Halide::Func::gpu_blocks (VarOrRVar block_x, VarOrRVar block_y, DeviceAPI device_api = DeviceAPI::Default_GPU)
Tell Halide that the following dimensions correspond to GPU block indices.
This is useful for scheduling stages that will run serially within each GPU block. If the selected target is not ptx, this just marks those dimensions as parallel.
Func& Halide::Func::gpu_blocks (VarOrRVar block_x, VarOrRVar block_y, VarOrRVar block_z, DeviceAPI device_api = DeviceAPI::Default_GPU)
Tell Halide that the following dimensions correspond to GPU block indices.
This is useful for scheduling stages that will run serially within each GPU block. If the selected target is not ptx, this just marks those dimensions as parallel.
Func& Halide::Func::gpu (VarOrRVar block_x, VarOrRVar thread_x, DeviceAPI device_api = DeviceAPI::Default_GPU)
Tell Halide that the following dimensions correspond to GPU block indices and thread indices.
If the selected target is not ptx, these just mark the given dimensions as parallel. The dimensions are consumed by this call, so do all other unrolling, reordering, etc first.
Func& Halide::Func::gpu (VarOrRVar block_x, VarOrRVar block_y, VarOrRVar thread_x, VarOrRVar thread_y, DeviceAPI device_api = DeviceAPI::Default_GPU)
Tell Halide that the following dimensions correspond to GPU block indices and thread indices.
If the selected target is not ptx, these just mark the given dimensions as parallel. The dimensions are consumed by this call, so do all other unrolling, reordering, etc first.
Func& Halide::Func::gpu (VarOrRVar block_x, VarOrRVar block_y, VarOrRVar block_z, VarOrRVar thread_x, VarOrRVar thread_y, VarOrRVar thread_z, DeviceAPI device_api = DeviceAPI::Default_GPU)
Tell Halide that the following dimensions correspond to GPU block indices and thread indices.
If the selected target is not ptx, these just mark the given dimensions as parallel. The dimensions are consumed by this call, so do all other unrolling, reordering, etc first.
Func& Halide::Func::gpu_tile (VarOrRVar x, VarOrRVar bx, VarOrRVar tx, Expr x_size, TailStrategy tail = TailStrategy::Auto, DeviceAPI device_api = DeviceAPI::Default_GPU)
Short-hand for tiling a domain and mapping the tile indices to GPU block indices and the coordinates within each tile to GPU thread indices.
Consumes the variables given, so do all other scheduling first.
Func& Halide::Func::gpu_tile (VarOrRVar x, VarOrRVar tx, Expr x_size, TailStrategy tail = TailStrategy::Auto, DeviceAPI device_api = DeviceAPI::Default_GPU)
Short-hand for tiling a domain and mapping the tile indices to GPU block indices and the coordinates within each tile to GPU thread indices.
Consumes the variables given, so do all other scheduling first.
Func& Halide::Func::gpu_tile (VarOrRVar x, VarOrRVar y, VarOrRVar bx, VarOrRVar by, VarOrRVar tx, VarOrRVar ty, Expr x_size, Expr y_size, TailStrategy tail = TailStrategy::Auto, DeviceAPI device_api = DeviceAPI::Default_GPU)
Short-hand for tiling a domain and mapping the tile indices to GPU block indices and the coordinates within each tile to GPU thread indices.
Consumes the variables given, so do all other scheduling first.
Func& Halide::Func::gpu_tile (VarOrRVar x, VarOrRVar y, VarOrRVar tx, VarOrRVar ty, Expr x_size, Expr y_size, TailStrategy tail = TailStrategy::Auto, DeviceAPI device_api = DeviceAPI::Default_GPU)
Short-hand for tiling a domain and mapping the tile indices to GPU block indices and the coordinates within each tile to GPU thread indices.
Consumes the variables given, so do all other scheduling first.
Func& Halide::Func::gpu_tile (VarOrRVar x, VarOrRVar y, VarOrRVar z, VarOrRVar bx, VarOrRVar by, VarOrRVar bz, VarOrRVar tx, VarOrRVar ty, VarOrRVar tz, Expr x_size, Expr y_size, Expr z_size, TailStrategy tail = TailStrategy::Auto, DeviceAPI device_api = DeviceAPI::Default_GPU)
Short-hand for tiling a domain and mapping the tile indices to GPU block indices and the coordinates within each tile to GPU thread indices.
Consumes the variables given, so do all other scheduling first.
Func& Halide::Func::gpu_tile (VarOrRVar x, VarOrRVar y, VarOrRVar z, VarOrRVar tx, VarOrRVar ty, VarOrRVar tz, Expr x_size, Expr y_size, Expr z_size, TailStrategy tail = TailStrategy::Auto, DeviceAPI device_api = DeviceAPI::Default_GPU)
Short-hand for tiling a domain and mapping the tile indices to GPU block indices and the coordinates within each tile to GPU thread indices.
Consumes the variables given, so do all other scheduling first.
Func& Halide::Func::shader (Var x, Var y, Var c, DeviceAPI device_api)
Schedule for execution using coordinate-based hardware api.
GLSL is an example of this. Conceptually, this is similar to parallelization over 'x' and 'y' (since GLSL shaders compute individual output pixels in parallel) and vectorization over 'c' (since GLSL/RS implicitly vectorizes the color channel).
Func& Halide::Func::glsl (Var x, Var y, Var c)
Schedule for execution as GLSL kernel.
Func& Halide::Func::hexagon (VarOrRVar x = Var::outermost())
Schedule for execution on Hexagon.
When a loop is marked with Hexagon, that loop is executed on a Hexagon DSP.
Referenced by Halide::Internal::schedule_scalar().
Func& Halide::Func::prefetch (const Func & f, VarOrRVar var, Expr offset = 1, PrefetchBoundStrategy strategy = PrefetchBoundStrategy::GuardWithIf)
Prefetch data written to or read from a Func or an ImageParam by a subsequent loop iteration, at an optionally specified iteration offset.
'var' specifies at which loop level the prefetch calls should be inserted. The final argument specifies how prefetch of region outside bounds should be handled.
For example, consider this pipeline:
Func f, g;
Var x, y;
f(x, y) = x + y;
g(x, y) = 2 * f(x, y);
The following schedule:
f.compute_root();
g.prefetch(f, x, 2, PrefetchBoundStrategy::NonFaulting);
will inject prefetch call at the innermost loop of 'g' and generate the following loop nest: for y = ... for x = ... f(x, y) = x + y for y = .. for x = ... prefetch(&f[x + 2, y], 1, 16); g(x, y) = 2 * f(x, y)
Func& Halide::Func::prefetch (const Internal::Parameter & param, VarOrRVar var, Expr offset = 1, PrefetchBoundStrategy strategy = PrefetchBoundStrategy::GuardWithIf)
Prefetch data written to or read from a Func or an ImageParam by a subsequent loop iteration, at an optionally specified iteration offset.
'var' specifies at which loop level the prefetch calls should be inserted. The final argument specifies how prefetch of region outside bounds should be handled.
For example, consider this pipeline:
Func f, g;
Var x, y;
f(x, y) = x + y;
g(x, y) = 2 * f(x, y);
The following schedule:
f.compute_root();
g.prefetch(f, x, 2, PrefetchBoundStrategy::NonFaulting);
will inject prefetch call at the innermost loop of 'g' and generate the following loop nest: for y = ... for x = ... f(x, y) = x + y for y = .. for x = ... prefetch(&f[x + 2, y], 1, 16); g(x, y) = 2 * f(x, y)
template<typename T > Func& Halide::Func::prefetch (const T & image, VarOrRVar var, Expr offset = 1, PrefetchBoundStrategy strategy = PrefetchBoundStrategy::GuardWithIf) inline
Prefetch data written to or read from a Func or an ImageParam by a subsequent loop iteration, at an optionally specified iteration offset.
'var' specifies at which loop level the prefetch calls should be inserted. The final argument specifies how prefetch of region outside bounds should be handled.
For example, consider this pipeline:
Func f, g;
Var x, y;
f(x, y) = x + y;
g(x, y) = 2 * f(x, y);
The following schedule:
f.compute_root();
g.prefetch(f, x, 2, PrefetchBoundStrategy::NonFaulting);
will inject prefetch call at the innermost loop of 'g' and generate the following loop nest: for y = ... for x = ... f(x, y) = x + y for y = .. for x = ... prefetch(&f[x + 2, y], 1, 16); g(x, y) = 2 * f(x, y)
Definition at line 1887 of file Func.h.
References HALIDE_NO_USER_CODE_INLINE, Halide::Runtime::Internal::offset, and Halide::VarOrRVar::var.
Func& Halide::Func::reorder_storage (const std::vector< Var > & dims)
Specify how the storage for the function is laid out.
These calls let you specify the nesting order of the dimensions. For example, foo.reorder_storage(y, x) tells Halide to use column-major storage for any realizations of foo, without changing how you refer to foo in the code. You may want to do this if you intend to vectorize across y. When representing color images, foo.reorder_storage(c, x, y) specifies packed storage (red, green, and blue values adjacent in memory), and foo.reorder_storage(x, y, c) specifies planar storage (entire red, green, and blue images one after the other in memory).
If you leave out some dimensions, those remain in the same positions in the nesting order while the specified variables are reordered around them.
Func& Halide::Func::reorder_storage (Var x, Var y)
Specify how the storage for the function is laid out.
These calls let you specify the nesting order of the dimensions. For example, foo.reorder_storage(y, x) tells Halide to use column-major storage for any realizations of foo, without changing how you refer to foo in the code. You may want to do this if you intend to vectorize across y. When representing color images, foo.reorder_storage(c, x, y) specifies packed storage (red, green, and blue values adjacent in memory), and foo.reorder_storage(x, y, c) specifies planar storage (entire red, green, and blue images one after the other in memory).
If you leave out some dimensions, those remain in the same positions in the nesting order while the specified variables are reordered around them.
template<typename... Args> HALIDE_NO_USER_CODE_INLINE std::enable_if<Internal::all_are_convertible<Var, Args...>::value, Func &>::type Halide::Func::reorder_storage (Var x, Var y, Args &&... args) inline
Specify how the storage for the function is laid out.
These calls let you specify the nesting order of the dimensions. For example, foo.reorder_storage(y, x) tells Halide to use column-major storage for any realizations of foo, without changing how you refer to foo in the code. You may want to do this if you intend to vectorize across y. When representing color images, foo.reorder_storage(c, x, y) specifies packed storage (red, green, and blue values adjacent in memory), and foo.reorder_storage(x, y, c) specifies planar storage (entire red, green, and blue images one after the other in memory).
If you leave out some dimensions, those remain in the same positions in the nesting order while the specified variables are reordered around them.
Definition at line 1913 of file Func.h.
References Halide::Auto.
Func& Halide::Func::align_storage (Var dim, Expr alignment)
Pad the storage extent of a particular dimension of realizations of this function up to be a multiple of the specified alignment.
This guarantees that the strides for the dimensions stored outside of dim will be multiples of the specified alignment, where the strides and alignment are measured in numbers of elements.
For example, to guarantee that a function foo(x, y, c) representing an image has scanlines starting on offsets aligned to multiples of 16, use foo.align_storage(x, 16).
Func& Halide::Func::fold_storage (Var dim, Expr extent, bool fold_forward = true)
Store realizations of this function in a circular buffer of a given extent.
This is more efficient when the extent of the circular buffer is a power of 2. If the fold factor is too small, or the dimension is not accessed monotonically, the pipeline will generate an error at runtime.
The fold_forward option indicates that the new values of the producer are accessed by the consumer in a monotonically increasing order. Folding storage of producers is also supported if the new values are accessed in a monotonically decreasing order by setting fold_forward to false.
For example, consider the pipeline:
Func f, g;
Var x, y;
g(x, y) = x*y;
f(x, y) = g(x, y) + g(x, y+1);
If we schedule f like so:
g.compute_at(f, y).store_root().fold_storage(y, 2);
Then g will be computed at each row of f and stored in a buffer with an extent in y of 2, alternately storing each computed row of g in row y=0 or y=1.
Func& Halide::Func::compute_at (Func f, Var var)
Compute this function as needed for each unique value of the given var for the given calling function f.
For example, consider the simple pipeline:
Func f, g;
Var x, y;
g(x, y) = x*y;
f(x, y) = g(x, y) + g(x, y+1) + g(x+1, y) + g(x+1, y+1);
If we schedule f like so:
g.compute_at(f, x);
Then the C code equivalent to this pipeline will look like this
int f[height][width];
for (int y = 0; y < height; y++) {
    for (int x = 0; x < width; x++) {
        int g[2][2];
        g[0][0] = x*y;
        g[0][1] = (x+1)*y;
        g[1][0] = x*(y+1);
        g[1][1] = (x+1)*(y+1);
        f[y][x] = g[0][0] + g[1][0] + g[0][1] + g[1][1];
    }
}
The allocation and computation of g is within f's loop over x, and enough of g is computed to satisfy all that f will need for that iteration. This has excellent locality - values of g are used as soon as they are computed, but it does redundant work. Each value of g ends up getting computed four times. If we instead schedule f like so:
g.compute_at(f, y);
The equivalent C code is:
int f[height][width];
for (int y = 0; y < height; y++) {
    int g[2][width+1];
    for (int x = 0; x < width; x++) {
        g[0][x] = x*y;
        g[1][x] = x*(y+1);
    }
    for (int x = 0; x < width; x++) {
        f[y][x] = g[0][x] + g[1][x] + g[0][x+1] + g[1][x+1];
    }
}
The allocation and computation of g is within f's loop over y, and enough of g is computed to satisfy all that f will need for that iteration. This does less redundant work (each point in g ends up being evaluated twice), but the locality is not quite as good, and we have to allocate more temporary memory to store g.
Func& Halide::Func::compute_at (Func f, RVar var)
Schedule a function to be computed within the iteration over some dimension of an update domain.
Produces equivalent code to the version of compute_at that takes a Var.
Func& Halide::Func::compute_at (LoopLevel loop_level)
Schedule a function to be computed within the iteration over a given LoopLevel.
Func& Halide::Func::compute_with (Stage s, VarOrRVar var, const std::vector< std::pair< VarOrRVar, LoopAlignStrategy >> & align)
Schedule the iteration over the initial definition of this function to be fused with another stage 's' from outermost loop to a given LoopLevel.
See Stage::compute_with
Func& Halide::Func::compute_with (Stage s, VarOrRVar var, LoopAlignStrategy align = LoopAlignStrategy::Auto)
Schedule the iteration over the initial definition of this function to be fused with another stage 's' from outermost loop to a given LoopLevel.
See Stage::compute_with
Func& Halide::Func::compute_with (LoopLevel loop_level, const std::vector< std::pair< VarOrRVar, LoopAlignStrategy >> & align)
Schedule the iteration over the initial definition of this function to be fused with another stage 's' from outermost loop to a given LoopLevel.
See Stage::compute_with
Func& Halide::Func::compute_with (LoopLevel loop_level, LoopAlignStrategy align = LoopAlignStrategy::Auto)
Schedule the iteration over the initial definition of this function to be fused with another stage 's' from outermost loop to a given LoopLevel.
See Stage::compute_with
Func& Halide::Func::compute_root ()
Compute all of this function once ahead of time.
Reusing the example in Func::compute_at :
Func f, g;
Var x, y;
g(x, y) = x*y;
f(x, y) = g(x, y) + g(x, y+1) + g(x+1, y) + g(x+1, y+1);
g.compute_root();
is equivalent to
int f[height][width];
int g[height+1][width+1];
for (int y = 0; y < height+1; y++) {
    for (int x = 0; x < width+1; x++) {
        g[y][x] = x*y;
    }
}
for (int y = 0; y < height; y++) {
    for (int x = 0; x < width; x++) {
        f[y][x] = g[y][x] + g[y+1][x] + g[y][x+1] + g[y+1][x+1];
    }
}
g is computed once ahead of time, and enough is computed to satisfy all uses of it. This does no redundant work (each point in g is evaluated once), but has poor locality (values of g are probably not still in cache when they are used by f), and allocates lots of temporary memory to store g.
Func& Halide::Func::memoize ()
Use the halide_memoization_cache_...
interface to store a computed version of this function across invocations of the Func.
Func& Halide::Func::store_at (Func f, Var var)
Allocate storage for this function within f's loop over var.
Scheduling storage is optional, and can be used to separate the loop level at which storage occurs from the loop level at which computation occurs to trade off between locality and redundant work. This can open the door for two types of optimization.
Consider again the pipeline from Func::compute_at :
Func f, g;
Var x, y;
g(x, y) = x*y;
f(x, y) = g(x, y) + g(x+1, y) + g(x, y+1) + g(x+1, y+1);
If we schedule it like so:
g.compute_at(f, x).store_at(f, y);
Then the computation of g takes place within the loop over x, but the storage takes place within the loop over y:
int f[height][width];
for (int y = 0; y < height; y++) {
    int g[2][width+1];
    for (int x = 0; x < width; x++) {
        g[0][x] = x*y;
        g[0][x+1] = (x+1)*y;
        g[1][x] = x*(y+1);
        g[1][x+1] = (x+1)*(y+1);
        f[y][x] = g[0][x] + g[1][x] + g[0][x+1] + g[1][x+1];
    }
}
Provided the for loop over x is serial, halide then automatically performs the following sliding window optimization:
int f[height][width];
for (int y = 0; y < height; y++) {
    int g[2][width+1];
    for (int x = 0; x < width; x++) {
        if (x == 0) {
            g[0][x] = x*y;
            g[1][x] = x*(y+1);
        }
        g[0][x+1] = (x+1)*y;
        g[1][x+1] = (x+1)*(y+1);
        f[y][x] = g[0][x] + g[1][x] + g[0][x+1] + g[1][x+1];
    }
}
Two of the assignments to g only need to be done when x is zero. The rest of the time, those sites have already been filled in by a previous iteration. This version has the locality of compute_at(f, x), but allocates more memory and does much less redundant work.
Halide then further optimizes this pipeline like so:
int f[height][width];
for (int y = 0; y < height; y++) {
    int g[2][2];
    for (int x = 0; x < width; x++) {
        if (x == 0) {
            g[0][0] = x*y;
            g[1][0] = x*(y+1);
        }
        g[0][(x+1)%2] = (x+1)*y;
        g[1][(x+1)%2] = (x+1)*(y+1);
        f[y][x] = g[0][x%2] + g[1][x%2] + g[0][(x+1)%2] + g[1][(x+1)%2];
    }
}
Halide has detected that it's possible to use a circular buffer to represent g, and has reduced all accesses to g modulo 2 in the x dimension. This optimization only triggers if the for loop over x is serial, and if halide can statically determine some power of two large enough to cover the range needed. For powers of two, the modulo operator compiles to more efficient bit-masking. This optimization reduces memory usage, and also improves locality by reusing recently-accessed memory instead of pulling new memory into cache.
Func& Halide::Func::store_at (Func f, RVar var)
Equivalent to the version of store_at that takes a Var, but schedules storage within the loop over a dimension of a reduction domain.
Func& Halide::Func::store_at (LoopLevel loop_level)
Equivalent to the version of store_at that takes a Var, but schedules storage at a given LoopLevel.
Func& Halide::Func::store_root ()
Equivalent to Func::store_at, but schedules storage outside the outermost loop.
Func& Halide::Func::compute_inline ()
Aggressively inline all uses of this function.
This is the default schedule, so you're unlikely to need to call this. For a Func with an update definition, that means it gets computed as close to the innermost loop as possible.
Consider once more the pipeline from Func::compute_at :
Func f, g;
Var x, y;
g(x, y) = x*y;
f(x, y) = g(x, y) + g(x+1, y) + g(x, y+1) + g(x+1, y+1);
Leaving g as inline, this compiles to code equivalent to the following C:
int f[height][width];
for (int y = 0; y < height; y++) {
    for (int x = 0; x < width; x++) {
        f[y][x] = x*y + x*(y+1) + (x+1)*y + (x+1)*(y+1);
    }
}
Stage Halide::Func::update (int idx = 0)
Get a handle on an update step for the purposes of scheduling it.
Func& Halide::Func::store_in (MemoryType memory_type)
Set the type of memory this Func should be stored in.
Controls whether allocations go on the stack or the heap on the CPU, and in global vs shared vs local on the GPU. See the documentation on MemoryType for more detail.
Func& Halide::Func::trace_loads ()
Trace all loads from this Func by emitting calls to halide_trace.
If the Func is inlined, this has no effect.
Func& Halide::Func::trace_stores ()
Trace all stores to the buffer backing this Func by emitting calls to halide_trace.
If the Func is inlined, this call has no effect.
Func& Halide::Func::trace_realizations ()
Trace all realizations of this Func by emitting calls to halide_trace.
Func& Halide::Func::add_trace_tag (const std::string & trace_tag)
Add a string of arbitrary text that will be passed thru to trace inspection code if the Func is realized in trace mode.
(Funcs that are inlined won't have their tags emitted.) Ignored entirely if tracing is not enabled for the Func (or globally).
Internal::Function Halide::Func::function () const inline
Get a handle on the internal halide function that this Func represents.
Useful if you want to do introspection on Halide functions
Definition at line 2266 of file Func.h.
Halide::Func::operator Stage () const
You can cast a Func to its pure stage for the purposes of scheduling it.
OutputImageParam Halide::Func::output_buffer () const
Get a handle on the output buffer for this Func.
Only relevant if this is the output Func in a pipeline. Useful for making static promises about strides, mins, and extents.
std::vector<OutputImageParam> Halide::Func::output_buffers () const
Schedule the iteration over the initial definition of this function to be fused with another stage 's' from outermost loop to a given LoopLevel.
See Stage::compute_with
Halide::Func::operator ExternFuncArgument () const inline
Use a Func as an argument to an external stage.
Definition at line 2283 of file Func.h.
References Halide::Internal::infer_arguments(), and Halide::Internal.
std::vector<Argument> Halide::Func::infer_arguments () const
Infer the arguments to the Func, sorted into a canonical order: all buffers (sorted alphabetically by name), followed by all non-buffers (sorted alphabetically by name).
This lets you write things like:
func.compile_to_assembly("/dev/stdout", func.infer_arguments());
std::string Halide::Func::source_location () const
Get the source location of the pure definition of this Func.
See Stage::source_location()
The documentation for this class was generated from the following file:
Func.h