Halide: Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C Class Reference
Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C Class Reference
#include <CodeGen_D3D12Compute_Dev.h>
Inherits Halide::Internal::CodeGen_C.
Public Member Functions
CodeGen_D3D12Compute_C (std::ostream &s, Target t)
void add_kernel (Stmt stmt, const std::string &name, const std::vector< DeviceArgument > &args)
Public Member Functions inherited from Halide::Internal::CodeGen_C
CodeGen_C (std::ostream &dest, Target target, OutputKind output_kind=CImplementation, const std::string &include_guard="")
Initialize a C code generator pointing at a particular output stream (e.g.
~CodeGen_C ()
void compile (const Module &module)
Emit the declarations contained in the module as C code.
const Target & get_target () const
The target we're generating code for.
Public Member Functions inherited from Halide::Internal::IRPrinter
virtual ~IRPrinter ()
IRPrinter (std::ostream &)
Construct an IRPrinter pointed at a given output stream (e.g.
void print (Expr)
emit an expression on the output stream
void print (Stmt)
emit a statement on the output stream
void print_list (const std::vector< Expr > &exprs)
emit a comma delimited list of exprs, without any leading or trailing punctuation.
Public Member Functions inherited from Halide::Internal::IRVisitor
IRVisitor ()
virtual ~IRVisitor ()
Protected Member Functions
std::string print_type (Type type, AppendSpaceIfNeeded space_option=DoNotAppendSpace)
Emit the C name for a halide type.
std::string print_storage_type (Type type)
std::string print_type_maybe_storage (Type type, bool storage, AppendSpaceIfNeeded space)
std::string print_reinterpret (Type type, Expr e)
Emit a statement to reinterpret an expression as another type.
std::string print_extern_call (const Call *op)
Bottleneck to allow customization of calls to generic Extern/PureExtern calls.
std::string print_vanilla_cast (Type type, std::string value_expr)
std::string print_reinforced_cast (Type type, std::string value_expr)
std::string print_cast (Type target_type, Type source_type, std::string value_expr)
std::string print_reinterpret_cast (Type type, std::string value_expr)
virtual std::string print_assignment (Type t, const std::string &rhs)
Emit an SSA-style assignment, and set id to the freshly generated name.
void visit (const Evaluate *op)
void visit (const Min *)
void visit (const Max *)
void visit (const Div *)
void visit (const Mod *)
void visit (const For *)
void visit (const Ramp *op)
void visit (const Broadcast *op)
void visit (const Load *op)
void visit (const Store *op)
void visit (const Select *op)
void visit (const Allocate *op)
void visit (const Free *op)
void visit (const Cast *op)
Protected Member Functions inherited from Halide::Internal::CodeGen_C
std::string print_expr (Expr)
Emit an expression as an assignment, then return the id of the resulting var.
std::string print_cast_expr (const Type &, Expr)
Like print_expr, but cast the Expr to the given Type.
void print_stmt (Stmt)
Emit a statement.
void create_assertion (const std::string &id_cond, const std::string &id_msg)
void create_assertion (const std::string &id_cond, Expr message)
void create_assertion (Expr cond, Expr message)
virtual std::string print_name (const std::string &)
Emit a version of a string that is a valid identifier in C (.
virtual void add_vector_typedefs (const std::set< Type > &vector_types)
Add typedefs for vector types.
std::string print_scalarized_expr (Expr e)
Convert a vector Expr into a series of scalar Exprs, then reassemble into vector of original type.
bool is_header ()
Return true if only generating an interface, which may be extern "C" or C++.
bool is_c_plus_plus_interface ()
Return true if generating C++ linkage.
void open_scope ()
Open a new C scope (i.e.
void close_scope (const std::string &comment)
Close a C scope (i.e.
void forward_declare_type_if_needed (const Type &t)
If the Type is a handle type, emit a forward-declaration for it if we haven't already.
void set_name_mangling_mode (NameMangling mode)
void visit (const Variable *)
void visit (const IntImm *)
void visit (const UIntImm *)
void visit (const StringImm *)
void visit (const FloatImm *)
void visit (const Add *)
void visit (const Sub *)
void visit (const Mul *)
void visit (const EQ *)
void visit (const NE *)
void visit (const LT *)
void visit (const LE *)
void visit (const GT *)
void visit (const GE *)
void visit (const And *)
void visit (const Or *)
void visit (const Not *)
void visit (const Call *)
void visit (const Let *)
void visit (const LetStmt *)
void visit (const AssertStmt *)
void visit (const ProducerConsumer *)
void visit (const Provide *)
void visit (const Realize *)
void visit (const IfThenElse *)
void visit (const Shuffle *)
void visit (const Prefetch *)
void visit_binop (Type t, Expr a, Expr b, const char *op)
virtual void compile (const LoweredFunc &func)
Emit a declaration.
virtual void compile (const Buffer<> &buffer)
Emit a declaration.
Protected Member Functions inherited from Halide::Internal::IRPrinter
void do_indent ()
Emit spaces according to the current indentation level.
void visit (const IntImm *)
void visit (const UIntImm *)
void visit (const FloatImm *)
void visit (const StringImm *)
void visit (const Cast *)
void visit (const Variable *)
void visit (const Add *)
void visit (const Sub *)
void visit (const Mul *)
void visit (const Div *)
void visit (const Mod *)
void visit (const Min *)
void visit (const Max *)
void visit (const EQ *)
void visit (const NE *)
void visit (const LT *)
void visit (const LE *)
void visit (const GT *)
void visit (const GE *)
void visit (const And *)
void visit (const Or *)
void visit (const Not *)
void visit (const Select *)
void visit (const Load *)
void visit (const Ramp *)
void visit (const Broadcast *)
void visit (const Call *)
void visit (const Let *)
void visit (const LetStmt *)
void visit (const AssertStmt *)
void visit (const ProducerConsumer *)
void visit (const For *)
void visit (const Store *)
void visit (const Provide *)
void visit (const Allocate *)
void visit (const Free *)
void visit (const Realize *)
void visit (const Block *)
void visit (const IfThenElse *)
void visit (const Evaluate *)
void visit (const Shuffle *)
void visit (const Prefetch *)
Additional Inherited Members
Public Types inherited from Halide::Internal::CodeGen_C
Static Public Member Functions inherited from Halide::Internal::CodeGen_C
static void test ()
Static Public Member Functions inherited from Halide::Internal::IRPrinter
static void test ()
Protected Types inherited from Halide::Internal::CodeGen_C
Static Protected Member Functions inherited from Halide::Internal::CodeGen_C
template<typename T >
static std::string with_sep (const std::vector< T > &v, const std::string &sep)
template<typename T >
static std::string with_commas (const std::vector< T > &v)
Protected Attributes inherited from Halide::Internal::CodeGen_C
std::string id
An ID for the most recently generated ssa variable.
Target target
The target being generated for.
OutputKind output_kind
Controls whether this instance is generating declarations or definitions and whether the interface us extern "C" or C++.
std::map< std::string, std::string > cache
A cache of generated values in scope.
Scope< Allocation > allocations
Track the types of allocations to avoid unnecessary casts.
Scope heap_allocations
Track which allocations actually went on the heap.
bool have_user_context
True if there is a void * __user_context parameter in the arguments.
bool extern_c_open
Track current calling convention scope.
bool uses_gpu_for_loops
True if at least one gpu-based for loop is used.
std::set< const halide_handle_cplusplus_type * > forward_declared
Track which handle types have been forward-declared already.
Protected Attributes inherited from Halide::Internal::IRPrinter
std::ostream & stream
The stream we're outputting on.
int indent
The current indentation level, useful for pretty-printing statements.
Detailed Description
Definition at line 45 of file CodeGen_D3D12Compute_Dev.h.
Constructor & Destructor Documentation
Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::CodeGen_D3D12Compute_C (std::ostream & s, Target t) inline
Definition at line 47 of file CodeGen_D3D12Compute_Dev.h.
References add_kernel(), Halide::Internal::CodeGen_C::DoNotAppendSpace, print_assignment(), print_cast(), print_extern_call(), print_reinforced_cast(), print_reinterpret(), print_reinterpret_cast(), print_storage_type(), print_type(), print_type_maybe_storage(), print_vanilla_cast(), visit(), and Halide::Internal::CodeGen_C::visit().
Member Function Documentation
void Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::add_kernel (Stmt stmt, const std::string & name, const std::vector< DeviceArgument > & args)
Referenced by CodeGen_D3D12Compute_C().
std::string Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::print_type (Type , AppendSpaceIfNeeded space_option = DoNotAppendSpace) protected virtual
Emit the C name for a halide type.
If space_option is AppendSpace, and there should be a space between the type and the next token, one is appended. (This allows both "int foo" and "Foo *foo" to be formatted correctly. Otherwise the latter is "Foo * foo".)
Reimplemented from Halide::Internal::CodeGen_C.
Referenced by CodeGen_D3D12Compute_C().
std::string Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::print_storage_type (Type type) protected
Referenced by CodeGen_D3D12Compute_C().
std::string Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::print_type_maybe_storage (Type type, bool storage, AppendSpaceIfNeeded space) protected
Referenced by CodeGen_D3D12Compute_C().
std::string Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::print_reinterpret (Type , Expr) protected virtual
Emit a statement to reinterpret an expression as another type.
Reimplemented from Halide::Internal::CodeGen_C.
Referenced by CodeGen_D3D12Compute_C().
std::string Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::print_extern_call (const Call * op) protected virtual
Bottleneck to allow customization of calls to generic Extern/PureExtern calls.
Reimplemented from Halide::Internal::CodeGen_C.
Referenced by CodeGen_D3D12Compute_C().
std::string Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::print_vanilla_cast (Type type, std::string value_expr) protected
Referenced by CodeGen_D3D12Compute_C().
std::string Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::print_reinforced_cast (Type type, std::string value_expr) protected
Referenced by CodeGen_D3D12Compute_C().
std::string Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::print_cast (Type target_type, Type source_type, std::string value_expr) protected
Referenced by CodeGen_D3D12Compute_C().
std::string Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::print_reinterpret_cast (Type type, std::string value_expr) protected
Referenced by CodeGen_D3D12Compute_C().
virtual std::string Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::print_assignment (Type t, const std::string & rhs) protected virtual
Emit an SSA-style assignment, and set id to the freshly generated name.
Return id.
Reimplemented from Halide::Internal::CodeGen_C.
Referenced by CodeGen_D3D12Compute_C().
void Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::visit (const Evaluate * op) protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
Referenced by CodeGen_D3D12Compute_C().
void Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::visit (const Min *) protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
void Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::visit (const Max *) protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
void Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::visit (const Div *) protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
void Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::visit (const Mod *) protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
void Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::visit (const For *) protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
void Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::visit (const Ramp * op) protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
void Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::visit (const Broadcast * op) protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
void Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::visit (const Load * op) protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
void Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::visit (const Store * op) protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
void Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::visit (const Select * op) protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
void Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::visit (const Allocate * op) protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
void Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::visit (const Free * op) protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
void Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::visit (const Cast * op) protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
The documentation for this class was generated from the following file:
CodeGen_D3D12Compute_Dev.h