Halide: Halide::Internal::Scope< T > Class Template Reference
Halide::Internal::Scope< T > Class Template Reference
A common pattern when traversing Halide IR is that you need to keep track of stuff when you find a Let or a LetStmt, and that it should hide previous values with the same name until you leave the Let or LetStmt nodes This class helps with that.
#include <Scope.h>
Classes
class const_iterator
Iterate through the scope.
class iterator
Public Member Functions
Scope ()
void set_containing_scope (const Scope< T > *s)
Set the parent scope.
template<typename T2 = T, typename = typename std::enable_if<!std::is_same<T2, void>::value>::type>
T2 get (const std::string &name) const
Retrieve the value referred to by a name.
template<typename T2 = T, typename = typename std::enable_if<!std::is_same<T2, void>::value>::type>
T2 & ref (const std::string &name)
Return a reference to an entry.
bool contains (const std::string &name) const
Tests if a name is in scope.
template<typename T2 = T, typename = typename std::enable_if<!std::is_same<T2, void>::value>::type>
void push (const std::string &name, const T2 &value)
Add a new (name, value) pair to the current scope.
template<typename T2 = T, typename = typename std::enable_if<std::is_same<T2, void>::value>::type>
void push (const std::string &name)
void pop (const std::string &name)
A name goes out of scope.
const_iterator cbegin () const
const_iterator cend () const
iterator begin ()
iterator end ()
void swap (Scope< T > &other)
Static Public Member Functions
static const Scope< T > & empty_scope ()
A const ref to an empty scope.
Detailed Description
template<typename T = void>
class Halide::Internal::Scope< T >
A common pattern when traversing Halide IR is that you need to keep track of stuff when you find a Let or a LetStmt, and that it should hide previous values with the same name until you leave the Let or LetStmt nodes This class helps with that.
Definition at line 90 of file Scope.h.
Constructor & Destructor Documentation
template<typename T = void> Halide::Internal::Scope< T >::Scope () inline
Definition at line 102 of file Scope.h.
Member Function Documentation
template<typename T = void> void Halide::Internal::Scope< T >::set_containing_scope (const Scope< T > * s) inline
Set the parent scope.
If lookups fail in this scope, they check the containing scope before returning an error. Caller is responsible for managing the memory of the containing scope.
Definition at line 107 of file Scope.h.
Referenced by Halide::Internal::ExprUsesVars< T >::ExprUsesVars(), and Halide::Internal::HexagonAlignmentAnalyzer::HexagonAlignmentAnalyzer().
template<typename T = void> static const Scope<T>& Halide::Internal::Scope< T >::empty_scope () inline static
A const ref to an empty scope.
Useful for default function arguments, which would otherwise require a copy constructor (with llvm in c++98 mode)
Definition at line 114 of file Scope.h.
template<typename T = void> template<typename T2 = T, typename = typename std::enable_if<!std::is_same<T2, void>::value>::type> T2 Halide::Internal::Scope< T >::get (const std::string & name) const inline
Retrieve the value referred to by a name.
Definition at line 122 of file Scope.h.
Referenced by Halide::Internal::Scope< Halide::Expr >::get().
template<typename T = void> template<typename T2 = T, typename = typename std::enable_if<!std::is_same<T2, void>::value>::type> T2& Halide::Internal::Scope< T >::ref (const std::string & name) inline
Return a reference to an entry.
Does not consider the containing scope.
Definition at line 137 of file Scope.h.
template<typename T = void> bool Halide::Internal::Scope< T >::contains (const std::string & name) const inline
Tests if a name is in scope.
Definition at line 146 of file Scope.h.
Referenced by Halide::Internal::Scope< Halide::Expr >::contains().
template<typename T = void> template<typename T2 = T, typename = typename std::enable_if<!std::is_same<T2, void>::value>::type> void Halide::Internal::Scope< T >::push (const std::string & name, const T2 & value) inline
Add a new (name, value) pair to the current scope.
Hide old values that have this name until we pop this name.
Definition at line 163 of file Scope.h.
Referenced by Halide::Internal::HexagonAlignmentAnalyzer::push(), Halide::Internal::ScopedBinding< T >::ScopedBinding(), Halide::Internal::ScopedBinding< void >::ScopedBinding(), and Halide::Internal::stmt_or_expr_uses_var().
template<typename T = void> template<typename T2 = T, typename = typename std::enable_if<std::is_same<T2, void>::value>::type> void Halide::Internal::Scope< T >::push (const std::string & name) inline
Definition at line 169 of file Scope.h.
template<typename T = void> void Halide::Internal::Scope< T >::pop (const std::string & name) inline
A name goes out of scope.
Restore whatever its old value was (or remove it entirely if there was nothing else of the same name in an outer scope)
Definition at line 176 of file Scope.h.
Referenced by Halide::Internal::HexagonAlignmentAnalyzer::pop(), Halide::Internal::ScopedBinding< T >::~ScopedBinding(), and Halide::Internal::ScopedBinding< void >::~ScopedBinding().
template<typename T = void> const_iterator Halide::Internal::Scope< T >::cbegin () const inline
Definition at line 216 of file Scope.h.
template<typename T = void> const_iterator Halide::Internal::Scope< T >::cend () const inline
Definition at line 220 of file Scope.h.
template<typename T = void> iterator Halide::Internal::Scope< T >::begin () inline
Definition at line 254 of file Scope.h.
template<typename T = void> iterator Halide::Internal::Scope< T >::end () inline
Definition at line 258 of file Scope.h.
template<typename T = void> void Halide::Internal::Scope< T >::swap (Scope< T > & other) inline
Definition at line 262 of file Scope.h.
The documentation for this class was generated from the following file:
Scope.h