Halide: Halide::Buffer< T > Class Template Reference
Halide::Buffer< T > Class Template Reference
A Halide::Buffer is a named shared reference to a Halide::Runtime::Buffer.
#include <Buffer.h>
Public Types
typedef T ElemType
Public Member Functions
virtual ~Buffer ()
Buffer ()
Make a null Buffer, which points to no Runtime::Buffer.
template<typename T2 >
Buffer (const Buffer< T2 > &other)
Make a Buffer from a Buffer of a different type.
template<typename T2 >
Buffer (Buffer< T2 > &&other)
Move construct from a Buffer of a different type.
template<int D>
Buffer (Runtime::Buffer< T, D > &&buf, const std::string &name="")
Construct a Buffer that captures and owns an rvalue Runtime::Buffer.
template<typename T2 >
bool same_as (const Buffer< T2 > &other)
Check if two Buffer objects point to the same underlying Buffer.
bool defined () const
Check if this Buffer refers to an existing Buffer.
int copy_to_device (const Target &t=get_jit_target_from_environment())
Copy to the GPU, using the device API that is the default for the given Target.
int copy_to_device (const DeviceAPI &d, const Target &t=get_jit_target_from_environment())
Copy to the GPU, using the given device API.
int device_malloc (const Target &t=get_jit_target_from_environment())
Allocate on the GPU, using the device API that is the default for the given Target.
int device_malloc (const DeviceAPI &d, const Target &t=get_jit_target_from_environment())
Allocate storage on the GPU, using the given device API.
int device_wrap_native (const DeviceAPI &d, uint64_t handle, const Target &t=get_jit_target_from_environment())
Wrap a native handle, using the given device API.
void set_name (const std::string &n)
Buffers are optionally named.
const std::string & name () const
Buffers are optionally named.
Runtime::Buffer< T > * get ()
Get a pointer to the underlying Runtime::Buffer.
const Runtime::Buffer< T > * get () const
Get a pointer to the underlying Runtime::Buffer.
template<typename... Args>
Expr operator() (Expr first, Args...rest) const
Make an Expr that loads from this concrete buffer at a computed coordinate.
template<typename... Args>
Expr operator() (const std::vector< Expr > &args) const
Make an Expr that loads from this concrete buffer at a computed coordinate.
template<typename... Args, typename = typename std::enable_if<Internal::all_ints_and_optional_name<Args...>::value>::type>
Buffer (Type t, int first, Args...rest)
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Buffer (const halide_buffer_t &buf, const std::string &name="")
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Buffer (const buffer_t &buf, const std::string &name="")
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
template<typename... Args, typename = typename std::enable_if<Internal::all_ints_and_optional_name<Args...>::value>::type>
Buffer (int first, Args...rest)
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Buffer (Type t, const std::vector< int > &sizes, const std::string &name="")
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Buffer (const std::vector< int > &sizes, const std::string &name="")
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
template<typename Array , size_t N>
Buffer (Array(&vals)[N], const std::string &name="")
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
template<typename... Args, typename = typename std::enable_if<Internal::all_ints_and_optional_name<Args...>::value>::type>
Buffer (Type t, Internal::add_const_if_T_is_const< T, void > *data, int first, Args &&...rest)
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
template<typename... Args, typename = typename std::enable_if<Internal::all_ints_and_optional_name<Args...>::value>::type>
Buffer (Type t, Internal::add_const_if_T_is_const< T, void > *data, const std::vector< int > &sizes, const std::string &name="")
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
template<typename... Args, typename = typename std::enable_if<Internal::all_ints_and_optional_name<Args...>::value>::type>
Buffer (T *data, int first, Args &&...rest)
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Buffer (T *data, const std::vector< int > &sizes, const std::string &name="")
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Buffer (Type t, Internal::add_const_if_T_is_const< T, void > *data, const std::vector< int > &sizes, const std::string &name="")
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Buffer (Type t, Internal::add_const_if_T_is_const< T, void > *data, int d, const halide_dimension_t *shape, const std::string &name="")
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Buffer (T *data, int d, const halide_dimension_t *shape, const std::string &name="")
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
static Buffer< T > make_scalar (const std::string &name="")
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
static Buffer make_scalar (Type t, const std::string &name="")
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
static Buffer< T > make_interleaved (int width, int height, int channels, const std::string &name="")
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
static Buffer make_interleaved (Type t, int width, int height, int channels, const std::string &name="")
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
static Buffer< T > make_interleaved (T *data, int width, int height, int channels, const std::string &name="")
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
static Buffer< Internal::add_const_if_T_is_const< T, void > > make_interleaved (Type t, T *data, int width, int height, int channels, const std::string &name="")
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
template<typename T2 >
static Buffer< T > make_with_shape_of (Buffer< T2 > src, void *(*allocate_fn)(size_t)=nullptr, void(*deallocate_fn)(void *)=nullptr, const std::string &name="")
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
template<typename T2 >
static Buffer< T > make_with_shape_of (const Runtime::Buffer< T2 > &src, void *(*allocate_fn)(size_t)=nullptr, void(*deallocate_fn)(void *)=nullptr, const std::string &name="")
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
static constexpr bool has_static_halide_type = Runtime::Buffer<T>::has_static_halide_type
Does the same thing as the equivalent Halide::Runtime::Buffer method.
template<typename Fn , typename... Args>
void for_each_value (Fn &&f, Args...other_buffers)
Does the same thing as the equivalent Halide::Runtime::Buffer method.
Type type () const
Does the same thing as the equivalent Halide::Runtime::Buffer method.
template<typename T2 >
Buffer< T2 > as () const
Does the same thing as the equivalent Halide::Runtime::Buffer method.
Buffer< T > copy () const
Does the same thing as the equivalent Halide::Runtime::Buffer method.
template<typename T2 >
void copy_from (const Buffer< T2 > &other)
Does the same thing as the equivalent Halide::Runtime::Buffer method.
template<typename... Args>
auto operator() (int first, Args &&...args) -> decltype(std::declval< Runtime::Buffer< T >>()(first, std::forward< Args >(args)...))
Does the same thing as the equivalent Halide::Runtime::Buffer method.
template<typename... Args>
auto operator() (int first, Args &&...args) const -> decltype(std::declval< const Runtime::Buffer< T >>()(first, std::forward< Args >(args)...))
Does the same thing as the equivalent Halide::Runtime::Buffer method.
auto operator() (const int *pos) -> decltype(std::declval< Runtime::Buffer< T >>()(pos))
Does the same thing as the equivalent Halide::Runtime::Buffer method.
auto operator() (const int *pos) const -> decltype(std::declval< const Runtime::Buffer< T >>()(pos))
Does the same thing as the equivalent Halide::Runtime::Buffer method.
auto operator() () -> decltype(std::declval< Runtime::Buffer< T >>()())
Does the same thing as the equivalent Halide::Runtime::Buffer method.
auto operator() () const -> decltype(std::declval< const Runtime::Buffer< T >>()())
Does the same thing as the equivalent Halide::Runtime::Buffer method.
static halide_type_t static_halide_type ()
Does the same thing as the equivalent Halide::Runtime::Buffer method.
template<typename T2 >
static bool can_convert_from (const Buffer< T2 > &other)
Does the same thing as the equivalent Halide::Runtime::Buffer method.
Detailed Description
template<typename T>
class Halide::Buffer< T >
A Halide::Buffer is a named shared reference to a Halide::Runtime::Buffer.
A Buffer<T1> can refer to a Buffer<T2> if T1 is const whenever T2 is const, and either T1 = T2 or T1 is void. A Buffer<void> can refer to any Buffer of any non-const type, and the default template parameter is T = void.
Definition at line 12 of file Buffer.h.
Member Typedef Documentation
template<typename T> typedef T Halide::Buffer< T >::ElemType
Definition at line 116 of file Buffer.h.
Constructor & Destructor Documentation
template<typename T> virtual Halide::Buffer< T >::~Buffer () inline virtual
Definition at line 120 of file Buffer.h.
template<typename T> Halide::Buffer< T >::Buffer () inline
Make a null Buffer, which points to no Runtime::Buffer.
Definition at line 123 of file Buffer.h.
template<typename T> template<typename T2 > Halide::Buffer< T >::Buffer (const Buffer< T2 > & other) inline
Make a Buffer from a Buffer of a different type.
Definition at line 127 of file Buffer.h.
template<typename T> template<typename T2 > Halide::Buffer< T >::Buffer (Buffer< T2 > && other) inline
Move construct from a Buffer of a different type.
Definition at line 134 of file Buffer.h.
template<typename T> template<int D> Halide::Buffer< T >::Buffer (Runtime::Buffer< T, D > && buf, const std::string & name = "") inline
Construct a Buffer that captures and owns an rvalue Runtime::Buffer.
Definition at line 141 of file Buffer.h.
template<typename T> template<typename... Args, typename = typename std::enable_if<Internal::all_ints_and_optional_name<Args...>::value>::type> Halide::Buffer< T >::Buffer (Type t, int first, Args... rest) inline explicit
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 158 of file Buffer.h.
template<typename T> Halide::Buffer< T >::Buffer (const halide_buffer_t & buf, const std::string & name = "") inline explicit
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 163 of file Buffer.h.
template<typename T> Halide::Buffer< T >::Buffer (const buffer_t & buf, const std::string & name = "") inline explicit
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 167 of file Buffer.h.
template<typename T> template<typename... Args, typename = typename std::enable_if<Internal::all_ints_and_optional_name<Args...>::value>::type> Halide::Buffer< T >::Buffer (int first, Args... rest) inline explicit
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 173 of file Buffer.h.
template<typename T> Halide::Buffer< T >::Buffer (Type t, const std::vector< int > & sizes, const std::string & name = "") inline explicit
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 177 of file Buffer.h.
template<typename T> Halide::Buffer< T >::Buffer (const std::vector< int > & sizes, const std::string & name = "") inline explicit
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 182 of file Buffer.h.
template<typename T> template<typename Array , size_t N> Halide::Buffer< T >::Buffer (Array(&) vals[N], const std::string & name = "") inline explicit
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 187 of file Buffer.h.
template<typename T> template<typename... Args, typename = typename std::enable_if<Internal::all_ints_and_optional_name<Args...>::value>::type> Halide::Buffer< T >::Buffer (Type t, Internal::add_const_if_T_is_const< T, void > * data, int first, Args &&... rest) inline explicit
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 193 of file Buffer.h.
template<typename T> template<typename... Args, typename = typename std::enable_if<Internal::all_ints_and_optional_name<Args...>::value>::type> Halide::Buffer< T >::Buffer (Type t, Internal::add_const_if_T_is_const< T, void > * data, const std::vector< int > & sizes, const std::string & name = "") inline explicit
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 201 of file Buffer.h.
template<typename T> template<typename... Args, typename = typename std::enable_if<Internal::all_ints_and_optional_name<Args...>::value>::type> Halide::Buffer< T >::Buffer (T * data, int first, Args &&... rest) inline explicit
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 209 of file Buffer.h.
template<typename T> Halide::Buffer< T >::Buffer (T * data, const std::vector< int > & sizes, const std::string & name = "") inline explicit
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 214 of file Buffer.h.
template<typename T> Halide::Buffer< T >::Buffer (Type t, Internal::add_const_if_T_is_const< T, void > * data, const std::vector< int > & sizes, const std::string & name = "") inline explicit
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 219 of file Buffer.h.
template<typename T> Halide::Buffer< T >::Buffer (Type t, Internal::add_const_if_T_is_const< T, void > * data, int d, const halide_dimension_t * shape, const std::string & name = "") inline explicit
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 225 of file Buffer.h.
template<typename T> Halide::Buffer< T >::Buffer (T * data, int d, const halide_dimension_t * shape, const std::string & name = "") inline explicit
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 232 of file Buffer.h.
Member Function Documentation
template<typename T> static Buffer<T> Halide::Buffer< T >::make_scalar (const std::string & name = "") inline static
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 239 of file Buffer.h.
template<typename T> static Buffer Halide::Buffer< T >::make_scalar (Type t, const std::string & name = "") inline static
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 243 of file Buffer.h.
template<typename T> static Buffer<T> Halide::Buffer< T >::make_interleaved (int width, int height, int channels, const std::string & name = "") inline static
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 247 of file Buffer.h.
template<typename T> static Buffer Halide::Buffer< T >::make_interleaved (Type t, int width, int height, int channels, const std::string & name = "") inline static
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 252 of file Buffer.h.
template<typename T> static Buffer<T> Halide::Buffer< T >::make_interleaved (T * data, int width, int height, int channels, const std::string & name = "") inline static
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 257 of file Buffer.h.
template<typename T> static Buffer<Internal::add_const_if_T_is_const<T, void> > Halide::Buffer< T >::make_interleaved (Type t, T * data, int width, int height, int channels, const std::string & name = "") inline static
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 263 of file Buffer.h.
template<typename T> template<typename T2 > static Buffer<T> Halide::Buffer< T >::make_with_shape_of (Buffer< T2 > src, void *(*)(size_t) allocate_fn = nullptr, void(*)(void *) deallocate_fn = nullptr, const std::string & name = "") inline static
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 270 of file Buffer.h.
template<typename T> template<typename T2 > static Buffer<T> Halide::Buffer< T >::make_with_shape_of (const Runtime::Buffer< T2 > & src, void *(*)(size_t) allocate_fn = nullptr, void(*)(void *) deallocate_fn = nullptr, const std::string & name = "") inline static
Constructors that match Runtime::Buffer with two differences: 1) They take a Type instead of a halide_type_t 2) There is an optional last string argument that gives the buffer a specific name.
Definition at line 279 of file Buffer.h.
template<typename T> void Halide::Buffer< T >::set_name (const std::string & n) inline
Buffers are optionally named.
Definition at line 290 of file Buffer.h.
template<typename T> const std::string& Halide::Buffer< T >::name () const inline
Buffers are optionally named.
Definition at line 294 of file Buffer.h.
Referenced by Halide::Internal::Call::make(), and Halide::Derivative::operator()().
template<typename T> template<typename T2 > bool Halide::Buffer< T >::same_as (const Buffer< T2 > & other) inline
Check if two Buffer objects point to the same underlying Buffer.
Definition at line 301 of file Buffer.h.
template<typename T> bool Halide::Buffer< T >::defined () const inline
Check if this Buffer refers to an existing Buffer.
Default-constructed Buffer objects do not refer to any existing Buffer.
Definition at line 308 of file Buffer.h.
template<typename T> Runtime::Buffer<T>* Halide::Buffer< T >::get () inline
Get a pointer to the underlying Runtime::Buffer.
Definition at line 314 of file Buffer.h.
Referenced by Halide::Buffer<>::can_convert_from(), Halide::Buffer<>::copy_from(), and Halide::Buffer<>::make_with_shape_of().
template<typename T> const Runtime::Buffer<T>* Halide::Buffer< T >::get () const inline
Get a pointer to the underlying Runtime::Buffer.
Definition at line 318 of file Buffer.h.
template<typename T> template<typename Fn , typename... Args> void Halide::Buffer< T >::for_each_value (Fn && f, Args... other_buffers) inline
Does the same thing as the equivalent Halide::Runtime::Buffer method.
Definition at line 416 of file Buffer.h.
template<typename T> static halide_type_t Halide::Buffer< T >::static_halide_type () inline static
Does the same thing as the equivalent Halide::Runtime::Buffer method.
Definition at line 422 of file Buffer.h.
template<typename T> template<typename T2 > static bool Halide::Buffer< T >::can_convert_from (const Buffer< T2 > & other) inline static
Does the same thing as the equivalent Halide::Runtime::Buffer method.
Definition at line 427 of file Buffer.h.
template<typename T> Type Halide::Buffer< T >::type () const inline
Does the same thing as the equivalent Halide::Runtime::Buffer method.
Definition at line 435 of file Buffer.h.
Referenced by Halide::Internal::Call::make(), and Halide::Internal::GeneratorOutput_Buffer< T >::operator=().
template<typename T> template<typename T2 > Buffer<T2> Halide::Buffer< T >::as () const inline
Does the same thing as the equivalent Halide::Runtime::Buffer method.
Definition at line 440 of file Buffer.h.
template<typename T> Buffer<T> Halide::Buffer< T >::copy () const inline
Does the same thing as the equivalent Halide::Runtime::Buffer method.
Definition at line 444 of file Buffer.h.
template<typename T> template<typename T2 > void Halide::Buffer< T >::copy_from (const Buffer< T2 > & other) inline
Does the same thing as the equivalent Halide::Runtime::Buffer method.
Definition at line 449 of file Buffer.h.
template<typename T> template<typename... Args> auto Halide::Buffer< T >::operator() (int first, Args &&... args) -> decltype(std::declval<Runtime::Buffer<T>>()(first, std::forward<Args>(args)...)) inline
Does the same thing as the equivalent Halide::Runtime::Buffer method.
Definition at line 454 of file Buffer.h.
template<typename T> template<typename... Args> auto Halide::Buffer< T >::operator() (int first, Args &&... args) const -> decltype(std::declval<const Runtime::Buffer<T>>()(first, std::forward<Args>(args)...)) inline
Does the same thing as the equivalent Halide::Runtime::Buffer method.
Definition at line 460 of file Buffer.h.
template<typename T> auto Halide::Buffer< T >::operator() (const int * pos) -> decltype(std::declval<Runtime::Buffer<T>>()(pos)) inline
Does the same thing as the equivalent Halide::Runtime::Buffer method.
Definition at line 465 of file Buffer.h.
template<typename T> auto Halide::Buffer< T >::operator() (const int * pos) const -> decltype(std::declval<const Runtime::Buffer<T>>()(pos)) inline
Does the same thing as the equivalent Halide::Runtime::Buffer method.
Definition at line 470 of file Buffer.h.
template<typename T> auto Halide::Buffer< T >::operator() () -> decltype(std::declval<Runtime::Buffer<T>>()()) inline
Does the same thing as the equivalent Halide::Runtime::Buffer method.
Definition at line 475 of file Buffer.h.
template<typename T> auto Halide::Buffer< T >::operator() () const -> decltype(std::declval<const Runtime::Buffer<T>>()()) inline
Does the same thing as the equivalent Halide::Runtime::Buffer method.
Definition at line 480 of file Buffer.h.
template<typename T> template<typename... Args> Expr Halide::Buffer< T >::operator() (Expr first, Args... rest) const inline
Make an Expr that loads from this concrete buffer at a computed coordinate.
Definition at line 489 of file Buffer.h.
template<typename T> template<typename... Args> Expr Halide::Buffer< T >::operator() (const std::vector< Expr > & args) const inline
Make an Expr that loads from this concrete buffer at a computed coordinate.
Definition at line 495 of file Buffer.h.
template<typename T> int Halide::Buffer< T >::copy_to_device (const Target & t = get_jit_target_from_environment()) inline
Copy to the GPU, using the device API that is the default for the given Target.
Definition at line 501 of file Buffer.h.
template<typename T> int Halide::Buffer< T >::copy_to_device (const DeviceAPI & d, const Target & t = get_jit_target_from_environment()) inline
Copy to the GPU, using the given device API.
Definition at line 506 of file Buffer.h.
template<typename T> int Halide::Buffer< T >::device_malloc (const Target & t = get_jit_target_from_environment()) inline
Allocate on the GPU, using the device API that is the default for the given Target.
Definition at line 511 of file Buffer.h.
template<typename T> int Halide::Buffer< T >::device_malloc (const DeviceAPI & d, const Target & t = get_jit_target_from_environment()) inline
Allocate storage on the GPU, using the given device API.
Definition at line 516 of file Buffer.h.
template<typename T> int Halide::Buffer< T >::device_wrap_native (const DeviceAPI & d, uint64_t handle, const Target & t = get_jit_target_from_environment()) inline
Wrap a native handle, using the given device API.
It is a bad idea to pass DeviceAPI::Default_GPU to this routine as the handle argument must match the API that the default resolves to and it is clearer and more reliable to pass the resolved DeviceAPI explicitly.
Definition at line 525 of file Buffer.h.
Member Data Documentation
template<typename T> constexpr bool Halide::Buffer< T >::has_static_halide_type = Runtime::Buffer<T>::has_static_halide_type static
Does the same thing as the equivalent Halide::Runtime::Buffer method.
Definition at line 420 of file Buffer.h.
The documentation for this class was generated from the following file:
Buffer.h