Halide: Halide::Runtime::Internal Namespace Reference
Halide::Runtime::Internal Namespace Reference
Namespaces
Cuda
Metal
Qurt
Synchronization
Classes
struct CacheEntry
struct CpuFeatures
struct device_copy
struct HashMap
struct ScopedMutexLock
struct ScopedSpinLock
struct THashMap
struct work
struct work_queue_t
Typedefs
typedef void(* copy_value_func) (uint8_t *dst, const uint8_t *src, size_t size)
typedef void(* destroy_value_func) (uint8_t *value, size_t size)
Enumerations
Functions
WEAK CpuFeatures halide_get_cpu_features ()
WEAK void copy_memory_helper (const device_copy &copy, int d, int64_t src_off, int64_t dst_off)
WEAK void copy_memory (const device_copy &copy, void *user_context)
WEAK device_copy make_buffer_copy (const halide_buffer_t *src, bool src_host, const halide_buffer_t *dst, bool dst_host)
WEAK device_copy make_host_to_device_copy (const halide_buffer_t *buf)
WEAK device_copy make_device_to_host_copy (const halide_buffer_t *buf)
__attribute__ ((always_inline)) int64_t calc_device_crop_byte_offset(const struct halide_buffer_t *src
for (int i=0;i< src->dimensions;i++)
bool keys_equal (const uint8_t *key1, const uint8_t *key2, size_t key_size)
uint32_t djb_hash (const uint8_t *key, size_t key_size)
WEAK objc_id create_autorelease_pool ()
WEAK void drain_autorelease_pool (objc_id pool)
WEAK void retain_ns_object (objc_id obj)
WEAK void release_ns_object (objc_id obj)
WEAK objc_id wrap_string_as_ns_string (const char *string, size_t length)
size_t strlen (const char *string)
WEAK void ns_log_utf8_string (const char *string)
WEAK void ns_log_object (objc_id obj)
WEAK void halide_use_jit_module ()
WEAK void halide_release_jit_module ()
void halide_thread_yield ()
WEAK int clamp_num_threads (int desired_num_threads)
WEAK int default_desired_num_threads ()
WEAK void worker_thread_already_locked (work *owned_job)
WEAK void worker_thread (void *)
Variables
struct halide_buffer_t * dst
offset *return offset = src->type.bytes()
int slice_dim
int int slice_pos
T & b
a = b
WEAK work_queue_t work_queue = {}
WEAK halide_do_task_t custom_do_task = halide_default_do_task
WEAK halide_do_par_for_t custom_do_par_for = halide_default_do_par_for
Typedef Documentation
typedef void(* Halide::Runtime::Internal::copy_value_func) (uint8_t *dst, const uint8_t *src, size_t size)
Definition at line 23 of file hashmap.h.
typedef void(* Halide::Runtime::Internal::destroy_value_func) (uint8_t *value, size_t size)
Definition at line 24 of file hashmap.h.
Enumeration Type Documentation
enum Halide::Runtime::Internal::PrinterType
Enumerator
BasicPrinter
ErrorPrinter
StringStreamPrinter
Definition at line 5 of file printer.h.
Function Documentation
WEAK CpuFeatures Halide::Runtime::Internal::halide_get_cpu_features ()
WEAK void Halide::Runtime::Internal::copy_memory_helper (const device_copy & copy, int d, int64_t src_off, int64_t dst_off)
Definition at line 47 of file device_buffer_utils.h.
References Halide::Runtime::Internal::device_copy::chunk_size, Halide::Runtime::Internal::device_copy::dst, Halide::Runtime::Internal::device_copy::dst_stride_bytes, Halide::Runtime::Internal::device_copy::extent, memcpy(), Halide::Runtime::Internal::device_copy::src, and Halide::Runtime::Internal::device_copy::src_stride_bytes.
Referenced by copy_memory().
WEAK void Halide::Runtime::Internal::copy_memory (const device_copy & copy, void * user_context)
Definition at line 64 of file device_buffer_utils.h.
References copy_memory_helper(), Halide::Runtime::Internal::device_copy::dst, MAX_COPY_DIMS, Halide::Runtime::Internal::device_copy::src, and Halide::Runtime::Internal::device_copy::src_begin.
WEAK device_copy Halide::Runtime::Internal::make_buffer_copy (const halide_buffer_t * src, bool src_host, const halide_buffer_t * dst, bool dst_host)
Definition at line 74 of file device_buffer_utils.h.
References Halide::Runtime::Internal::device_copy::chunk_size, halide_buffer_t::device, halide_buffer_t::dim, halide_buffer_t::dimensions, Halide::Runtime::Internal::device_copy::dst, Halide::Runtime::Internal::device_copy::dst_stride_bytes, Halide::Runtime::Internal::device_copy::extent, halide_dimension_t::extent, halide_buffer_t::host, MAX_COPY_DIMS, halide_dimension_t::min, NULL, Halide::Runtime::Internal::device_copy::src, Halide::Runtime::Internal::device_copy::src_begin, Halide::Runtime::Internal::device_copy::src_stride_bytes, halide_dimension_t::stride, and halide_buffer_t::type.
Referenced by make_device_to_host_copy(), and make_host_to_device_copy().
WEAK device_copy Halide::Runtime::Internal::make_host_to_device_copy (const halide_buffer_t * buf)
Definition at line 161 of file device_buffer_utils.h.
References make_buffer_copy().
WEAK device_copy Halide::Runtime::Internal::make_device_to_host_copy (const halide_buffer_t * buf)
Definition at line 165 of file device_buffer_utils.h.
References __attribute__(), and make_buffer_copy().
WEAK Halide::Runtime::Internal::__attribute__ ((always_inline)) const inline
Definition at line 205 of file runtime_internal.h.
References __attribute__(), halide_thread_yield(), memcpy(), Halide::min(), and WEAK.
Referenced by make_device_to_host_copy().
Halide::Runtime::Internal::for (int i = 0; i < src->dimensions; i++)
Definition at line 173 of file device_buffer_utils.h.
bool Halide::Runtime::Internal::keys_equal (const uint8_t * key1, const uint8_t * key2, size_t key_size) inline
Definition at line 11 of file hashmap.h.
References memcmp().
Referenced by Halide::Runtime::Internal::HashMap::lookup(), and Halide::Runtime::Internal::HashMap::store().
uint32_t Halide::Runtime::Internal::djb_hash (const uint8_t * key, size_t key_size) inline
Definition at line 15 of file hashmap.h.
Referenced by Halide::Runtime::Internal::HashMap::lookup(), and Halide::Runtime::Internal::HashMap::store().
WEAK objc_id Halide::Runtime::Internal::create_autorelease_pool ()
Definition at line 16 of file objc_support.h.
References objc_getClass(), objc_msgSend(), and sel_getUid().
WEAK void Halide::Runtime::Internal::drain_autorelease_pool (objc_id pool)
Definition at line 23 of file objc_support.h.
References objc_msgSend(), and sel_getUid().
WEAK void Halide::Runtime::Internal::retain_ns_object (objc_id obj)
Definition at line 27 of file objc_support.h.
References objc_msgSend(), and sel_getUid().
WEAK void Halide::Runtime::Internal::release_ns_object (objc_id obj)
Definition at line 31 of file objc_support.h.
References objc_msgSend(), and sel_getUid().
Referenced by ns_log_object(), and ns_log_utf8_string().
WEAK objc_id Halide::Runtime::Internal::wrap_string_as_ns_string (const char * string, size_t length)
Definition at line 35 of file objc_support.h.
References objc_getClass(), objc_msgSend(), sel_getUid(), and strlen().
Referenced by ns_log_object(), and ns_log_utf8_string().
size_t Halide::Runtime::Internal::strlen (const char * string)
Referenced by ns_log_utf8_string(), and wrap_string_as_ns_string().
WEAK void Halide::Runtime::Internal::ns_log_utf8_string (const char * string)
Definition at line 45 of file objc_support.h.
References NSLog(), release_ns_object(), strlen(), and wrap_string_as_ns_string().
WEAK void Halide::Runtime::Internal::ns_log_object (objc_id obj)
Definition at line 53 of file objc_support.h.
References NSLog(), release_ns_object(), and wrap_string_as_ns_string().
WEAK void Halide::Runtime::Internal::halide_use_jit_module ()
WEAK void Halide::Runtime::Internal::halide_release_jit_module ()
void Halide::Runtime::Internal::halide_thread_yield ()
Referenced by __attribute__(), and Halide::Runtime::Internal::Synchronization::word_lock::__attribute__().
WEAK int Halide::Runtime::Internal::clamp_num_threads (int desired_num_threads)
Definition at line 86 of file thread_pool_common.h.
Referenced by halide_default_do_par_for(), and halide_set_num_threads().
WEAK int Halide::Runtime::Internal::default_desired_num_threads ()
Definition at line 95 of file thread_pool_common.h.
References atoi(), getenv(), and halide_host_cpu_count().
Referenced by halide_default_do_par_for(), and halide_set_num_threads().
WEAK void Halide::Runtime::Internal::worker_thread_already_locked (work * owned_job)
Definition at line 110 of file thread_pool_common.h.
References Halide::Runtime::Internal::work::active_workers, Halide::Runtime::Internal::work::closure, Halide::Runtime::Internal::work::exit_status, Halide::Runtime::Internal::work::f, halide_cond_broadcast(), halide_cond_wait(), halide_do_task(), halide_mutex_lock(), halide_mutex_unlock(), Halide::Runtime::Internal::work::max, Halide::Runtime::Internal::work::next, Halide::Runtime::Internal::work::next_job, NULL, Halide::Runtime::Internal::work::running(), and Halide::Runtime::Internal::work::user_context.
Referenced by halide_default_do_par_for(), and worker_thread().
WEAK void Halide::Runtime::Internal::worker_thread (void *)
Definition at line 176 of file thread_pool_common.h.
References halide_mutex_lock(), halide_mutex_unlock(), NULL, and worker_thread_already_locked().
Referenced by halide_default_do_par_for().
Variable Documentation
struct halide_buffer_t* Halide::Runtime::Internal::dst
Initial value:
{
    int64_t offset = 0
Definition at line 171 of file device_buffer_utils.h.
Referenced by Halide::Runtime::Internal::THashMap< KeyType, ValueType >::copy_value_func().
offset *return Halide::Runtime::Internal::offset = src->type.bytes()
Definition at line 176 of file device_buffer_utils.h.
Referenced by Halide::Internal::Elf::Symbol::define(), Halide::Internal::Elf::Symbol::get_offset(), Halide::Internal::Elf::Relocation::get_offset(), Halide::Runtime::Buffer< T, D >::make_with_shape_of(), Halide::Stage::prefetch(), Halide::Func::prefetch(), Halide::Stage::reorder(), Halide::Func::reorder(), and Halide::Internal::Elf::Relocation::set_offset().
int Halide::Runtime::Internal::slice_dim
Definition at line 183 of file device_buffer_utils.h.
int int Halide::Runtime::Internal::slice_pos
Initial value:
{
    int64_t offset = (slice_pos - src->dim[slice_dim].min) * src->dim[slice_dim].stride
Definition at line 183 of file device_buffer_utils.h.
const T & Halide::Runtime::Internal::b
Initial value:
{
    T t = a
Definition at line 188 of file runtime_internal.h.
Referenced by Halide::cast(), Halide::Internal::TemporaryFile::detach(), Halide::Realization::device_sync(), Halide::Internal::div_imp(), Halide::Internal::div_imp< double >(), Halide::Internal::div_imp< float >(), Halide::Internal::ExprWithCompareCache::ExprWithCompareCache(), Halide::Internal::CodeGen_LLVM::get_allocation_name(), Halide::Internal::IRCompareCache::insert(), Halide::Internal::make_const(), Halide::max(), Halide::min(), Halide::Internal::mod_imp(), Halide::Internal::mod_imp< double >(), Halide::Internal::mod_imp< float >(), Halide::operator!=(), Halide::operator%(), Halide::operator&&(), Halide::operator*(), Halide::operator+(), Halide::operator-(), Halide::operator/(), Halide::operator<(), Halide::operator<=(), Halide::operator==(), Halide::operator>(), Halide::operator>=(), Halide::operator||(), Halide::Runtime::Buffer< T, D >::owns_host_memory(), Halide::Internal::Interval::same_as(), Halide::Internal::Parameter::set_scalar(), and Halide::Tuple::Tuple().
Halide::Runtime::Internal::a = b
Definition at line 190 of file runtime_internal.h.
Referenced by HalideIntrospectionCanary::A::A(), Halide::abs(), Halide::cast(), Halide::Internal::TemporaryFile::detach(), Halide::Internal::ExprWithCompareCache::ExprWithCompareCache(), Halide::Internal::CodeGen_LLVM::get_allocation_name(), Halide::Internal::IRCompareCache::insert(), Halide::Internal::make_const(), Halide::max(), Halide::min(), Halide::operator&&(), Halide::operator*=(), Halide::operator+=(), Halide::operator-=(), Halide::operator/=(), Halide::operator||(), Halide::Realization::Realization(), Halide::Pipeline::RealizationArg::RealizationArg(), Halide::Internal::Interval::same_as(), and Halide::Tuple::Tuple().
WEAK work_queue_t Halide::Runtime::Internal::work_queue = {}
Definition at line 84 of file thread_pool_common.h.
Referenced by halide_default_do_par_for(), halide_set_num_threads(), and halide_shutdown_thread_pool().
WEAK halide_do_task_t Halide::Runtime::Internal::custom_do_task = halide_default_do_task
Definition at line 182 of file thread_pool_common.h.
Referenced by Halide::Func::Func(), halide_do_task(), and halide_set_custom_do_task().
WEAK halide_do_par_for_t Halide::Runtime::Internal::custom_do_par_for = halide_default_do_par_for
Definition at line 183 of file thread_pool_common.h.
Referenced by Halide::Func::Func(), halide_do_par_for(), and halide_set_custom_do_par_for().