Halide: Halide::Internal Namespace Reference
Halide::Internal Namespace Reference
Namespaces
Elf
GeneratorMinMax
IntegerDivision
Introspection
Classes
struct Add
The sum of two expressions.
struct all_are_convertible
struct all_ints_and_optional_name
struct all_ints_and_optional_name< First, Rest... >
struct all_ints_and_optional_name< T >
struct all_ints_and_optional_name<>
struct Allocate
Allocate a scratch area called with the given name, type, and size.
struct And
Logical and - are both expressions true.
struct ApplySplitResult
struct AssertStmt
If the 'condition' is false, then evaluate and return the message, which should be a call to an error function.
struct AssociativeOp
Represent the equivalent associative op of an update definition.
struct AssociativePattern
Represent an associative op with its identity.
struct BaseExprNode
A base class for expression nodes.
struct BaseStmtNode
IR nodes are split into expressions and statements.
struct Block
A sequence of statements to be executed in-order.
struct Bound
struct Box
Represents the bounds of a region of arbitrary dimension.
struct Broadcast
A vector with 'lanes' elements, in which every element is 'value'.
struct BufferBuilder
A builder to help create Exprs representing halide_buffer_t structs (e.g.
struct BufferContents
struct BufferInfo
Find all calls to image buffers in the function.
struct Call
A function call.
struct Cast
The actual IR nodes begin here.
class Closure
A helper class to manage closures.
class CodeGen_ARM
A code generator that emits ARM code from a given Halide stmt.
class CodeGen_C
This class emits C++ code equivalent to a halide Stmt.
class CodeGen_D3D12Compute_Dev
class CodeGen_GLSL
Compile one statement into GLSL.
class CodeGen_GLSLBase
This class handles GLSL arithmetic, shared by CodeGen_GLSL and CodeGen_OpenGLCompute_C.
struct CodeGen_GPU_Dev
A code generator that emits GPU code from a given Halide stmt.
class CodeGen_GPU_Host
A code generator that emits GPU code from a given Halide stmt.
class CodeGen_Hexagon
A code generator that emits Hexagon code from a given Halide stmt.
class CodeGen_LLVM
A code generator abstract base class.
class CodeGen_Metal_Dev
class CodeGen_MIPS
A code generator that emits mips code from a given Halide stmt.
class CodeGen_OpenCL_Dev
class CodeGen_OpenGL_Dev
class CodeGen_OpenGLCompute_Dev
class CodeGen_Posix
A code generator that emits posix code from a given Halide stmt.
class CodeGen_PowerPC
A code generator that emits mips code from a given Halide stmt.
class CodeGen_PTX_Dev
A code generator that emits GPU code from a given Halide stmt.
class CodeGen_PyTorch
class CodeGen_X86
A code generator that emits x86 code from a given Halide stmt.
struct cond
struct Convert
struct Cost
class debug
For optional debugging during codegen, use the debug class as follows:
class Definition
A Function definition which can either represent a init or an update definition.
struct DeviceArgument
A DeviceArgument looks similar to an Halide::Argument, but has behavioral differences that make it specific to the GPU pipeline; the fact that neither is-a nor has-a Halide::Argument is deliberate.
struct Dim
class Dimension
struct Div
The ratio of two expressions.
struct EQ
Is the first expression equal to the second.
struct ErrorReport
struct Evaluate
Evaluate and discard an expression, presumably because it has some side-effect.
struct ExprNode
We use the "curiously recurring template pattern" to avoid duplicated code in the IR Nodes.
class ExprUsesVars
struct ExprWithCompareCache
A wrapper about Exprs so that they can be deeply compared with a cache for known-equal subexpressions.
struct FileStat
class FindAllCalls
Visitor for keeping track of functions that are directly called and the arguments with which they are called.
struct FloatImm
Floating point constants.
struct For
A for loop.
struct Free
Free the resources associated with the given buffer.
class FuncSchedule
A schedule for a Function of a Halide pipeline.
class Function
A reference-counted handle to Halide's internal representation of a function.
struct FunctionPtr
A possibly-weak pointer to a Halide function.
struct FusedPair
This represents two stages with fused loop nests from outermost to a specific loop level.
struct GE
Is the first expression greater than or equal to the second.
class GeneratorBase
class GeneratorInput_Arithmetic
class GeneratorInput_Buffer
class GeneratorInput_Func
class GeneratorInput_Scalar
class GeneratorInputBase
class GeneratorInputImpl
class GeneratorOutput_Arithmetic
class GeneratorOutput_Buffer
class GeneratorOutput_Func
class GeneratorOutputBase
class GeneratorOutputImpl
class GeneratorParam_Arithmetic
class GeneratorParam_Bool
class GeneratorParam_Enum
class GeneratorParam_LoopLevel
class GeneratorParam_MachineParams
class GeneratorParam_Synthetic
class GeneratorParam_Target
class GeneratorParam_Type
class GeneratorParamBase
class GeneratorParamImpl
class GeneratorRegistry
class GeneratorStub
class GIOBase
GIOBase is the base class for all GeneratorInput<> and GeneratorOutput<> instantiations; it is not part of the public API and should never be used directly by user code.
struct GT
Is the first expression greater than the second.
struct has_static_halide_type_method
struct has_static_halide_type_method< T2, typename type_sink< decltype(T2::static_halide_type())>::type >
class HexagonAlignmentAnalyzer
class HostClosure
A Closure modified to inspect GPU-specific memory accesses, and produce a vector of DeviceArgument objects.
struct IfThenElse
An if-then-else block.
struct InferredArgument
An inferred argument.
struct integer_sequence
struct Interval
A class to represent ranges of Exprs.
struct IntImm
Integer constants.
struct IntrusivePtr
Intrusive shared pointers have a reference count (a RefCount object) stored in the class itself.
class IRCompareCache
Lossily track known equal exprs with a cache.
struct IRDeepCompare
A compare struct suitable for use in std::map and std::set that computes a lexical ordering on IR nodes.
class IRGraphMutator2
A mutator that caches and reapplies previously-done mutations, so that it can handle graphs of IR that have not had CSE done to them.
class IRGraphVisitor
A base class for algorithms that walk recursively over the IR without visiting the same node twice.
struct IRHandle
IR nodes are passed around opaque handles to them.
class IRMutator
Deprecated for new use: please use IRMutator2 instead.
class IRMutator2
A base class for passes over the IR which modify it (e.g.
struct IRNode
The abstract base classes for a node in the Halide IR.
class IRPrinter
An IRVisitor that emits IR to the given output stream in a human readable form.
class IRVisitor
A base class for algorithms that need to recursively walk over the IR.
struct IsRoundtrippable
struct JITHandlers
struct JITModule
class JITSharedRuntime
struct JITUserContext
struct LE
Is the first expression less than or equal to the second.
struct Let
A let expression, like you might find in a functional language.
struct LetStmt
The statement form of a let node.
struct Load
Load a value from a named symbol if predicate is true.
struct LoweredArgument
Definition of an argument to a LoweredFunc.
struct LoweredFunc
Definition of a lowered function.
struct LT
Is the first expression less than the second.
struct make_integer_sequence_helper
struct make_integer_sequence_helper< T, N, N >
struct Max
The greater of two values.
struct meta_and
struct meta_and< T1, Args... >
struct meta_or
struct meta_or< T1, Args... >
struct Min
The lesser of two values.
struct Mod
The remainder of a / b.
struct ModulusRemainder
The result of modulus_remainder analysis.
struct Mul
The product of two expressions.
struct NE
Is the first expression not equal to the second.
struct next_integer_sequence
struct next_integer_sequence< integer_sequence< T, Ints... > >
struct NoRealizations
struct NoRealizations< T, Args... >
struct NoRealizations<>
struct Not
Logical not - true if the expression false.
class ObjectInstanceRegistry
struct Or
Logical or - is at least one of the expression true.
class Parameter
A reference-counted handle to a parameter to a halide pipeline.
struct Prefetch
Represent a multi-dimensional region of a Func or an ImageParam that needs to be prefetched.
struct PrefetchDirective
struct ProducerConsumer
This node is a helpful annotation to do with permissions.
struct Provide
This defines the value of a function at a multi-dimensional location.
class PythonExtensionGen
struct Ramp
A linear ramp vector node.
struct Range
A single-dimensional span.
struct Realize
Allocate a multi-dimensional buffer of the given type and size.
class ReductionDomain
A reference-counted handle on a reduction domain, which is just a vector of ReductionVariable.
struct ReductionVariable
A single named dimension of a reduction domain.
struct ReductionVariableInfo
Return a list of reduction variables the expression or tuple depends on.
class RefCount
A class representing a reference count to be used with IntrusivePtr.
struct RegionCosts
Auto scheduling component which is used to assign costs for computing a region of a function or one of its stages.
class RegisteredParameter
A Subclass of Parameter which registers itself in the ObjectInstanceRegistry; this is provided for backwards compatibility with legacy Generator code that uses ImageParam/Param instead of Input.
class RegisterGenerator
class ScheduleParamBase
class Scope
A common pattern when traversing Halide IR is that you need to keep track of stuff when you find a Let or a LetStmt, and that it should hide previous values with the same name until you leave the Let or LetStmt nodes This class helps with that.
struct ScopedBinding
Helper class for pushing/popping Scope<> values, to allow for early-exit in Visitor/Mutators that preserves correctness.
struct ScopedBinding< void >
struct ScopedValue
Helper class for saving/restoring variable values on the stack, to allow for early-exit that preserves correctness.
struct Select
A ternary operator.
struct select_type
struct select_type< First >
struct Shuffle
Construct a new vector by taking elements from another sequence of vectors.
class SmallStack
A stack which can store one item very efficiently.
class SmallStack< void >
struct SolverResult
struct Specialization
struct Split
class StageSchedule
A schedule for a single stage of a Halide pipeline.
struct StaticCast
struct Stmt
A reference-counted handle to a statement node.
struct StmtNode
struct StorageDim
struct Store
Store a 'value' to the buffer called 'name' at a given 'index' if 'predicate' is true.
struct StringImm
String constants.
struct StringOrLoopLevel
class StubInput
class StubInputBuffer
StubInputBuffer is the placeholder that a Stub uses when it requires a Buffer for an input (rather than merely a Func or Expr).
class StubOutputBuffer
StubOutputBuffer is the placeholder that a Stub uses when it requires a Buffer for an output (rather than merely a Func).
class StubOutputBufferBase
struct Sub
The difference of two expressions.
class TemporaryFile
A simple utility class that creates a temporary file in its ctor and deletes that file in its dtor; this is useful for temporary files that you want to ensure are deleted when exiting a certain scope.
class ThreadPool
struct type_sink
struct UIntImm
Unsigned integer constants.
class ValueTracker
ValueTracker is an internal utility class that attempts to track and flag certain obvious Stub-related errors at Halide compile time: it tracks the constraints set on any Parameter-based argument (i.e., Input<Buffer> and Output<Buffer>) to ensure that incompatible values aren't set.
struct Variable
A named variable.
class Voidifier
Typedefs
typedef std::map< std::string, Interval > DimBounds
typedef std::map< std::pair< std::string, int >, Interval > FuncValueBounds
template<typename T , typename T2 >
using add_const_if_T_is_const = typename std::conditional< std::is_const< T >::value, const T2, T2 >::type
using FuncBounds = std::vector< std::pair< Expr, Expr >>
template<typename T >
using GeneratorParamImplBase = typename select_type< cond< std::is_same< T, Target >::value, GeneratorParam_Target< T >>, cond< std::is_same< T, MachineParams >::value, GeneratorParam_MachineParams< T >>, cond< std::is_same< T, LoopLevel >::value, GeneratorParam_LoopLevel >, cond< std::is_same< T, Type >::value, GeneratorParam_Type< T >>, cond< std::is_same< T, bool >::value, GeneratorParam_Bool< T >>, cond< std::is_arithmetic< T >::value, GeneratorParam_Arithmetic< T >>, cond< std::is_enum< T >::value, GeneratorParam_Enum< T >> >::type
template<typename T , typename TBase = typename std::remove_all_extents<T>::type>
using GeneratorInputImplBase = typename select_type< cond< has_static_halide_type_method< TBase >::value, GeneratorInput_Buffer< T >>, cond< std::is_same< TBase, Func >::value, GeneratorInput_Func< T >>, cond< std::is_arithmetic< TBase >::value, GeneratorInput_Arithmetic< T >>, cond< std::is_scalar< TBase >::value, GeneratorInput_Scalar< T >> >::type
template<typename T , typename TBase = typename std::remove_all_extents<T>::type>
using GeneratorOutputImplBase = typename select_type< cond< has_static_halide_type_method< TBase >::value, GeneratorOutput_Buffer< T >>, cond< std::is_same< TBase, Func >::value, GeneratorOutput_Func< T >>, cond< std::is_arithmetic< TBase >::value, GeneratorOutput_Arithmetic< T >> >::type
using GeneratorFactory = std::function< std::unique_ptr< GeneratorBase >(const GeneratorContext &)>
using GeneratorParamsMap = std::map< std::string, StringOrLoopLevel >
typedef std::vector< Range > Region
A multi-dimensional box.
typedef int(* halide_task) (void *user_context, int, uint8_t *)
typedef llvm::raw_pwrite_stream LLVMOStream
template<typename T , T N>
using make_integer_sequence = typename make_integer_sequence_helper< T, 0, N >::type
template<size_t... Ints>
using index_sequence = integer_sequence< size_t, Ints... >
template<size_t N>
using make_index_sequence = make_integer_sequence< size_t, N >
Enumerations
Functions
Stmt add_image_checks (Stmt s, const std::vector< Function > &outputs, const Target &t, const std::vector< std::string > &order, const std::map< std::string, Function > &env, const FuncValueBounds &fb)
Insert checks to make sure a statement doesn't read out of bounds on inputs or outputs, and that the inputs and outputs conform to the format required (e.g.
Stmt add_parameter_checks (Stmt s, const Target &t)
Insert checks to make sure that all referenced parameters meet their constraints.
Stmt align_loads (Stmt s, int alignment, const Scope< ModulusRemainder > &alignment_info)
Attempt to rewrite unaligned loads from buffers which are known to be aligned to instead load aligned vectors that cover the original load, and then slice the original load out of the aligned vectors.
Stmt allocation_bounds_inference (Stmt s, const std::map< std::string, Function > &env, const std::map< std::pair< std::string, int >, Interval > &func_bounds)
Take a partially statement with Realize nodes in terms of variables, and define values for those variables.
std::vector< ApplySplitResult > apply_split (const Split &split, bool is_update, std::string prefix, std::map< std::string, Expr > &dim_extent_alignment)
Given a Split schedule on a definition (init or update), return a list of of predicates on the definition, substitutions that needs to be applied to the definition (in ascending order of application), and let stmts which defined the values of variables referred by the predicates and substitutions (ordered from innermost to outermost let).
std::vector< std::pair< std::string, Expr > > compute_loop_bounds_after_split (const Split &split, std::string prefix)
Compute the loop bounds of the new dimensions resulting from applying the split schedules using the loop bounds of the old dimensions.
const std::vector< AssociativePattern > & get_ops_table (const std::vector< Expr > &exprs)
AssociativeOp prove_associativity (const std::string &f, std::vector< Expr > args, std::vector< Expr > exprs)
Given an update definition of a Func 'f', determine its equivalent associative binary/unary operator if there is any.
void associativity_test ()
bool inline_all_trivial_functions (const std::vector< Function > &outputs, const std::vector< std::string > &order, const std::map< std::string, Function > &env)
If the cost of computing a Func is about the same as calling the Func, inline the Func.
bool inline_all_element_wise_functions (const std::vector< Function > &outputs, const std::vector< std::string > &order, const std::map< std::string, Function > &env)
Inline a Func if its values are only consumed by another single Func in element-wise manner.
void check_estimates_on_outputs (const std::vector< Function > &outputs)
Check if all the pipeline outputs have estimates specified on each of their dimensions; otherwise, throw an assertion.
std::string generate_schedules (const std::vector< Function > &outputs, const Target &target, const MachineParams &arch_params)
Generate schedules for Funcs within a pipeline.
int string_to_int (const std::string &s)
Return an int representation of 's'.
Expr get_extent (const Interval &i)
Return the size of an interval.
Expr box_size (const Box &b)
Return the size of an n-d box.
void disp_regions (const std::map< std::string, Box > &regions)
Helper function to print the bounds of a region.
Definition get_stage_definition (const Function &f, int stage_num)
Return the corresponding definition of a function given the stage.
std::vector< Dim > & get_stage_dims (const Function &f, int stage_num)
Return the corresponding loop dimensions of a function given the stage.
void combine_load_costs (std::map< std::string, Expr > &result, const std::map< std::string, Expr > &partial)
Add partial load costs to the corresponding function in the result costs.
DimBounds get_stage_bounds (Function f, int stage_num, const DimBounds &pure_bounds)
Return the required bounds of an intermediate stage (f, stage_num) of function 'f' given the bounds of the pure dimensions.
std::vector< DimBounds > get_stage_bounds (Function f, const DimBounds &pure_bounds)
Return the required bounds for all the stages of the function 'f'.
Expr perform_inline (Expr e, const std::map< std::string, Function > &env, const std::set< std::string > &inlines=std::set< std::string >())
Recursively inline all the functions in the set 'inlines' into the expression 'e' and return the resulting expression.
std::set< std::string > get_parents (Function f, int stage)
Return all functions that are directly called by a function stage (f, stage).
void propagate_estimate_test ()
Interval bounds_of_expr_in_scope (Expr expr, const Scope< Interval > &scope, const FuncValueBounds &func_bounds=FuncValueBounds(), bool const_bound=false)
Given an expression in some variables, and a map from those variables to their bounds (in the form of (minimum possible value, maximum possible value)), compute two expressions that give the minimum possible value and the maximum possible value of this expression.
Expr find_constant_bound (const Expr &e, Direction d, const Scope< Interval > &scope=Scope< Interval >())
Interval find_constant_bounds (const Expr &e, const Scope< Interval > &scope)
Find bounds for a varying expression that are either constants or +/-inf.
void merge_boxes (Box &a, const Box &b)
Expand box a to encompass box b.
bool boxes_overlap (const Box &a, const Box &b)
Test if box a could possibly overlap box b.
Box box_union (const Box &a, const Box &b)
The union of two boxes.
Box box_intersection (const Box &a, const Box &b)
The intersection of two boxes.
bool box_contains (const Box &a, const Box &b)
Test if box a provably contains box b.
FuncValueBounds compute_function_value_bounds (const std::vector< std::string > &order, const std::map< std::string, Function > &env)
Compute the maximum and minimum possible value for each function in an environment.
void bounds_test ()
Stmt bounds_inference (Stmt, const std::vector< Function > &outputs, const std::vector< std::string > &realization_order, const std::vector< std::vector< std::string >> &fused_groups, const std::map< std::string, Function > &environment, const std::map< std::pair< std::string, int >, Interval > &func_bounds, const Target &target)
Take a partially lowered statement that includes symbolic representations of the bounds over which things should be realized, and inject expressions defining those bounds.
Stmt bound_small_allocations (const Stmt &s)
Expr buffer_accessor (const Buffer<> &buf, const std::vector< Expr > &args)
template<typename T , typename = typename std::enable_if<!std::is_convertible<T, std::string>::value>::type>
std::string get_name_from_end_of_parameter_pack (T &&)
std::string get_name_from_end_of_parameter_pack (const std::string &n)
std::string get_name_from_end_of_parameter_pack ()
template<typename First , typename Second , typename... Args>
std::string get_name_from_end_of_parameter_pack (First first, Second second, Args &&...rest)
void get_shape_from_start_of_parameter_pack_helper (std::vector< int > &, const std::string &)
void get_shape_from_start_of_parameter_pack_helper (std::vector< int > &)
template<typename... Args>
void get_shape_from_start_of_parameter_pack_helper (std::vector< int > &result, int x, Args &&...rest)
template<typename... Args>
std::vector< int > get_shape_from_start_of_parameter_pack (Args &&...args)
Stmt canonicalize_gpu_vars (Stmt s)
Canonicalize GPU var names into some pre-determined block/thread names (i.e.
llvm::StructType * build_closure_type (const Closure &closure, llvm::StructType *buffer_t, llvm::LLVMContext *context)
The llvm type of a struct containing all of the externally referenced state of a Closure.
void pack_closure (llvm::StructType *type, llvm::Value *dst, const Closure &closure, const Scope< llvm::Value * > &src, llvm::StructType *buffer_t, llvm::IRBuilder< llvm::ConstantFolder, llvm::IRBuilderDefaultInserter > *builder)
Emit code that builds a struct containing all the externally referenced state.
void unpack_closure (const Closure &closure, Scope< llvm::Value * > &dst, llvm::StructType *type, llvm::Value *src, llvm::IRBuilder< llvm::ConstantFolder, llvm::IRBuilderDefaultInserter > *builder)
Emit code that unpacks a struct containing all the externally referenced state into a symbol table.
llvm::Type * llvm_type_of (llvm::LLVMContext *context, Halide::Type t)
Get the llvm type equivalent to a given halide type.
bool function_takes_user_context (const std::string &name)
Which built-in functions require a user-context first argument?
bool can_allocation_fit_on_stack (int64_t size)
Given a size (in bytes), return True if the allocation size can fit on the stack; otherwise, return False.
Stmt unpredicate_loads_stores (Stmt s)
Replace predicated loads/stores with unpredicated equivalents inside branches.
void get_target_options (const llvm::Module &module, llvm::TargetOptions &options, std::string &mcpu, std::string &mattrs)
Given an llvm::Module, set llvm:TargetOptions, cpu and attr information.
void clone_target_options (const llvm::Module &from, llvm::Module &to)
Given two llvm::Modules, clone target options from one to the other.
std::unique_ptr< llvm::TargetMachine > make_target_machine (const llvm::Module &module)
Given an llvm::Module, get or create an llvm:TargetMachine.
void set_function_attributes_for_target (llvm::Function *, Target)
Set the appropriate llvm Function attributes given a Target.
std::string cplusplus_function_mangled_name (const std::string &name, const std::vector< std::string > &namespaces, Type return_type, const std::vector< ExternFuncArgument > &args, const Target &target)
Return the mangled C++ name for a function.
void cplusplus_mangle_test ()
Expr common_subexpression_elimination (const Expr &, bool lift_all=false)
Replace each common sub-expression in the argument with a variable, and wrap the resulting expr in a let statement giving a value to that variable.
Stmt common_subexpression_elimination (const Stmt &, bool lift_all=false)
Do common-subexpression-elimination on each expression in a statement.
void cse_test ()
std::ostream & operator<< (std::ostream &stream, const Stmt &)
Emit a halide statement on an output stream (such as std::cout) in a human-readable form.
std::ostream & operator<< (std::ostream &stream, const LoweredFunc &)
Emit a halide LoweredFunc in a human readable format.
void debug_arguments (LoweredFunc *func)
Injects debug prints in a LoweredFunc that describe the arguments.
Stmt debug_to_file (Stmt s, const std::vector< Function > &outputs, const std::map< std::string, Function > &env)
Takes a statement with Realize nodes still unlowered.
Expr extract_odd_lanes (Expr a)
Extract the odd-numbered lanes in a vector.
Expr extract_even_lanes (Expr a)
Extract the even-numbered lanes in a vector.
Expr extract_lane (Expr vec, int lane)
Extract the nth lane of a vector.
Stmt rewrite_interleavings (Stmt s)
Look through a statement for expressions of the form select(ramp % 2 == 0, a, b) and replace them with calls to an interleave intrinsic.
void deinterleave_vector_test ()
void derivative_test ()
bool has_variable (const Expr &expr, const std::string &name)
Return true if expr depends on the variable.
bool has_let_defined (const Expr &expr, const std::string &name)
Return true if expr has a Let operation defining the variable.
Expr remove_let_definitions (const Expr &expr)
Remove all let definitions of expr.
std::vector< std::string > gather_variables (const Expr &expr, const std::vector< std::string > &filter)
Return a list of variables that expr depends on and are in the filter.
std::vector< std::string > gather_variables (const Expr &expr, const std::vector< Var > &filter)
std::map< std::string, ReductionVariableInfo > gather_rvariables (Expr expr)
std::map< std::string, ReductionVariableInfo > gather_rvariables (Tuple tuple)
Expr add_let_expression (const Expr &expr, const std::map< std::string, Expr > &let_var_mapping, const std::vector< std::string > &let_variables)
Add necessary let expressions to expr.
std::vector< Expr > sort_expressions (const Expr &expr)
Topologically sort the expression graph expressed by expr.
std::map< std::string, Box > inference_bounds (const std::vector< Func > &funcs, const std::vector< FuncBounds > &output_bounds)
Compute the bounds of funcs.
std::map< std::string, Box > inference_bounds (const Func &func, const FuncBounds &output_bounds)
std::vector< std::pair< Expr, Expr > > box_to_vector (const Box &bounds)
Convert Box to vector of (min, extent)
bool equal (const RDom &bounds0, const RDom &bounds1)
Return true if bounds0 and bounds1 represent the same bounds.
std::vector< std::string > vars_to_strings (const std::vector< Var > &vars)
Return a list of variable names.
ReductionDomain extract_rdom (const Expr &expr)
Return the reduction domain used by expr.
std::pair< bool, Expr > solve_inverse (Expr expr, const std::string &new_var, const std::string &var)
expr is new_var == f(var), solve for var == g(new_var) if multiple new_var correponds to same var, introduce a RDom
std::map< std::string, BufferInfo > find_buffer_calls (const Func &func)
std::set< std::string > find_implicit_variables (Expr expr)
Find all implicit variables in expr.
Expr substitute_rdom_predicate (const std::string &name, const Expr &replacement, const Expr &expr)
Substitute the variable.
bool is_calling_function (const std::string &func_name, const Expr &expr, const std::map< std::string, Expr > &let_var_mapping)
Return true if expr contains call to func_name.
bool is_calling_function (const Expr &expr, const std::map< std::string, Expr > &let_var_mapping)
Return true if expr depends on any function or buffer.
Expr make_device_interface_call (DeviceAPI device_api)
Get an Expr which evaluates to the device interface for the given device api at runtime.
Stmt inject_early_frees (Stmt s)
Take a statement with allocations and inject markers (of the form of calls to "mark buffer dead") after the last use of each allocation.
Type eliminated_bool_type (Type bool_type, Type other_type)
If a type is a boolean vector, find the type that it has been changed to by eliminate_bool_vectors.
template<>
RefCount & ref_count< IRNode > (const IRNode *t)
template<>
void destroy< IRNode > (const IRNode *t)
template<typename StmtOrExpr , typename T >
bool stmt_or_expr_uses_vars (StmtOrExpr e, const Scope< T > &v, const Scope< Expr > &s=Scope< Expr >::empty_scope())
Test if a statement or expression references any of the variables in a scope, additionally considering variables bound to Expr's in the scope provided in the final argument.
template<typename StmtOrExpr >
bool stmt_or_expr_uses_var (StmtOrExpr e, const std::string &v, const Scope< Expr > &s=Scope< Expr >::empty_scope())
Test if a statement or expression references the given variable, additionally considering variables bound to Expr's in the scope provided in the final argument.
bool expr_uses_var (Expr e, const std::string &v, const Scope< Expr > &s=Scope< Expr >::empty_scope())
Test if an expression references the given variable, additionally considering variables bound to Expr's in the scope provided in the final argument.
bool stmt_uses_var (Stmt stmt, const std::string &v, const Scope< Expr > &s=Scope< Expr >::empty_scope())
Test if a statement references the given variable, additionally considering variables bound to Expr's in the scope provided in the final argument.
template<typename T >
bool expr_uses_vars (Expr e, const Scope< T > &v, const Scope< Expr > &s=Scope< Expr >::empty_scope())
Test if an expression references any of the variables in a scope, additionally considering variables bound to Expr's in the scope provided in the final argument.
template<typename T >
bool stmt_uses_vars (Stmt stmt, const Scope< T > &v, const Scope< Expr > &s=Scope< Expr >::empty_scope())
Test if a statement references any of the variables in a scope, additionally considering variables bound to Expr's in the scope provided in the final argument.
std::map< std::string, Function > find_direct_calls (Function f)
Construct a map from name to Function definition object for all Halide functions called directly in the definition of the Function f, including in update definitions, update index expressions, and RDom extents.
std::map< std::string, Function > find_transitive_calls (Function f)
Construct a map from name to Function definition object for all Halide functions called directly in the definition of the Function f, or indirectly in those functions' definitions, recursively.
void populate_environment (Function f, std::map< std::string, Function > &env)
Find all Functions transitively referenced by f in any way and add them to the given map.
template<typename Last >
void check_types (const Tuple &t, int idx)
template<typename First , typename Second , typename... Rest>
void check_types (const Tuple &t, int idx)
template<typename Last >
void assign_results (Realization &r, int idx, Last last)
template<typename First , typename Second , typename... Rest>
void assign_results (Realization &r, int idx, First first, Second second, Rest &&...rest)
void schedule_scalar (Func f)
std::pair< std::vector< Function >, std::map< std::string, Function > > deep_copy (const std::vector< Function > &outputs, const std::map< std::string, Function > &env)
Deep copy an entire Function DAG.
Stmt zero_gpu_loop_mins (Stmt s)
Rewrite all GPU loops to have a min of zero.
Stmt fuse_gpu_thread_loops (Stmt s)
Converts Halide's GPGPU IR to the OpenCL/CUDA/Metal model.
Stmt fuzz_float_stores (Stmt s)
On every store of a floating point value, mask off the least-significant-bit of the mantissa.
void generator_test ()
std::vector< Expr > parameter_constraints (const Parameter &p)
template<typename T >
HALIDE_NO_USER_CODE_INLINE std::string enum_to_string (const std::map< std::string, T > &enum_map, const T &t)
template<typename T >
T enum_from_string (const std::map< std::string, T > &enum_map, const std::string &s)
const std::map< std::string, Halide::Type > & get_halide_type_enum_map ()
std::string halide_type_to_enum_string (const Type &t)
std::string halide_type_to_c_source (const Type &t)
std::string halide_type_to_c_type (const Type &t)
int generate_filter_main (int argc, char **argv, std::ostream &cerr)
generate_filter_main() is a convenient wrapper for GeneratorRegistry::create() + compile_to_files(); it can be trivially wrapped by a "real" main() to produce a command-line utility for ahead-of-time filter compilation.
template<typename T >
T parse_scalar (const std::string &value)
std::vector< Type > parse_halide_type_list (const std::string &types)
Stmt inject_hexagon_rpc (Stmt s, const Target &host_target, Module &module)
Pull loops marked with the Hexagon device API to a separate module, and call them through the Hexagon host runtime module.
Buffer< uint8_t > compile_module_to_hexagon_shared_object (const Module &device_code)
Stmt optimize_hexagon_shuffles (Stmt s, int lut_alignment)
Replace indirect and other loads with simple loads + vlut calls.
Stmt vtmpy_generator (Stmt s)
Generate vtmpy instruction if possible.
Stmt optimize_hexagon_instructions (Stmt s, Target t, Scope< ModulusRemainder > &alignment_info)
Hexagon deinterleaves when performing widening operations, and interleaves when performing narrowing operations.
std::vector< InferredArgument > infer_arguments (Stmt body, const std::vector< Function > &outputs)
Stmt call_extern_and_assert (const std::string &name, const std::vector< Expr > &args)
A helper function to call an extern function, and assert that it returns 0.
Stmt inject_host_dev_buffer_copies (Stmt s, const Target &t)
Inject calls to halide_device_malloc, halide_copy_to_device, and halide_copy_to_host as needed.
Stmt inject_opengl_intrinsics (Stmt s)
Take a statement with for kernel for loops and turn loads and stores inside the loops into OpenGL texture load and store intrinsics.
void validate_schedule_inlined_function (Function f)
Check if the schedule of an inlined function is legal, throwing an error if it is not.
void interval_test ()
void ir_equality_test ()
bool expr_match (Expr pattern, Expr expr, std::vector< Expr > &result)
Does the first expression have the same structure as the second? Variables in the first expression with the name * are interpreted as wildcards, and their matching equivalent in the second expression is placed in the vector give as the third argument.
bool expr_match (Expr pattern, Expr expr, std::map< std::string, Expr > &result)
Does the first expression have the same structure as the second? Variables are matched consistently.
void expr_match_test ()
bool is_const (const Expr &e)
Is the expression either an IntImm, a FloatImm, a StringImm, or a Cast of the same, or a Ramp or Broadcast of the same.
bool is_const (const Expr &e, int64_t v)
Is the expression an IntImm, FloatImm of a particular value, or a Cast, or Broadcast of the same.
const int64_t * as_const_int (const Expr &e)
If an expression is an IntImm or a Broadcast of an IntImm, return a pointer to its value.
const uint64_t * as_const_uint (const Expr &e)
If an expression is a UIntImm or a Broadcast of a UIntImm, return a pointer to its value.
const double * as_const_float (const Expr &e)
If an expression is a FloatImm or a Broadcast of a FloatImm, return a pointer to its value.
bool is_const_power_of_two_integer (const Expr &e, int *bits)
Is the expression a constant integer power of two.
bool is_positive_const (const Expr &e)
Is the expression a const (as defined by is_const), and also strictly greater than zero (in all lanes, if a vector expression)
bool is_negative_const (const Expr &e)
Is the expression a const (as defined by is_const), and also strictly less than zero (in all lanes, if a vector expression)
bool is_negative_negatable_const (const Expr &e)
Is the expression a const (as defined by is_const), and also strictly less than zero (in all lanes, if a vector expression) and is its negative value representable.
bool is_undef (const Expr &e)
Is the expression an undef.
bool is_zero (const Expr &e)
Is the expression a const (as defined by is_const), and also equal to zero (in all lanes, if a vector expression)
bool is_one (const Expr &e)
Is the expression a const (as defined by is_const), and also equal to one (in all lanes, if a vector expression)
bool is_two (const Expr &e)
Is the expression a const (as defined by is_const), and also equal to two (in all lanes, if a vector expression)
bool is_no_op (const Stmt &s)
Is the statement a no-op (which we represent as either an undefined Stmt, or as an Evaluate node of a constant)
bool is_pure (const Expr &e)
Does the expression 1) Take on the same value no matter where it appears in a Stmt, and 2) Evaluating it has no side-effects.
void check_representable (Type t, int64_t val)
Check if a constant value can be correctly represented as the given type.
Expr make_bool (bool val, int lanes=1)
Construct a boolean constant from a C++ boolean value.
Expr make_zero (Type t)
Construct the representation of zero in the given type.
Expr make_one (Type t)
Construct the representation of one in the given type.
Expr make_two (Type t)
Construct the representation of two in the given type.
Expr const_true (int lanes=1)
Construct the constant boolean true.
Expr const_false (int lanes=1)
Construct the constant boolean false.
Expr lossless_cast (Type t, Expr e)
Attempt to cast an expression to a smaller type while provably not losing information.
void match_types (Expr &a, Expr &b)
Coerce the two expressions to have the same type, using C-style casting rules.
Expr raise_to_integer_power (Expr a, int64_t b)
Raise an expression to an integer power by repeatedly multiplying it by itself.
void split_into_ands (const Expr &cond, std::vector< Expr > &result)
Split a boolean condition into vector of ANDs.
Expr strided_ramp_base (Expr e, int stride=1)
If e is a ramp expression with stride, default 1, return the base, otherwise undefined.
HALIDE_NO_USER_CODE_INLINE void collect_print_args (std::vector< Expr > &args)
template<typename... Args>
HALIDE_NO_USER_CODE_INLINE void collect_print_args (std::vector< Expr > &args, const char *arg, Args &&...more_args)
template<typename... Args>
HALIDE_NO_USER_CODE_INLINE void collect_print_args (std::vector< Expr > &args, Expr arg, Args &&...more_args)
Expr memoize_tag_helper (Expr result, const std::vector< Expr > &cache_key_values)
std::ostream & operator<< (std::ostream &stream, const AssociativePattern &)
Emit a halide associative pattern on an output stream (such as std::cout) in a human-readable form.
std::ostream & operator<< (std::ostream &stream, const AssociativeOp &)
Emit a halide associative op on an output stream (such as std::cout) in a human-readable form.
std::ostream & operator<< (std::ostream &stream, const ForType &)
Emit a halide for loop type (vectorized, serial, etc) in a human readable form.
std::ostream & operator<< (std::ostream &stream, const NameMangling &)
Emit a halide name mangling value in a human readable format.
std::ostream & operator<< (std::ostream &stream, const LinkageType &)
Emit a halide linkage value in a human readable format.
Expr lower_lerp (Expr zero_val, Expr one_val, Expr weight)
Build Halide IR that computes a lerp.
Stmt loop_invariant_code_motion (Stmt)
Hoist loop-invariants out of inner loops.
template<typename T >
auto iterator_to_pointer (T iter) -> decltype(&*std::declval< T >())
llvm::Triple get_triple_for_target (const Target &target)
Return the llvm::Triple that corresponds to the given Halide Target.
std::unique_ptr< llvm::Module > get_initial_module_for_target (Target, llvm::LLVMContext *, bool for_shared_jit_runtime=false, bool just_gpu=false)
Create an llvm module containing the support code for a given target.
std::unique_ptr< llvm::Module > get_initial_module_for_ptx_device (Target, llvm::LLVMContext *c)
Create an llvm module containing the support code for ptx device.
void add_bitcode_to_module (llvm::LLVMContext *context, llvm::Module &module, const std::vector< uint8_t > &bitcode, const std::string &name)
Link a block of llvm bitcode into an llvm module.
Stmt loop_carry (Stmt, int max_carried_values=8)
Reuse loads done on previous loop iterations by stashing them in induction variables instead of redoing the load.
Module lower (const std::vector< Function > &output_funcs, const std::string &pipeline_name, const Target &t, const std::vector< Argument > &args, const LinkageType linkage_type, const std::vector< IRMutator2 * > &custom_passes=std::vector< IRMutator2 * >())
Given a vector of scheduled halide functions, create a Module that evaluates it.
Stmt lower_main_stmt (const std::vector< Function > &output_funcs, const std::string &pipeline_name, const Target &t, const std::vector< IRMutator2 * > &custom_passes=std::vector< IRMutator2 * >())
Given a halide function with a schedule, create a statement that evaluates it.
void lower_test ()
Stmt lower_warp_shuffles (Stmt s)
Rewrite access to things stored outside the loop over GPU lanes to use nvidia's warp shuffle instructions.
llvm::Function * define_matlab_wrapper (llvm::Module *module, llvm::Function *pipeline_argv_wrapper, llvm::Function *metadata_getter)
Add a mexFunction wrapper definition to the module, calling the function with the name pipeline_name.
Stmt inject_memoization (Stmt s, const std::map< std::string, Function > &env, const std::string &name, const std::vector< Function > &outputs)
Transform pipeline calls for Funcs scheduled with memoize to do a lookup call to the runtime cache implementation, and if there is a miss, compute the results and call the runtime to store it back to the cache.
Stmt rewrite_memoized_allocations (Stmt s, const std::map< std::string, Function > &env)
This should be called after Storage Flattening has added Allocation IR nodes.
ModulusRemainder modulus_remainder (Expr e)
For things like alignment analysis, often it's helpful to know if an integer expression is some multiple of a constant plus some other constant.
ModulusRemainder modulus_remainder (Expr e, const Scope< ModulusRemainder > &scope)
If we have alignment information about external variables, we can let the analysis know about that using this version of modulus_remainder:
void modulus_remainder_test ()
int64_t gcd (int64_t, int64_t)
The greatest common divisor of two integers.
int64_t lcm (int64_t, int64_t)
The least common multiple of two integers.
Monotonic is_monotonic (Expr e, const std::string &var)
void is_monotonic_test ()
bool can_parallelize_rvar (const std::string &rvar, const std::string &func, const Definition &r)
Returns whether or not Halide can prove that it is safe to parallelize an update definition across a specific variable.
void check_call_arg_types (const std::string &name, std::vector< Expr > *args, int dims)
Validate arguments to a call to a func, image or imageparam.
bool has_likely_tag (Expr e)
Return true if an expression uses a likely tag.
Stmt partition_loops (Stmt s)
Partitions loop bodies into a prologue, a steady state, and an epilogue.
Stmt inject_placeholder_prefetch (Stmt s, const std::map< std::string, Function > &env, const std::string &prefix, const std::vector< PrefetchDirective > &prefetches)
Inject placeholder prefetches to 's'.
Stmt inject_prefetch (Stmt s, const std::map< std::string, Function > &env)
Compute the actual region to be prefetched and place it to the placholder prefetch.
Stmt reduce_prefetch_dimension (Stmt stmt, const Target &t)
Reduce a multi-dimensional prefetch into a prefetch of lower dimension (max dimension of the prefetch is specified by target architecture).
std::string print_loop_nest (const std::vector< Function > &output_funcs)
Emit some simple pseudocode that shows the structure of the loop nest specified by this pipeline's schedule, and the schedules of the functions it uses.
Stmt inject_profiling (Stmt, std::string)
Take a statement representing a halide pipeline insert high-resolution timing into the generated code (via spawning a thread that acts as a sampling profiler); summaries of execution times and counts will be logged at the end.
Expr qualify (const std::string &prefix, Expr value)
Prefix all variable names in the given expression with the prefix string.
Expr random_float (const std::vector< Expr > &)
Return a random floating-point number between zero and one that varies deterministically based on the input expressions.
Expr random_int (const std::vector< Expr > &)
Return a random unsigned integer between zero and 2^32-1 that varies deterministically based on the input expressions (which must be integers or unsigned integers).
Expr lower_random (Expr e, const std::vector< std::string > &free_vars, int tag)
Convert calls to random() to IR generated by random_float and random_int.
std::pair< std::vector< std::string >, std::vector< std::vector< std::string > > > realization_order (const std::vector< Function > &outputs, std::map< std::string, Function > &env)
Given a bunch of functions that call each other, determine an order in which to do the scheduling.
std::vector< std::string > topological_order (const std::vector< Function > &outputs, const std::map< std::string, Function > &env)
Given a bunch of functions that call each other, determine a topological order which stays constant regardless of the schedule.
void split_predicate_test ()
bool is_func_trivial_to_inline (const Function &func)
Return true if the cost of inlining a function is equivalent to the cost of calling the function directly.
Stmt remove_dead_allocations (Stmt s)
Find Allocate/Free pairs that are never loaded from or stored to, and remove them from the Stmt.
Stmt remove_trivial_for_loops (Stmt s)
Convert for loops of size 1 into LetStmt nodes, which allows for further simplification.
Stmt remove_undef (Stmt s)
Removes stores that depend on undef values, and statements that only contain such stores.
Stmt schedule_functions (const std::vector< Function > &outputs, const std::vector< std::vector< std::string >> &fused_groups, const std::map< std::string, Function > &env, const Target &target, bool &any_memoized)
Build loop nests and inject Function realizations at the appropriate places using the schedule.
template<typename T >
std::ostream & operator<< (std::ostream &stream, const Scope< T > &s)
Stmt select_gpu_api (Stmt s, Target t)
Replace for loops with GPU_Default device_api with an actual device API depending on what's enabled in the target.
void simple_autoschedule_test ()
bool can_prove (Expr e)
A common use of the simplifier is to prove boolean expressions are true at compile time.
Stmt simplify_exprs (Stmt)
Simplify expressions found in a statement, but don't simplify across different statements.
template<>
float mod_imp< float > (float a, float b)
template<>
double mod_imp< double > (double a, double b)
template<>
float div_imp< float > (float a, float b)
template<>
double div_imp< double > (double a, double b)
void simplify_specializations (std::map< std::string, Function > &env)
Try to simplify the RHS/LHS of a function's definition based on its specializations.
Stmt skip_stages (Stmt s, const std::vector< std::string > &order)
Avoid computing certain stages if we can infer a runtime condition to check that tells us they won't be used.
Stmt sliding_window (Stmt s, const std::map< std::string, Function > &env)
Perform sliding window optimizations on a halide statement.
SolverResult solve_expression (Expr e, const std::string &variable, const Scope< Expr > &scope=Scope< Expr >::empty_scope())
Attempts to collect all instances of a variable in an expression tree and place it as far to the left as possible, and as far up the tree as possible (i.e.
Interval solve_for_outer_interval (Expr c, const std::string &variable)
Find the smallest interval such that the condition is either true or false inside of it, but definitely false outside of it.
Interval solve_for_inner_interval (Expr c, const std::string &variable)
Find the largest interval such that the condition is definitely true inside of it, and might be true or false outside of it.
Expr and_condition_over_domain (Expr c, const Scope< Interval > &varying)
Take a conditional that includes variables that vary over some domain, and convert it to a more conservative (less frequently true) condition that doesn't depend on those variables.
void solve_test ()
Stmt split_tuples (Stmt s, const std::map< std::string, Function > &env)
Rewrite all tuple-valued Realizations, Provide nodes, and Call nodes into several scalar-valued ones, so that later lowering passes only need to think about scalar-valued productions.
void print_to_html (std::string filename, Stmt s)
Dump an HTML-formatted print of a Stmt to filename.
void print_to_html (std::string filename, const Module &m)
Dump an HTML-formatted print of a Module to filename.
Stmt storage_flattening (Stmt s, const std::vector< Function > &outputs, const std::map< std::string, Function > &env, const Target &target)
Take a statement with multi-dimensional Realize, Provide, and Call nodes, and turn it into a statement with single-dimensional Allocate, Store, and Load nodes respectively.
Stmt storage_folding (Stmt s, const std::map< std::string, Function > &env)
Fold storage of functions if possible.
bool strictify_float (std::map< std::string, Function > &env, const Target &t)
Propagate strict_float intrinisics such that they immediately wrap all floating-point expressions.
Expr substitute (const std::string &name, const Expr &replacement, const Expr &expr)
Substitute variables with the given name with the replacement expression within expr.
Stmt substitute (const std::string &name, const Expr &replacement, const Stmt &stmt)
Substitute variables with the given name with the replacement expression within stmt.
void target_test ()
Stmt inject_tracing (Stmt, const std::string &pipeline_name, const std::map< std::string, Function > &env, const std::vector< Function > &outputs, const Target &Target)
Take a statement representing a halide pipeline, inject calls to tracing functions at interesting points, such as allocations.
Stmt trim_no_ops (Stmt s)
Truncate loop bounds to the region over which they actually do something.
Stmt unify_duplicate_lets (Stmt s)
Find let statements that all define the same value, and make later ones just reuse the symbol names of the earlier ones.
Stmt uniquify_variable_names (Stmt s)
Modify a statement so that every internally-defined variable name is unique.
Stmt unpack_buffers (Stmt s)
Creates let stmts for the various buffer components (e.g.
Stmt unroll_loops (Stmt)
Take a statement with for loops marked for unrolling, and convert each into several copies of the innermost statement.
Stmt lower_unsafe_promises (Stmt s, const Target &t)
Lower all unsafe promises into either assertions or unchecked code, depending on the target.
template<typename DST , typename SRC , typename std::enable_if< std::is_floating_point< SRC >::value >::type * = nullptr>
DST safe_numeric_cast (SRC s)
Some numeric conversions are UB if the value won't fit in the result; safe_numeric_cast<>() is meant as a drop-in replacement for a C/C++ cast that adds well-defined behavior for the UB cases, attempting to mimic common implementation behavior as much as possible.
template<typename DstType , typename SrcType >
DstType reinterpret_bits (const SrcType &src)
An aggressive form of reinterpret cast used for correct type-punning.
std::string make_entity_name (void *stack_ptr, const std::string &type, char prefix)
Make a unique name for an object based on the name of the stack variable passed in.
std::string get_env_variable (char const *env_var_name)
Get value of an environment variable.
std::string running_program_name ()
Get the name of the currently running executable.
bool starts_with (const std::string &str, const std::string &prefix)
Test if the first string starts with the second string.
bool ends_with (const std::string &str, const std::string &suffix)
Test if the first string ends with the second string.
std::string replace_all (const std::string &str, const std::string &find, const std::string &replace)
Replace all matches of the second string in the first string with the last string.
std::vector< std::string > split_string (const std::string &source, const std::string &delim)
Split the source string using 'delim' as the divider.
template<typename T , typename Fn >
T fold_left (const std::vector< T > &vec, Fn f)
Perform a left fold of a vector.
template<typename T , typename Fn >
T fold_right (const std::vector< T > &vec, Fn f)
Returns a right fold of a vector.
template<typename T1 , typename T2 , typename T3 , typename T4 >
HALIDE_NO_USER_CODE_INLINE void collect_paired_args (std::vector< std::pair< T1, T2 >> &collected_args, const T3 &a1, const T4 &a2)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename... Args>
HALIDE_NO_USER_CODE_INLINE void collect_paired_args (std::vector< std::pair< T1, T2 >> &collected_args, const T3 &a1, const T4 &a2, Args &&...args)
std::string extract_namespaces (const std::string &name, std::vector< std::string > &namespaces)
Returns base name and fills in namespaces, outermost one first in vector.
std::string file_make_temp (const std::string &prefix, const std::string &suffix)
Create a unique file with a name of the form prefixXXXXXsuffix in an arbitrary (but writable) directory; this is typically /tmp, but the specific location is not guaranteed.
std::string dir_make_temp ()
Create a unique directory in an arbitrary (but writable) directory; this is typically somewhere inside /tmp, but the specific location is not guaranteed.
bool file_exists (const std::string &name)
Wrapper for access().
void assert_file_exists (const std::string &name)
assert-fail if the file doesn't exist.
void assert_no_file_exists (const std::string &name)
assert-fail if the file DOES exist.
void file_unlink (const std::string &name)
Wrapper for unlink().
void ensure_no_file_exists (const std::string &name)
Ensure that no file with this path exists.
void dir_rmdir (const std::string &name)
Wrapper for rmdir().
FileStat file_stat (const std::string &name)
Wrapper for stat().
void halide_tic_impl (const char *file, int line)
void halide_toc_impl (const char *file, int line)
std::vector< Var > make_argument_list (int dimensionality)
Make a list of unique arguments for definitions with unnamed arguments.
Stmt find_linear_expressions (Stmt s)
find_linear_expressions(Stmt s) identifies expressions that may be moved out of the generated fragment shader into a varying attribute.
Stmt setup_gpu_vertex_buffer (Stmt s)
Compute a set of 2D mesh coordinates based on the behavior of varying attribute expressions contained within a GLSL scheduled for loop.
Stmt vectorize_loops (Stmt s, const Target &t)
Take a statement with for loops marked for vectorization, and turn them into single statements that operate on vectors.
std::map< std::string, Function > wrap_func_calls (const std::map< std::string, Function > &env)
Replace every call to wrapped Functions in the Functions' definitions with call to their wrapper functions.
void wrap_legacy_extern_stages (Module m)
Add wrappers for any LoweredFuncs that need them to support backwards compatibility.
void add_legacy_wrapper (Module m, const LoweredFunc &fn)
Add a wrapper for a LoweredFunc that accepts old buffers and upgrades them.
Expr subsitute_var_estimates (Expr e)
Substitute every variable in an Expr or a Stmt with its estimate if specified.
Stmt subsitute_var_estimates (Stmt s)
Substitute every variable in an Expr or a Stmt with its estimate if specified.
template<typename K , typename V >
V get_element (const std::map< K, V > &m, const K &key)
Return value of element within a map.
template<typename K , typename V >
V & get_element (std::map< K, V > &m, const K &key)
Return value of element within a map.
std::map< std::string, Box > boxes_required (Expr e, const Scope< Interval > &scope=Scope< Interval >::empty_scope(), const FuncValueBounds &func_bounds=FuncValueBounds())
Compute rectangular domains large enough to cover all the 'Call's to each function that occurs within a given statement or expression.
std::map< std::string, Box > boxes_required (Stmt s, const Scope< Interval > &scope=Scope< Interval >::empty_scope(), const FuncValueBounds &func_bounds=FuncValueBounds())
Compute rectangular domains large enough to cover all the 'Call's to each function that occurs within a given statement or expression.
std::map< std::string, Box > boxes_provided (Expr e, const Scope< Interval > &scope=Scope< Interval >::empty_scope(), const FuncValueBounds &func_bounds=FuncValueBounds())
Compute rectangular domains large enough to cover all the 'Provides's to each function that occurs within a given statement or expression.
std::map< std::string, Box > boxes_provided (Stmt s, const Scope< Interval > &scope=Scope< Interval >::empty_scope(), const FuncValueBounds &func_bounds=FuncValueBounds())
Compute rectangular domains large enough to cover all the 'Provides's to each function that occurs within a given statement or expression.
std::map< std::string, Box > boxes_touched (Expr e, const Scope< Interval > &scope=Scope< Interval >::empty_scope(), const FuncValueBounds &func_bounds=FuncValueBounds())
Compute rectangular domains large enough to cover all the 'Call's and 'Provides's to each function that occurs within a given statement or expression.
std::map< std::string, Box > boxes_touched (Stmt s, const Scope< Interval > &scope=Scope< Interval >::empty_scope(), const FuncValueBounds &func_bounds=FuncValueBounds())
Compute rectangular domains large enough to cover all the 'Call's and 'Provides's to each function that occurs within a given statement or expression.
Box box_required (Expr e, std::string fn, const Scope< Interval > &scope=Scope< Interval >::empty_scope(), const FuncValueBounds &func_bounds=FuncValueBounds())
Variants of the above that are only concerned with a single function.
Box box_required (Stmt s, std::string fn, const Scope< Interval > &scope=Scope< Interval >::empty_scope(), const FuncValueBounds &func_bounds=FuncValueBounds())
Variants of the above that are only concerned with a single function.
Box box_provided (Expr e, std::string fn, const Scope< Interval > &scope=Scope< Interval >::empty_scope(), const FuncValueBounds &func_bounds=FuncValueBounds())
Variants of the above that are only concerned with a single function.
Box box_provided (Stmt s, std::string fn, const Scope< Interval > &scope=Scope< Interval >::empty_scope(), const FuncValueBounds &func_bounds=FuncValueBounds())
Variants of the above that are only concerned with a single function.
Box box_touched (Expr e, std::string fn, const Scope< Interval > &scope=Scope< Interval >::empty_scope(), const FuncValueBounds &func_bounds=FuncValueBounds())
Variants of the above that are only concerned with a single function.
Box box_touched (Stmt s, std::string fn, const Scope< Interval > &scope=Scope< Interval >::empty_scope(), const FuncValueBounds &func_bounds=FuncValueBounds())
Variants of the above that are only concerned with a single function.
Expr lower_euclidean_div (Expr a, Expr b)
Given a Halide Euclidean division/mod operation, define it in terms of div_round_to_zero or mod_round_to_zero.
Expr lower_euclidean_mod (Expr a, Expr b)
Given a Halide Euclidean division/mod operation, define it in terms of div_round_to_zero or mod_round_to_zero.
Stmt eliminate_bool_vectors (Stmt s)
Some targets treat vectors of bools as integers of the same type that the boolean operation is being used to operate on.
Expr eliminate_bool_vectors (Expr s)
Some targets treat vectors of bools as integers of the same type that the boolean operation is being used to operate on.
Expr native_deinterleave (Expr x)
Generate deinterleave or interleave operations, operating on groups of vectors at a time.
Expr native_interleave (Expr x)
Generate deinterleave or interleave operations, operating on groups of vectors at a time.
bool is_native_deinterleave (Expr x)
Generate deinterleave or interleave operations, operating on groups of vectors at a time.
bool is_native_interleave (Expr x)
Generate deinterleave or interleave operations, operating on groups of vectors at a time.
Stmt inline_function (Stmt s, Function f)
Inline a single named function, which must be pure.
Expr inline_function (Expr e, Function f)
Inline a single named function, which must be pure.
void inline_function (Function caller, Function f)
Inline a single named function, which must be pure.
template<typename T >
RefCount & ref_count (const T *t)
Because in this header we don't yet know how client classes store their RefCount (and we don't want to depend on the declarations of the client classes), any class that you want to hold onto via one of these must provide implementations of ref_count and destroy, which we forward-declare here.
template<typename T >
void destroy (const T *t)
Because in this header we don't yet know how client classes store their RefCount (and we don't want to depend on the declarations of the client classes), any class that you want to hold onto via one of these must provide implementations of ref_count and destroy, which we forward-declare here.
bool equal (const Expr &a, const Expr &b)
Compare IR nodes for equality of value.
bool equal (const Stmt &a, const Stmt &b)
Compare IR nodes for equality of value.
bool graph_equal (const Expr &a, const Expr &b)
Compare IR nodes for equality of value.
bool graph_equal (const Stmt &a, const Stmt &b)
Compare IR nodes for equality of value.
Expr make_const (Type t, int64_t val)
Construct an immediate of the given type from any numeric C++ type.
Expr make_const (Type t, uint64_t val)
Construct an immediate of the given type from any numeric C++ type.
Expr make_const (Type t, double val)
Construct an immediate of the given type from any numeric C++ type.
Expr make_const (Type t, int32_t val)
Construct an immediate of the given type from any numeric C++ type.
Expr make_const (Type t, uint32_t val)
Construct an immediate of the given type from any numeric C++ type.
Expr make_const (Type t, int16_t val)
Construct an immediate of the given type from any numeric C++ type.
Expr make_const (Type t, uint16_t val)
Construct an immediate of the given type from any numeric C++ type.
Expr make_const (Type t, int8_t val)
Construct an immediate of the given type from any numeric C++ type.
Expr make_const (Type t, uint8_t val)
Construct an immediate of the given type from any numeric C++ type.
Expr make_const (Type t, bool val)
Construct an immediate of the given type from any numeric C++ type.
Expr make_const (Type t, float val)
Construct an immediate of the given type from any numeric C++ type.
Expr make_const (Type t, float16_t val)
Construct an immediate of the given type from any numeric C++ type.
Expr halide_log (Expr a)
Halide's vectorizable transcendentals.
Expr halide_exp (Expr a)
Halide's vectorizable transcendentals.
Expr halide_erf (Expr a)
Halide's vectorizable transcendentals.
bool reduce_expr_modulo (Expr e, int modulus, int *remainder)
Reduce an expression modulo some integer.
bool reduce_expr_modulo (Expr e, int modulus, int *remainder, const Scope< ModulusRemainder > &scope)
Reduce an expression modulo some integer.
Stmt simplify (Stmt, bool remove_dead_lets=true, const Scope< Interval > &bounds=Scope< Interval >::empty_scope(), const Scope< ModulusRemainder > &alignment=Scope< ModulusRemainder >::empty_scope())
Perform a a wide range of simplifications to expressions and statements, including constant folding, substituting in trivial values, arithmetic rearranging, etc.
Expr simplify (Expr, bool remove_dead_lets=true, const Scope< Interval > &bounds=Scope< Interval >::empty_scope(), const Scope< ModulusRemainder > &alignment=Scope< ModulusRemainder >::empty_scope())
Perform a a wide range of simplifications to expressions and statements, including constant folding, substituting in trivial values, arithmetic rearranging, etc.
template<typename T >
T mod_imp (T a, T b)
Implementations of division and mod that are specific to Halide.
template<typename T >
T div_imp (T a, T b)
Implementations of division and mod that are specific to Halide.
Expr substitute (const std::map< std::string, Expr > &replacements, const Expr &expr)
Substitute variables with names in the map.
Stmt substitute (const std::map< std::string, Expr > &replacements, const Stmt &stmt)
Substitute variables with names in the map.
Expr substitute (const Expr &find, const Expr &replacement, const Expr &expr)
Substitute expressions for other expressions.
Stmt substitute (const Expr &find, const Expr &replacement, const Stmt &stmt)
Substitute expressions for other expressions.
Expr graph_substitute (const std::string &name, const Expr &replacement, const Expr &expr)
Substitutions where the IR may be a general graph (and not just a DAG).
Stmt graph_substitute (const std::string &name, const Expr &replacement, const Stmt &stmt)
Substitutions where the IR may be a general graph (and not just a DAG).
Expr graph_substitute (const Expr &find, const Expr &replacement, const Expr &expr)
Substitutions where the IR may be a general graph (and not just a DAG).
Stmt graph_substitute (const Expr &find, const Expr &replacement, const Stmt &stmt)
Substitutions where the IR may be a general graph (and not just a DAG).
Expr substitute_in_all_lets (const Expr &expr)
Substitute in all let Exprs in a piece of IR.
Stmt substitute_in_all_lets (const Stmt &stmt)
Substitute in all let Exprs in a piece of IR.
std::string unique_name (char prefix)
Generate a unique name starting with the given prefix.
std::string unique_name (const std::string &prefix)
Generate a unique name starting with the given prefix.
bool add_would_overflow (int bits, int64_t a, int64_t b)
Routines to test if math would overflow for signed integers with the given number of bits.
bool sub_would_overflow (int bits, int64_t a, int64_t b)
Routines to test if math would overflow for signed integers with the given number of bits.
bool mul_would_overflow (int bits, int64_t a, int64_t b)
Routines to test if math would overflow for signed integers with the given number of bits.
Variables
const int64_t unknown = std::numeric_limits<int64_t>::min()
Typedef Documentation
typedef std::map<std::string, Interval> Halide::Internal::DimBounds
Definition at line 20 of file AutoScheduleUtils.h.
typedef std::map<std::pair<std::string, int>, Interval> Halide::Internal::FuncValueBounds
Definition at line 16 of file Bounds.h.
template<typename T , typename T2 > using Halide::Internal::add_const_if_T_is_const = typedef typename std::conditional<std::is_const<T>::value, const T2, T2>::type
Definition at line 80 of file Buffer.h.
using Halide::Internal::FuncBounds = typedef std::vector<std::pair<Expr, Expr>>
Definition at line 14 of file DerivativeUtils.h.
template<typename T > using Halide::Internal::GeneratorParamImplBase = typedef typename select_type< cond<std::is_same<T, Target>::value, GeneratorParam_Target<T>>, cond<std::is_same<T, MachineParams>::value, GeneratorParam_MachineParams<T>>, cond<std::is_same<T, LoopLevel>::value, GeneratorParam_LoopLevel>, cond<std::is_same<T, Type>::value, GeneratorParam_Type<T>>, cond<std::is_same<T, bool>::value, GeneratorParam_Bool<T>>, cond<std::is_arithmetic<T>::value, GeneratorParam_Arithmetic<T>>, cond<std::is_enum<T>::value, GeneratorParam_Enum<T>> >::type
Definition at line 855 of file Generator.h.
template<typename T , typename TBase = typename std::remove_all_extents<T>::type> using Halide::Internal::GeneratorInputImplBase = typedef typename select_type< cond<has_static_halide_type_method<TBase>::value, GeneratorInput_Buffer<T>>, cond<std::is_same<TBase, Func>::value, GeneratorInput_Func<T>>, cond<std::is_arithmetic<TBase>::value, GeneratorInput_Arithmetic<T>>, cond<std::is_scalar<TBase>::value, GeneratorInput_Scalar<T>> >::type
Definition at line 1798 of file Generator.h.
template<typename T , typename TBase = typename std::remove_all_extents<T>::type> using Halide::Internal::GeneratorOutputImplBase = typedef typename select_type< cond<has_static_halide_type_method<TBase>::value, GeneratorOutput_Buffer<T>>, cond<std::is_same<TBase, Func>::value, GeneratorOutput_Func<T>>, cond<std::is_arithmetic<TBase>::value, GeneratorOutput_Arithmetic<T>> >::type
Definition at line 2295 of file Generator.h.
using Halide::Internal::GeneratorFactory = typedef std::function<std::unique_ptr<GeneratorBase>(const GeneratorContext&)>
Definition at line 2609 of file Generator.h.
using Halide::Internal::GeneratorParamsMap = typedef std::map<std::string, StringOrLoopLevel>
Definition at line 2620 of file Generator.h.
typedef std::vector<Range> Halide::Internal::Region
A multi-dimensional box.
The outer product of the elements
Definition at line 397 of file IR.h.
typedef int(* Halide::Internal::halide_task) (void *user_context, int, uint8_t *)
Definition at line 123 of file JITModule.h.
typedef llvm::raw_pwrite_stream Halide::Internal::LLVMOStream
Definition at line 27 of file LLVM_Output.h.
template<typename T , T N> using Halide::Internal::make_integer_sequence = typedef typename make_integer_sequence_helper<T, 0, N>::type
Definition at line 354 of file Util.h.
template<size_t... Ints> using Halide::Internal::index_sequence = typedef integer_sequence<size_t, Ints...>
Definition at line 357 of file Util.h.
template<size_t N> using Halide::Internal::make_index_sequence = typedef make_integer_sequence<size_t, N>
Definition at line 360 of file Util.h.
Enumeration Type Documentation
enum Halide::Internal::Direction strong
Given a varying expression, try to find a constant that is either: An upper bound (always greater than or equal to the expression), or A lower bound (always less than or equal to the expression) If it fails, returns an undefined Expr.
Enumerator
Upper
Lower
Definition at line 39 of file Bounds.h.
enum Halide::Internal::IRNodeType strong
All our IR node types get unique IDs for the purposes of RTTI.
Enumerator
IntImm
UIntImm
FloatImm
StringImm
Cast
Variable
Add
Sub
Mul
Div
Mod
Min
Max
EQ
NE
LT
LE
GT
GE
And
Or
Not
Select
Load
Ramp
Broadcast
Call
Let
LetStmt
AssertStmt
ProducerConsumer
For
Store
Provide
Allocate
Free
Realize
Block
IfThenElse
Evaluate
Shuffle
Prefetch
Definition at line 25 of file Expr.h.
enum Halide::Internal::ForType strong
An enum describing a type of loop traversal.
Used in schedules, and in the For loop IR node. Serial is a conventional ordered for loop. Iterations occur in increasing order, and each iteration must appear to have finished before the next begins. Parallel, GPUBlock, and GPUThread are parallel and unordered: iterations may occur in any order, and multiple iterations may occur simultaneously. Vectorized and GPULane are parallel and synchronous: they act as if all iterations occur at the same time in lockstep.
Enumerator
Serial
Parallel
Vectorized
Unrolled
GPUBlock
GPUThread
GPULane
Definition at line 384 of file Expr.h.
enum Halide::Internal::IOKind strong
Enumerator
Scalar
Function
Buffer
Definition at line 1080 of file Generator.h.
enum Halide::Internal::SyntheticParamType strong
Enumerator
Type
Dim
ArraySize
Definition at line 2377 of file Generator.h.
enum Halide::Internal::Monotonic strong
Detect whether an expression is monotonic increasing in a variable, decreasing, or unknown.
Enumerator
Constant
Increasing
Decreasing
Unknown
Definition at line 18 of file Monotonic.h.
Function Documentation
Stmt Halide::Internal::add_image_checks (Stmt s, const std::vector< Function > & outputs, const Target & t, const std::vector< std::string > & order, const std::map< std::string, Function > & env, const FuncValueBounds & fb)
Insert checks to make sure a statement doesn't read out of bounds on inputs or outputs, and that the inputs and outputs conform to the format required (e.g.
stride.0 must be 1).
Stmt Halide::Internal::add_parameter_checks (Stmt s, const Target & t)
Insert checks to make sure that all referenced parameters meet their constraints.
Stmt Halide::Internal::align_loads (Stmt s, int alignment, const Scope< ModulusRemainder > & alignment_info)
Attempt to rewrite unaligned loads from buffers which are known to be aligned to instead load aligned vectors that cover the original load, and then slice the original load out of the aligned vectors.
Stmt Halide::Internal::allocation_bounds_inference (Stmt s, const std::map< std::string, Function > & env, const std::map< std::pair< std::string, int >, Interval > & func_bounds)
Take a partially statement with Realize nodes in terms of variables, and define values for those variables.
std::vector<ApplySplitResult> Halide::Internal::apply_split (const Split & split, bool is_update, std::string prefix, std::map< std::string, Expr > & dim_extent_alignment)
Given a Split schedule on a definition (init or update), return a list of of predicates on the definition, substitutions that needs to be applied to the definition (in ascending order of application), and let stmts which defined the values of variables referred by the predicates and substitutions (ordered from innermost to outermost let).
Referenced by Halide::Internal::ApplySplitResult::is_predicate().
std::vector<std::pair<std::string, Expr> > Halide::Internal::compute_loop_bounds_after_split (const Split & split, std::string prefix)
Compute the loop bounds of the new dimensions resulting from applying the split schedules using the loop bounds of the old dimensions.
Referenced by Halide::Internal::ApplySplitResult::is_predicate().
const std::vector<AssociativePattern>& Halide::Internal::get_ops_table (const std::vector< Expr > & exprs)
Referenced by Halide::Internal::AssociativePattern::commutative().
AssociativeOp Halide::Internal::prove_associativity (const std::string & f, std::vector< Expr > args, std::vector< Expr > exprs)
Given an update definition of a Func 'f', determine its equivalent associative binary/unary operator if there is any.
'is_associative' indicates if the operation was successfuly proven as associative.
Referenced by Halide::Internal::AssociativeOp::size().
void Halide::Internal::associativity_test ()
Referenced by Halide::Internal::AssociativeOp::size().
bool Halide::Internal::inline_all_trivial_functions (const std::vector< Function > & outputs, const std::vector< std::string > & order, const std::map< std::string, Function > & env)
If the cost of computing a Func is about the same as calling the Func, inline the Func.
Return true of any of the Funcs is inlined.
Referenced by Halide::MachineParams::MachineParams().
bool Halide::Internal::inline_all_element_wise_functions (const std::vector< Function > & outputs, const std::vector< std::string > & order, const std::map< std::string, Function > & env)
Inline a Func if its values are only consumed by another single Func in element-wise manner.
Referenced by Halide::MachineParams::MachineParams().
void Halide::Internal::check_estimates_on_outputs (const std::vector< Function > & outputs)
Check if all the pipeline outputs have estimates specified on each of their dimensions; otherwise, throw an assertion.
Referenced by Halide::MachineParams::MachineParams().
std::string Halide::Internal::generate_schedules (const std::vector< Function > & outputs, const Target & target, const MachineParams & arch_params)
Generate schedules for Funcs within a pipeline.
The Funcs should not already have specializations or schedules as the current auto-scheduler does not take into account user-defined schedules or specializations. This applies the schedules and returns a string representation of the schedules. The target architecture is specified by 'target'.
Referenced by Halide::MachineParams::MachineParams().
int Halide::Internal::string_to_int (const std::string & s)
Return an int representation of 's'.
Throw an error on failure.
Expr Halide::Internal::subsitute_var_estimates (Expr e)
Substitute every variable in an Expr or a Stmt with its estimate if specified.
Stmt Halide::Internal::subsitute_var_estimates (Stmt s)
Substitute every variable in an Expr or a Stmt with its estimate if specified.
Expr Halide::Internal::get_extent (const Interval & i)
Return the size of an interval.
Return an undefined expr if the interval is unbounded.
Expr Halide::Internal::box_size (const Box & b)
Return the size of an n-d box.
void Halide::Internal::disp_regions (const std::map< std::string, Box > & regions)
Helper function to print the bounds of a region.
Definition Halide::Internal::get_stage_definition (const Function & f, int stage_num)
Return the corresponding definition of a function given the stage.
This will throw an assertion if the function is an extern function (Extern Func does not have definition).
std::vector<Dim>& Halide::Internal::get_stage_dims (const Function & f, int stage_num)
Return the corresponding loop dimensions of a function given the stage.
For extern Func, this will return a list of size 1 containing the dummy __outermost loop dimension.
void Halide::Internal::combine_load_costs (std::map< std::string, Expr > & result, const std::map< std::string, Expr > & partial)
Add partial load costs to the corresponding function in the result costs.
DimBounds Halide::Internal::get_stage_bounds (Function f, int stage_num, const DimBounds & pure_bounds)
Return the required bounds of an intermediate stage (f, stage_num) of function 'f' given the bounds of the pure dimensions.
std::vector<DimBounds> Halide::Internal::get_stage_bounds (Function f, const DimBounds & pure_bounds)
Return the required bounds for all the stages of the function 'f'.
Each entry in the returned vector corresponds to a stage.
Expr Halide::Internal::perform_inline (Expr e, const std::map< std::string, Function > & env, const std::set< std::string > & inlines = std::set< std::string >())
Recursively inline all the functions in the set 'inlines' into the expression 'e' and return the resulting expression.
std::set<std::string> Halide::Internal::get_parents (Function f, int stage)
Return all functions that are directly called by a function stage (f, stage).
template<typename K , typename V > V Halide::Internal::get_element (const std::map< K, V > & m, const K & key)
Return value of element within a map.
This will assert if the element is not in the map.
Definition at line 98 of file AutoScheduleUtils.h.
References internal_assert.
template<typename K , typename V > V& Halide::Internal::get_element (std::map< K, V > & m, const K & key)
Return value of element within a map.
This will assert if the element is not in the map.
Definition at line 105 of file AutoScheduleUtils.h.
References internal_assert, and propagate_estimate_test().
void Halide::Internal::propagate_estimate_test ()
Referenced by get_element().
Interval Halide::Internal::bounds_of_expr_in_scope (Expr expr, const Scope< Interval > & scope, const FuncValueBounds & func_bounds = FuncValueBounds(), bool const_bound = false)
Given an expression in some variables, and a map from those variables to their bounds (in the form of (minimum possible value, maximum possible value)), compute two expressions that give the minimum possible value and the maximum possible value of this expression.
Max or min may be undefined expressions if the value is not bounded above or below. If the expression is a vector, also takes the bounds across the vector lanes and returns a scalar result.
This is for tasks such as deducing the region of a buffer loaded by a chunk of code.
Expr Halide::Internal::find_constant_bound (const Expr & e, Direction d, const Scope< Interval > & scope = Scope< Interval >())
Interval Halide::Internal::find_constant_bounds (const Expr & e, const Scope< Interval > & scope)
Find bounds for a varying expression that are either constants or +/-inf.
void Halide::Internal::merge_boxes (Box & a, const Box & b)
Expand box a to encompass box b.
bool Halide::Internal::boxes_overlap (const Box & a, const Box & b)
Test if box a could possibly overlap box b.
Box Halide::Internal::box_union (const Box & a, const Box & b)
The union of two boxes.
Box Halide::Internal::box_intersection (const Box & a, const Box & b)
The intersection of two boxes.
bool Halide::Internal::box_contains (const Box & a, const Box & b)
Test if box a provably contains box b.
std::map<std::string, Box> Halide::Internal::boxes_required (Expr e, const Scope< Interval > & scope = Scope< Interval >::empty_scope(), const FuncValueBounds & func_bounds = FuncValueBounds())
Compute rectangular domains large enough to cover all the 'Call's to each function that occurs within a given statement or expression.
This is useful for figuring out what regions of things to evaluate.
std::map<std::string, Box> Halide::Internal::boxes_required (Stmt s, const Scope< Interval > & scope = Scope< Interval >::empty_scope(), const FuncValueBounds & func_bounds = FuncValueBounds())
Compute rectangular domains large enough to cover all the 'Call's to each function that occurs within a given statement or expression.
This is useful for figuring out what regions of things to evaluate.
std::map<std::string, Box> Halide::Internal::boxes_provided (Expr e, const Scope< Interval > & scope = Scope< Interval >::empty_scope(), const FuncValueBounds & func_bounds = FuncValueBounds())
Compute rectangular domains large enough to cover all the 'Provides's to each function that occurs within a given statement or expression.
std::map<std::string, Box> Halide::Internal::boxes_provided (Stmt s, const Scope< Interval > & scope = Scope< Interval >::empty_scope(), const FuncValueBounds & func_bounds = FuncValueBounds())
Compute rectangular domains large enough to cover all the 'Provides's to each function that occurs within a given statement or expression.
std::map<std::string, Box> Halide::Internal::boxes_touched (Expr e, const Scope< Interval > & scope = Scope< Interval >::empty_scope(), const FuncValueBounds & func_bounds = FuncValueBounds())
Compute rectangular domains large enough to cover all the 'Call's and 'Provides's to each function that occurs within a given statement or expression.
std::map<std::string, Box> Halide::Internal::boxes_touched (Stmt s, const Scope< Interval > & scope = Scope< Interval >::empty_scope(), const FuncValueBounds & func_bounds = FuncValueBounds())
Compute rectangular domains large enough to cover all the 'Call's and 'Provides's to each function that occurs within a given statement or expression.
Box Halide::Internal::box_required (Expr e, std::string fn, const Scope< Interval > & scope = Scope< Interval >::empty_scope(), const FuncValueBounds & func_bounds = FuncValueBounds())
Variants of the above that are only concerned with a single function.
Box Halide::Internal::box_required (Stmt s, std::string fn, const Scope< Interval > & scope = Scope< Interval >::empty_scope(), const FuncValueBounds & func_bounds = FuncValueBounds())
Variants of the above that are only concerned with a single function.
Box Halide::Internal::box_provided (Expr e, std::string fn, const Scope< Interval > & scope = Scope< Interval >::empty_scope(), const FuncValueBounds & func_bounds = FuncValueBounds())
Variants of the above that are only concerned with a single function.
Box Halide::Internal::box_provided (Stmt s, std::string fn, const Scope< Interval > & scope = Scope< Interval >::empty_scope(), const FuncValueBounds & func_bounds = FuncValueBounds())
Variants of the above that are only concerned with a single function.
Box Halide::Internal::box_touched (Expr e, std::string fn, const Scope< Interval > & scope = Scope< Interval >::empty_scope(), const FuncValueBounds & func_bounds = FuncValueBounds())
Variants of the above that are only concerned with a single function.
Box Halide::Internal::box_touched (Stmt s, std::string fn, const Scope< Interval > & scope = Scope< Interval >::empty_scope(), const FuncValueBounds & func_bounds = FuncValueBounds())
Variants of the above that are only concerned with a single function.
FuncValueBounds Halide::Internal::compute_function_value_bounds (const std::vector< std::string > & order, const std::map< std::string, Function > & env)
Compute the maximum and minimum possible value for each function in an environment.
void Halide::Internal::bounds_test ()
Stmt Halide::Internal::bounds_inference (Stmt , const std::vector< Function > & outputs, const std::vector< std::string > & realization_order, const std::vector< std::vector< std::string >> & fused_groups, const std::map< std::string, Function > & environment, const std::map< std::pair< std::string, int >, Interval > & func_bounds, const Target & target)
Take a partially lowered statement that includes symbolic representations of the bounds over which things should be realized, and inject expressions defining those bounds.
Stmt Halide::Internal::bound_small_allocations (const Stmt & s)
Expr Halide::Internal::buffer_accessor (const Buffer<> & buf, const std::vector< Expr > & args)
Referenced by Halide::Buffer<>::operator()().
template<typename T , typename = typename std::enable_if<!std::is_convertible<T, std::string>::value>::type> std::string Halide::Internal::get_name_from_end_of_parameter_pack (T &&)
Definition at line 40 of file Buffer.h.
Referenced by get_name_from_end_of_parameter_pack().
std::string Halide::Internal::get_name_from_end_of_parameter_pack (const std::string & n) inline
Definition at line 44 of file Buffer.h.
std::string Halide::Internal::get_name_from_end_of_parameter_pack () inline
Definition at line 48 of file Buffer.h.
template<typename First , typename Second , typename... Args> std::string Halide::Internal::get_name_from_end_of_parameter_pack (First first, Second second, Args &&... rest)
Definition at line 55 of file Buffer.h.
References get_name_from_end_of_parameter_pack().
void Halide::Internal::get_shape_from_start_of_parameter_pack_helper (std::vector< int > & , const std::string &) inline
Definition at line 59 of file Buffer.h.
Referenced by get_shape_from_start_of_parameter_pack(), and get_shape_from_start_of_parameter_pack_helper().
void Halide::Internal::get_shape_from_start_of_parameter_pack_helper (std::vector< int > &) inline
Definition at line 62 of file Buffer.h.
template<typename... Args> void Halide::Internal::get_shape_from_start_of_parameter_pack_helper (std::vector< int > & result, int x, Args &&... rest)
Definition at line 66 of file Buffer.h.
References get_shape_from_start_of_parameter_pack_helper().
template<typename... Args> std::vector<int> Halide::Internal::get_shape_from_start_of_parameter_pack (Args &&... args)
Definition at line 73 of file Buffer.h.
References get_shape_from_start_of_parameter_pack_helper().
Stmt Halide::Internal::canonicalize_gpu_vars (Stmt s)
Canonicalize GPU var names into some pre-determined block/thread names (i.e.
__block_id_x, __thread_id_x, etc.). The x/y/z/w order is determined by the nesting order: innermost is assigned to x and so on.
llvm::StructType* Halide::Internal::build_closure_type (const Closure & closure, llvm::StructType * buffer_t, llvm::LLVMContext * context)
The llvm type of a struct containing all of the externally referenced state of a Closure.
void Halide::Internal::pack_closure (llvm::StructType * type, llvm::Value * dst, const Closure & closure, const Scope< llvm::Value * > & src, llvm::StructType * buffer_t, llvm::IRBuilder< llvm::ConstantFolder, llvm::IRBuilderDefaultInserter > * builder)
Emit code that builds a struct containing all the externally referenced state.
Requires you to pass it a type and struct to fill in, a scope to retrieve the llvm values from and a builder to place the packing code.
void Halide::Internal::unpack_closure (const Closure & closure, Scope< llvm::Value * > & dst, llvm::StructType * type, llvm::Value * src, llvm::IRBuilder< llvm::ConstantFolder, llvm::IRBuilderDefaultInserter > * builder)
Emit code that unpacks a struct containing all the externally referenced state into a symbol table.
Requires you to pass it a state struct type and value, a scope to fill, and a builder to place the unpacking code.
llvm::Type* Halide::Internal::llvm_type_of (llvm::LLVMContext * context, Halide::Type t)
Get the llvm type equivalent to a given halide type.
Referenced by Halide::Internal::CodeGen_LLVM::prepare_for_early_exit().
bool Halide::Internal::function_takes_user_context (const std::string & name)
Which built-in functions require a user-context first argument?
bool Halide::Internal::can_allocation_fit_on_stack (int64_t size)
Given a size (in bytes), return True if the allocation size can fit on the stack; otherwise, return False.
This routine asserts if size is non-positive.
Expr Halide::Internal::lower_euclidean_div (Expr a, Expr b)
Given a Halide Euclidean division/mod operation, define it in terms of div_round_to_zero or mod_round_to_zero.
Expr Halide::Internal::lower_euclidean_mod (Expr a, Expr b)
Given a Halide Euclidean division/mod operation, define it in terms of div_round_to_zero or mod_round_to_zero.
Stmt Halide::Internal::unpredicate_loads_stores (Stmt s)
Replace predicated loads/stores with unpredicated equivalents inside branches.
void Halide::Internal::get_target_options (const llvm::Module & module, llvm::TargetOptions & options, std::string & mcpu, std::string & mattrs)
Given an llvm::Module, set llvm:TargetOptions, cpu and attr information.
void Halide::Internal::clone_target_options (const llvm::Module & from, llvm::Module & to)
Given two llvm::Modules, clone target options from one to the other.
std::unique_ptr<llvm::TargetMachine> Halide::Internal::make_target_machine (const llvm::Module & module)
Given an llvm::Module, get or create an llvm:TargetMachine.
void Halide::Internal::set_function_attributes_for_target (llvm::Function * , Target)
Set the appropriate llvm Function attributes given a Target.
std::string Halide::Internal::cplusplus_function_mangled_name (const std::string & name, const std::vector< std::string > & namespaces, Type return_type, const std::vector< ExternFuncArgument > & args, const Target & target)
Return the mangled C++ name for a function.
The target parameter is used to decide on the C++ ABI/mangling style to use.
void Halide::Internal::cplusplus_mangle_test ()
Expr Halide::Internal::common_subexpression_elimination (const Expr & , bool lift_all = false)
Replace each common sub-expression in the argument with a variable, and wrap the resulting expr in a let statement giving a value to that variable.
This is important to do within Halide (instead of punting to llvm), because exprs that come in from the front-end are small when considered as a graph, but combinatorially large when considered as a tree. For an example of a such a case, see test/code_explosion.cpp
The last parameter determines whether all common subexpressions are lifted, or only those that the simplifier would not subsitute back in (e.g. addition of a constant).
Stmt Halide::Internal::common_subexpression_elimination (const Stmt & , bool lift_all = false)
Do common-subexpression-elimination on each expression in a statement.
Does not introduce let statements.
void Halide::Internal::cse_test ()
std::ostream & Halide::Internal::operator<< (std::ostream & stream, const Stmt &)
Emit a halide statement on an output stream (such as std::cout) in a human-readable form.
std::ostream & Halide::Internal::operator<< (std::ostream & , const LoweredFunc &)
Emit a halide LoweredFunc in a human readable format.
void Halide::Internal::debug_arguments (LoweredFunc * func)
Injects debug prints in a LoweredFunc that describe the arguments.
Mutates the given func.
Stmt Halide::Internal::debug_to_file (Stmt s, const std::vector< Function > & outputs, const std::map< std::string, Function > & env)
Takes a statement with Realize nodes still unlowered.
If the corresponding functions have a debug_file set, then inject code that will dump the contents of those functions to a file after the realization.
Referenced by Halide::Func::add_custom_lowering_pass().
Expr Halide::Internal::extract_odd_lanes (Expr a)
Extract the odd-numbered lanes in a vector.
Expr Halide::Internal::extract_even_lanes (Expr a)
Extract the even-numbered lanes in a vector.
Expr Halide::Internal::extract_lane (Expr vec, int lane)
Extract the nth lane of a vector.
Stmt Halide::Internal::rewrite_interleavings (Stmt s)
Look through a statement for expressions of the form select(ramp % 2 == 0, a, b) and replace them with calls to an interleave intrinsic.
void Halide::Internal::deinterleave_vector_test ()
void Halide::Internal::derivative_test ()
bool Halide::Internal::has_variable (const Expr & expr, const std::string & name)
Return true if expr depends on the variable.
bool Halide::Internal::has_let_defined (const Expr & expr, const std::string & name)
Return true if expr has a Let operation defining the variable.
Expr Halide::Internal::remove_let_definitions (const Expr & expr)
Remove all let definitions of expr.
std::vector<std::string> Halide::Internal::gather_variables (const Expr & expr, const std::vector< std::string > & filter)
Return a list of variables that expr depends on and are in the filter.
std::vector<std::string> Halide::Internal::gather_variables (const Expr & expr, const std::vector< Var > & filter)
std::map<std::string, ReductionVariableInfo> Halide::Internal::gather_rvariables (Expr expr)
std::map<std::string, ReductionVariableInfo> Halide::Internal::gather_rvariables (Tuple tuple)
Expr Halide::Internal::add_let_expression (const Expr & expr, const std::map< std::string, Expr > & let_var_mapping, const std::vector< std::string > & let_variables)
Add necessary let expressions to expr.
std::vector<Expr> Halide::Internal::sort_expressions (const Expr & expr)
Topologically sort the expression graph expressed by expr.
std::map<std::string, Box> Halide::Internal::inference_bounds (const std::vector< Func > & funcs, const std::vector< FuncBounds > & output_bounds)
Compute the bounds of funcs.
std::map<std::string, Box> Halide::Internal::inference_bounds (const Func & func, const FuncBounds & output_bounds)
std::vector<std::pair<Expr, Expr> > Halide::Internal::box_to_vector (const Box & bounds)
Convert Box to vector of (min, extent)
bool Halide::Internal::equal (const RDom & bounds0, const RDom & bounds1)
Return true if bounds0 and bounds1 represent the same bounds.
Referenced by Halide::Internal::ExprWithCompareCache::ExprWithCompareCache(), Halide::Internal::AssociativePattern::operator==(), and Halide::Internal::AssociativeOp::Replacement::operator==().
std::vector<std::string> Halide::Internal::vars_to_strings (const std::vector< Var > & vars)
Return a list of variable names.
ReductionDomain Halide::Internal::extract_rdom (const Expr & expr)
Return the reduction domain used by expr.
std::pair<bool, Expr> Halide::Internal::solve_inverse (Expr expr, const std::string & new_var, const std::string & var)
expr is new_var == f(var), solve for var == g(new_var) if multiple new_var correponds to same var, introduce a RDom
std::map<std::string, BufferInfo> Halide::Internal::find_buffer_calls (const Func & func)
std::set<std::string> Halide::Internal::find_implicit_variables (Expr expr)
Find all implicit variables in expr.
Expr Halide::Internal::substitute_rdom_predicate (const std::string & name, const Expr & replacement, const Expr & expr)
Substitute the variable.
Also replace all occurence in rdom.where() predicates.
bool Halide::Internal::is_calling_function (const std::string & func_name, const Expr & expr, const std::map< std::string, Expr > & let_var_mapping)
Return true if expr contains call to func_name.
bool Halide::Internal::is_calling_function (const Expr & expr, const std::map< std::string, Expr > & let_var_mapping)
Return true if expr depends on any function or buffer.
Expr Halide::Internal::make_device_interface_call (DeviceAPI device_api)
Get an Expr which evaluates to the device interface for the given device api at runtime.
Stmt Halide::Internal::inject_early_frees (Stmt s)
Take a statement with allocations and inject markers (of the form of calls to "mark buffer dead") after the last use of each allocation.
Targets may use this to free buffers earlier than the close of their Allocate node.
Stmt Halide::Internal::eliminate_bool_vectors (Stmt s)
Some targets treat vectors of bools as integers of the same type that the boolean operation is being used to operate on.
For example, instead of select(i1x8, u16x8, u16x8), the target would prefer to see select(u16x8, u16x8, u16x8), where the first argument is a vector of integers representing a mask. This pass converts vectors of bools to vectors of integers to meet this requirement. This is done by injecting intrinsics to convert bools to architecture-specific masks, and using a select_mask instrinsic instead of a Select node. Because the masks are architecture specific, they may not be stored or loaded. On Stores, the masks are converted to UInt(8) with a value of 0 or 1, which is our canonical in-memory representation of a bool.
Expr Halide::Internal::eliminate_bool_vectors (Expr s)
Some targets treat vectors of bools as integers of the same type that the boolean operation is being used to operate on.
For example, instead of select(i1x8, u16x8, u16x8), the target would prefer to see select(u16x8, u16x8, u16x8), where the first argument is a vector of integers representing a mask. This pass converts vectors of bools to vectors of integers to meet this requirement. This is done by injecting intrinsics to convert bools to architecture-specific masks, and using a select_mask instrinsic instead of a Select node. Because the masks are architecture specific, they may not be stored or loaded. On Stores, the masks are converted to UInt(8) with a value of 0 or 1, which is our canonical in-memory representation of a bool.
Type Halide::Internal::eliminated_bool_type (Type bool_type, Type other_type) inline
If a type is a boolean vector, find the type that it has been changed to by eliminate_bool_vectors.
Definition at line 32 of file EliminateBoolVectors.h.
References Halide::Type::bits(), Halide::Type::Int, Halide::Type::is_vector(), Halide::Type::with_bits(), and Halide::Type::with_code().
template<> RefCount& Halide::Internal::ref_count< IRNode > (const IRNode * t) inline
Definition at line 102 of file Expr.h.
template<> void Halide::Internal::destroy< IRNode > (const IRNode * t) inline
Definition at line 105 of file Expr.h.
template<typename StmtOrExpr , typename T > bool Halide::Internal::stmt_or_expr_uses_vars (StmtOrExpr e, const Scope< T > & v, const Scope< Expr > & s = Scope<Expr>::empty_scope()) inline
Test if a statement or expression references any of the variables in a scope, additionally considering variables bound to Expr's in the scope provided in the final argument.
Definition at line 55 of file ExprUsesVar.h.
References Halide::Internal::ExprUsesVars< T >::result.
Referenced by expr_uses_vars(), and stmt_uses_vars().
template<typename StmtOrExpr > bool Halide::Internal::stmt_or_expr_uses_var (StmtOrExpr e, const std::string & v, const Scope< Expr > & s = Scope<Expr>::empty_scope()) inline
Test if a statement or expression references the given variable, additionally considering variables bound to Expr's in the scope provided in the final argument.
Definition at line 67 of file ExprUsesVar.h.
References Halide::Internal::Scope< T >::push().
Referenced by expr_uses_var(), and stmt_uses_var().
bool Halide::Internal::expr_uses_var (Expr e, const std::string & v, const Scope< Expr > & s = Scope<Expr>::empty_scope()) inline
Test if an expression references the given variable, additionally considering variables bound to Expr's in the scope provided in the final argument.
Definition at line 78 of file ExprUsesVar.h.
References stmt_or_expr_uses_var().
bool Halide::Internal::stmt_uses_var (Stmt stmt, const std::string & v, const Scope< Expr > & s = Scope<Expr>::empty_scope()) inline
Test if a statement references the given variable, additionally considering variables bound to Expr's in the scope provided in the final argument.
Definition at line 87 of file ExprUsesVar.h.
References stmt_or_expr_uses_var().
template<typename T > bool Halide::Internal::expr_uses_vars (Expr e, const Scope< T > & v, const Scope< Expr > & s = Scope<Expr>::empty_scope()) inline
Test if an expression references any of the variables in a scope, additionally considering variables bound to Expr's in the scope provided in the final argument.
Definition at line 97 of file ExprUsesVar.h.
References stmt_or_expr_uses_vars().
template<typename T > bool Halide::Internal::stmt_uses_vars (Stmt stmt, const Scope< T > & v, const Scope< Expr > & s = Scope<Expr>::empty_scope()) inline
Test if a statement references any of the variables in a scope, additionally considering variables bound to Expr's in the scope provided in the final argument.
Definition at line 107 of file ExprUsesVar.h.
References stmt_or_expr_uses_vars().
std::map<std::string, Function> Halide::Internal::find_direct_calls (Function f)
Construct a map from name to Function definition object for all Halide functions called directly in the definition of the Function f, including in update definitions, update index expressions, and RDom extents.
This map does not include the Function f, unless it is called recursively by itself.
std::map<std::string, Function> Halide::Internal::find_transitive_calls (Function f)
Construct a map from name to Function definition object for all Halide functions called directly in the definition of the Function f, or indirectly in those functions' definitions, recursively.
This map always includes the Function f.
void Halide::Internal::populate_environment (Function f, std::map< std::string, Function > & env)
Find all Functions transitively referenced by f in any way and add them to the given map.
template<typename Last > void Halide::Internal::check_types (const Tuple & t, int idx) inline
Definition at line 2305 of file Func.h.
References user_assert.
Referenced by Halide::evaluate(), and Halide::evaluate_may_gpu().
template<typename First , typename Second , typename... Rest> void Halide::Internal::check_types (const Tuple & t, int idx) inline
Definition at line 2314 of file Func.h.
template<typename Last > void Halide::Internal::assign_results (Realization & r, int idx, Last last) inline
Definition at line 2320 of file Func.h.
Referenced by Halide::evaluate(), and Halide::evaluate_may_gpu().
template<typename First , typename Second , typename... Rest> void Halide::Internal::assign_results (Realization & r, int idx, First first, Second second, Rest &&... rest) inline
Definition at line 2326 of file Func.h.
void Halide::Internal::schedule_scalar (Func f) inline
Definition at line 2362 of file Func.h.
References Halide::get_jit_target_from_environment(), Halide::Func::gpu_single_thread(), Halide::Target::has_feature(), Halide::Target::has_gpu_feature(), Halide::Func::hexagon(), Halide::Target::HVX_128, and Halide::Target::HVX_64.
Referenced by Halide::evaluate_may_gpu().
std::pair<std::vector<Function>, std::map<std::string, Function> > Halide::Internal::deep_copy (const std::vector< Function > & outputs, const std::map< std::string, Function > & env)
Deep copy an entire Function DAG.
Referenced by Halide::Internal::FuncSchedule::FuncSchedule(), Halide::Internal::Function::get_contents(), Halide::Internal::Function::operator ExternFuncArgument(), and Halide::Internal::ReductionDomain::ReductionDomain().
Stmt Halide::Internal::zero_gpu_loop_mins (Stmt s)
Rewrite all GPU loops to have a min of zero.
Stmt Halide::Internal::fuse_gpu_thread_loops (Stmt s)
Converts Halide's GPGPU IR to the OpenCL/CUDA/Metal model.
Within every loop over gpu block indices, fuse the inner loops over thread indices into a single loop (with predication to turn off threads). Also injects synchronization points as needed, and hoists allocations at the block level out into a single shared memory array.
Stmt Halide::Internal::fuzz_float_stores (Stmt s)
On every store of a floating point value, mask off the least-significant-bit of the mantissa.
We've found that whether or not this dramatically changes the output of a pipeline correlates very well with whether or not a pipeline will produce very different outputs on different architectures (e.g. with and without FMA). It's also a useful way to detect bad tests, such as those that expect exact floating point equality across platforms.
void Halide::Internal::generator_test ()
Referenced by Halide::Generator< T >::call_schedule().
std::vector<Expr> Halide::Internal::parameter_constraints (const Parameter & p)
Referenced by Halide::Internal::ValueTracker::ValueTracker().
template<typename T > HALIDE_NO_USER_CODE_INLINE std::string Halide::Internal::enum_to_string (const std::map< std::string, T > & enum_map, const T & t)
Definition at line 288 of file Generator.h.
References user_error.
Referenced by Halide::Internal::GeneratorParam_Enum< T >::get_default_value(), and halide_type_to_enum_string().
template<typename T > T Halide::Internal::enum_from_string (const std::map< std::string, T > & enum_map, const std::string & s)
Definition at line 299 of file Generator.h.
References get_halide_type_enum_map(), and user_assert.
const std::map<std::string, Halide::Type>& Halide::Internal::get_halide_type_enum_map ()
Referenced by enum_from_string(), and halide_type_to_enum_string().
std::string Halide::Internal::halide_type_to_enum_string (const Type & t) inline
Definition at line 306 of file Generator.h.
References enum_to_string(), generate_filter_main(), get_halide_type_enum_map(), halide_type_to_c_source(), and halide_type_to_c_type().
std::string Halide::Internal::halide_type_to_c_source (const Type & t)
Referenced by Halide::Internal::GeneratorParam_Type< T >::get_default_value(), and halide_type_to_enum_string().
std::string Halide::Internal::halide_type_to_c_type (const Type & t)
Referenced by Halide::Internal::GeneratorInput_Buffer< T >::get_c_type(), Halide::Internal::GeneratorOutput_Buffer< T >::get_c_type(), and halide_type_to_enum_string().
int Halide::Internal::generate_filter_main (int argc, char ** argv, std::ostream & cerr)
generate_filter_main() is a convenient wrapper for GeneratorRegistry::create() + compile_to_files(); it can be trivially wrapped by a "real" main() to produce a command-line utility for ahead-of-time filter compilation.
Referenced by halide_type_to_enum_string().
template<typename T > T Halide::Internal::parse_scalar (const std::string & value)
Definition at line 2367 of file Generator.h.
References parse_halide_type_list(), and user_assert.
std::vector<Type> Halide::Internal::parse_halide_type_list (const std::string & types)
Referenced by parse_scalar().
Stmt Halide::Internal::inject_hexagon_rpc (Stmt s, const Target & host_target, Module & module)
Pull loops marked with the Hexagon device API to a separate module, and call them through the Hexagon host runtime module.
Buffer<uint8_t> Halide::Internal::compile_module_to_hexagon_shared_object (const Module & device_code)
Stmt Halide::Internal::optimize_hexagon_shuffles (Stmt s, int lut_alignment)
Replace indirect and other loads with simple loads + vlut calls.
Stmt Halide::Internal::vtmpy_generator (Stmt s)
Generate vtmpy instruction if possible.
Stmt Halide::Internal::optimize_hexagon_instructions (Stmt s, Target t, Scope< ModulusRemainder > & alignment_info)
Hexagon deinterleaves when performing widening operations, and interleaves when performing narrowing operations.
This pass rewrites widenings/narrowings to be explicit in the IR, and attempts to simplify away most of the interleaving/deinterleaving.
Expr Halide::Internal::native_deinterleave (Expr x)
Generate deinterleave or interleave operations, operating on groups of vectors at a time.
Expr Halide::Internal::native_interleave (Expr x)
Generate deinterleave or interleave operations, operating on groups of vectors at a time.
bool Halide::Internal::is_native_deinterleave (Expr x)
Generate deinterleave or interleave operations, operating on groups of vectors at a time.
bool Halide::Internal::is_native_interleave (Expr x)
Generate deinterleave or interleave operations, operating on groups of vectors at a time.
std::vector<InferredArgument> Halide::Internal::infer_arguments (Stmt body, const std::vector< Function > & outputs)
Referenced by Halide::Pipeline::add_custom_lowering_pass(), Halide::Func::operator ExternFuncArgument(), and Halide::Internal::InferredArgument::operator<().
Stmt Halide::Internal::call_extern_and_assert (const std::string & name, const std::vector< Expr > & args)
A helper function to call an extern function, and assert that it returns 0.
Stmt Halide::Internal::inject_host_dev_buffer_copies (Stmt s, const Target & t)
Inject calls to halide_device_malloc, halide_copy_to_device, and halide_copy_to_host as needed.
Stmt Halide::Internal::inject_opengl_intrinsics (Stmt s)
Take a statement with for kernel for loops and turn loads and stores inside the loops into OpenGL texture load and store intrinsics.
Should only be run when the OpenGL target is active.
Stmt Halide::Internal::inline_function (Stmt s, Function f)
Inline a single named function, which must be pure.
For a pure function to be inlined, it must not have any specializations (i.e. it can only have one values definition).
Expr Halide::Internal::inline_function (Expr e, Function f)
Inline a single named function, which must be pure.
For a pure function to be inlined, it must not have any specializations (i.e. it can only have one values definition).
void Halide::Internal::inline_function (Function caller, Function f)
Inline a single named function, which must be pure.
For a pure function to be inlined, it must not have any specializations (i.e. it can only have one values definition).
void Halide::Internal::validate_schedule_inlined_function (Function f)
Check if the schedule of an inlined function is legal, throwing an error if it is not.
void Halide::Internal::interval_test ()
Referenced by Halide::Internal::Interval::operator==().
template<typename T > RefCount& Halide::Internal::ref_count (const T * t)
Because in this header we don't yet know how client classes store their RefCount (and we don't want to depend on the declarations of the client classes), any class that you want to hold onto via one of these must provide implementations of ref_count and destroy, which we forward-declare here.
E.g. if you want to use IntrusivePtr<MyClass>, then you should define something like this in MyClass.cpp (assuming MyClass has a field: mutable RefCount ref_count):
template<> RefCount &ref_count<MyClass>(const MyClass *c) {return c->ref_count;} template<> void destroy<MyClass>(const MyClass *c) {delete c;}
Referenced by Halide::Internal::RefCount::is_zero().
template<typename T > void Halide::Internal::destroy (const T * t)
Because in this header we don't yet know how client classes store their RefCount (and we don't want to depend on the declarations of the client classes), any class that you want to hold onto via one of these must provide implementations of ref_count and destroy, which we forward-declare here.
E.g. if you want to use IntrusivePtr<MyClass>, then you should define something like this in MyClass.cpp (assuming MyClass has a field: mutable RefCount ref_count):
template<> RefCount &ref_count<MyClass>(const MyClass *c) {return c->ref_count;} template<> void destroy<MyClass>(const MyClass *c) {delete c;}
Referenced by Halide::Internal::RefCount::is_zero().
bool Halide::Internal::equal (const Expr & a, const Expr & b)
Compare IR nodes for equality of value.
Traverses entire IR tree. For equality of reference, use Expr::same_as. If you're comparing non-CSE'd Exprs, use graph_equal, which is safe for nasty graphs of IR nodes.
bool Halide::Internal::equal (const Stmt & a, const Stmt & b)
Compare IR nodes for equality of value.
Traverses entire IR tree. For equality of reference, use Expr::same_as. If you're comparing non-CSE'd Exprs, use graph_equal, which is safe for nasty graphs of IR nodes.
bool Halide::Internal::graph_equal (const Expr & a, const Expr & b)
Compare IR nodes for equality of value.
Traverses entire IR tree. For equality of reference, use Expr::same_as. If you're comparing non-CSE'd Exprs, use graph_equal, which is safe for nasty graphs of IR nodes.
Referenced by Halide::Internal::ExprWithCompareCache::ExprWithCompareCache().
bool Halide::Internal::graph_equal (const Stmt & a, const Stmt & b)
Compare IR nodes for equality of value.
Traverses entire IR tree. For equality of reference, use Expr::same_as. If you're comparing non-CSE'd Exprs, use graph_equal, which is safe for nasty graphs of IR nodes.
void Halide::Internal::ir_equality_test ()
Referenced by Halide::Internal::ExprWithCompareCache::ExprWithCompareCache().
bool Halide::Internal::expr_match (Expr pattern, Expr expr, std::vector< Expr > & result)
Does the first expression have the same structure as the second? Variables in the first expression with the name * are interpreted as wildcards, and their matching equivalent in the second expression is placed in the vector give as the third argument.
Wildcards require the types to match. For the type bits and width, a 0 indicates "match anything". So an Int(8, 0) will match 8-bit integer vectors of any width (including scalars), and a UInt(0, 0) will match any unsigned integer type.
For example:
Expr x = Variable::make(Int(32), "*");
match(x + x, 3 + (2*k), result)
should return true, and set result[0] to 3 and result[1] to 2*k.
bool Halide::Internal::expr_match (Expr pattern, Expr expr, std::map< std::string, Expr > & result)
Does the first expression have the same structure as the second? Variables are matched consistently.
The first time a variable is matched, it assumes the value of the matching part of the second expression. Subsequent matches must be equal to the first match.
For example:
Var x("x"), y("y");
match(x*(x + y), a*(a + b), result)
should return true, and set result["x"] = a, and result["y"] = b.
void Halide::Internal::expr_match_test ()
bool Halide::Internal::is_const (const Expr & e)
Is the expression either an IntImm, a FloatImm, a StringImm, or a Cast of the same, or a Ramp or Broadcast of the same.
Doesn't do any constant folding.
Referenced by halide_handle_cplusplus_type::make().
bool Halide::Internal::is_const (const Expr & e, int64_t v)
Is the expression an IntImm, FloatImm of a particular value, or a Cast, or Broadcast of the same.
const int64_t* Halide::Internal::as_const_int (const Expr & e)
If an expression is an IntImm or a Broadcast of an IntImm, return a pointer to its value.
Otherwise returns nullptr.
Referenced by Halide::cast(), Halide::fast_pow(), Halide::lerp(), and Halide::pow().
const uint64_t* Halide::Internal::as_const_uint (const Expr & e)
If an expression is a UIntImm or a Broadcast of a UIntImm, return a pointer to its value.
Otherwise returns nullptr.
Referenced by Halide::cast().
const double* Halide::Internal::as_const_float (const Expr & e)
If an expression is a FloatImm or a Broadcast of a FloatImm, return a pointer to its value.
Otherwise returns nullptr.
Referenced by Halide::cast(), and Halide::lerp().
bool Halide::Internal::is_const_power_of_two_integer (const Expr & e, int * bits)
Is the expression a constant integer power of two.
Also returns log base two of the expression if it is. Only returns true for integer types.
bool Halide::Internal::is_positive_const (const Expr & e)
Is the expression a const (as defined by is_const), and also strictly greater than zero (in all lanes, if a vector expression)
bool Halide::Internal::is_negative_const (const Expr & e)
Is the expression a const (as defined by is_const), and also strictly less than zero (in all lanes, if a vector expression)
bool Halide::Internal::is_negative_negatable_const (const Expr & e)
Is the expression a const (as defined by is_const), and also strictly less than zero (in all lanes, if a vector expression) and is its negative value representable.
(This excludes the most negative value of the Expr's type from inclusion. Intended to be used when the value will be negated as part of simplification.)
bool Halide::Internal::is_undef (const Expr & e)
Is the expression an undef.
bool Halide::Internal::is_zero (const Expr & e)
Is the expression a const (as defined by is_const), and also equal to zero (in all lanes, if a vector expression)
Referenced by Halide::operator%().
bool Halide::Internal::is_one (const Expr & e)
Is the expression a const (as defined by is_const), and also equal to one (in all lanes, if a vector expression)
Referenced by Halide::Internal::Box::maybe_unused().
bool Halide::Internal::is_two (const Expr & e)
Is the expression a const (as defined by is_const), and also equal to two (in all lanes, if a vector expression)
bool Halide::Internal::is_no_op (const Stmt & s)
Is the statement a no-op (which we represent as either an undefined Stmt, or as an Evaluate node of a constant)
bool Halide::Internal::is_pure (const Expr & e)
Does the expression 1) Take on the same value no matter where it appears in a Stmt, and 2) Evaluating it has no side-effects.
Expr Halide::Internal::make_const (Type t, int64_t val)
Construct an immediate of the given type from any numeric C++ type.
Referenced by Halide::cast(), make_const(), Halide::max(), Halide::min(), Halide::Internal::GeneratorParamImpl< LoopLevel >::operator Expr(), Halide::operator!=(), Halide::operator%(), Halide::operator*(), Halide::operator+(), Halide::operator-(), Halide::operator/(), Halide::operator<(), Halide::operator<<(), Halide::operator<=(), Halide::operator==(), Halide::operator>(), Halide::operator>=(), and Halide::operator>>().
Expr Halide::Internal::make_const (Type t, uint64_t val)
Construct an immediate of the given type from any numeric C++ type.
Expr Halide::Internal::make_const (Type t, double val)
Construct an immediate of the given type from any numeric C++ type.
Expr Halide::Internal::make_const (Type t, int32_t val) inline
Construct an immediate of the given type from any numeric C++ type.
Definition at line 91 of file IROperator.h.
References make_const().
Expr Halide::Internal::make_const (Type t, uint32_t val) inline
Construct an immediate of the given type from any numeric C++ type.
Definition at line 92 of file IROperator.h.
References make_const().
Expr Halide::Internal::make_const (Type t, int16_t val) inline
Construct an immediate of the given type from any numeric C++ type.
Definition at line 93 of file IROperator.h.
References make_const().
Expr Halide::Internal::make_const (Type t, uint16_t val) inline
Construct an immediate of the given type from any numeric C++ type.
Definition at line 94 of file IROperator.h.
References make_const().
Expr Halide::Internal::make_const (Type t, int8_t val) inline
Construct an immediate of the given type from any numeric C++ type.
Definition at line 95 of file IROperator.h.
References make_const().
Expr Halide::Internal::make_const (Type t, uint8_t val) inline
Construct an immediate of the given type from any numeric C++ type.
Definition at line 96 of file IROperator.h.
References make_const().
Expr Halide::Internal::make_const (Type t, bool val) inline
Construct an immediate of the given type from any numeric C++ type.
Definition at line 97 of file IROperator.h.
References make_const().
Expr Halide::Internal::make_const (Type t, float val) inline
Construct an immediate of the given type from any numeric C++ type.
Definition at line 98 of file IROperator.h.
References make_const().
Expr Halide::Internal::make_const (Type t, float16_t val) inline
Construct an immediate of the given type from any numeric C++ type.
Definition at line 99 of file IROperator.h.
References Halide::Runtime::Internal::a, Halide::Runtime::Internal::b, check_representable(), const_false(), const_true(), halide_erf(), halide_exp(), halide_log(), lossless_cast(), make_bool(), make_const(), make_one(), make_two(), make_zero(), match_types(), raise_to_integer_power(), and split_into_ands().
void Halide::Internal::check_representable (Type t, int64_t val)
Check if a constant value can be correctly represented as the given type.
Referenced by make_const(), Halide::max(), Halide::min(), Halide::operator!=(), Halide::operator%(), Halide::operator*(), Halide::operator+(), Halide::operator-(), Halide::operator/(), Halide::operator<(), Halide::operator<<(), Halide::operator<=(), Halide::operator==(), Halide::operator>(), Halide::operator>=(), and Halide::operator>>().
Expr Halide::Internal::make_bool (bool val, int lanes = 1)
Construct a boolean constant from a C++ boolean value.
May also be a vector if width is given. It is not possible to coerce a C++ boolean to Expr because if we provide such a path then char objects can ambiguously be converted to Halide Expr or to std::string. The problem is that C++ does not have a real bool type - it is in fact close enough to char that C++ does not know how to distinguish them. make_bool is the explicit coercion.
Referenced by make_const().
Expr Halide::Internal::make_zero (Type t)
Construct the representation of zero in the given type.
Referenced by make_const(), Halide::operator&&(), and Halide::operator-().
Expr Halide::Internal::make_one (Type t)
Construct the representation of one in the given type.
Referenced by make_const(), and Halide::operator||().
Expr Halide::Internal::make_two (Type t)
Construct the representation of two in the given type.
Referenced by make_const().
Expr Halide::Internal::const_true (int lanes = 1)
Construct the constant boolean true.
May also be a vector of trues, if a lanes argument is given.
Referenced by make_const().
Expr Halide::Internal::const_false (int lanes = 1)
Construct the constant boolean false.
May also be a vector of falses, if a lanes argument is given.
Referenced by make_const().
Expr Halide::Internal::lossless_cast (Type t, Expr e)
Attempt to cast an expression to a smaller type while provably not losing information.
If it can't be done, return an undefined Expr.
Referenced by Halide::clamp(), and make_const().
void Halide::Internal::match_types (Expr & a, Expr & b)
Coerce the two expressions to have the same type, using C-style casting rules.
For the purposes of casting, a boolean type is UInt(1). We use the following procedure:
If the types already match, do nothing.
Then, if one type is a vector and the other is a scalar, the scalar is broadcast to match the vector width, and we continue.
Then, if one type is floating-point and the other is not, the non-float is cast to the floating-point type, and we're done.
Then, if both types are unsigned ints, the one with fewer bits is cast to match the one with more bits and we're done.
Then, if both types are signed ints, the one with fewer bits is cast to match the one with more bits and we're done.
Finally, if one type is an unsigned int and the other type is a signed int, both are cast to a signed int with the greater of the two bit-widths. For example, matching an Int(8) with a UInt(16) results in an Int(16).
Referenced by Halide::absd(), Halide::div_round_to_zero(), make_const(), Halide::max(), Halide::min(), Halide::mod_round_to_zero(), Halide::operator!=(), Halide::operator%(), Halide::operator&&(), Halide::operator*(), Halide::operator+(), Halide::operator-(), Halide::operator/(), Halide::operator<(), Halide::operator<<(), Halide::operator<=(), Halide::operator==(), Halide::operator>(), Halide::operator>=(), Halide::operator>>(), and Halide::operator||().
Expr Halide::Internal::halide_log (Expr a)
Halide's vectorizable transcendentals.
Referenced by make_const().
Expr Halide::Internal::halide_exp (Expr a)
Halide's vectorizable transcendentals.
Referenced by make_const().
Expr Halide::Internal::halide_erf (Expr a)
Halide's vectorizable transcendentals.
Referenced by Halide::erf(), and make_const().
Expr Halide::Internal::raise_to_integer_power (Expr a, int64_t b)
Raise an expression to an integer power by repeatedly multiplying it by itself.
Referenced by Halide::fast_pow(), make_const(), and Halide::pow().
void Halide::Internal::split_into_ands (const Expr & cond, std::vector< Expr > & result)
Split a boolean condition into vector of ANDs.
If 'cond' is undefined, return an empty vector.
Referenced by make_const().
Expr Halide::Internal::strided_ramp_base (Expr e, int stride = 1)
If e is a ramp expression with stride, default 1, return the base, otherwise undefined.
HALIDE_NO_USER_CODE_INLINE void Halide::Internal::collect_print_args (std::vector< Expr > & args) inline
Definition at line 1724 of file IROperator.h.
Referenced by collect_print_args(), Halide::print(), Halide::print_when(), and Halide::require().
template<typename... Args> HALIDE_NO_USER_CODE_INLINE void Halide::Internal::collect_print_args (std::vector< Expr > & args, const char * arg, Args &&... more_args) inline
Definition at line 1728 of file IROperator.h.
References collect_print_args().
template<typename... Args> HALIDE_NO_USER_CODE_INLINE void Halide::Internal::collect_print_args (std::vector< Expr > & args, Expr arg, Args &&... more_args) inline
Definition at line 1734 of file IROperator.h.
References collect_print_args(), and Halide::print().
Expr Halide::Internal::memoize_tag_helper (Expr result, const std::vector< Expr > & cache_key_values)
Referenced by Halide::memoize_tag(), and Halide::undef().
std::ostream& Halide::Internal::operator<< (std::ostream & stream, const AssociativePattern &)
Emit a halide associative pattern on an output stream (such as std::cout) in a human-readable form.
std::ostream& Halide::Internal::operator<< (std::ostream & stream, const AssociativeOp &)
Emit a halide associative op on an output stream (such as std::cout) in a human-readable form.
std::ostream& Halide::Internal::operator<< (std::ostream & stream, const ForType &)
Emit a halide for loop type (vectorized, serial, etc) in a human readable form.
std::ostream& Halide::Internal::operator<< (std::ostream & stream, const NameMangling &)
Emit a halide name mangling value in a human readable format.
std::ostream& Halide::Internal::operator<< (std::ostream & stream, const LinkageType &)
Emit a halide linkage value in a human readable format.
Expr Halide::Internal::lower_lerp (Expr zero_val, Expr one_val, Expr weight)
Build Halide IR that computes a lerp.
Use by codegen targets that don't have a native lerp.
Stmt Halide::Internal::loop_invariant_code_motion (Stmt)
Hoist loop-invariants out of inner loops.
This is especially important in cases where LLVM would not do it for us automatically. For example, it hoists loop invariants out of cuda kernels.
template<typename T > auto Halide::Internal::iterator_to_pointer (T iter) -> decltype(&*std::declval<T>())
Definition at line 84 of file LLVM_Headers.h.
llvm::Triple Halide::Internal::get_triple_for_target (const Target & target)
Return the llvm::Triple that corresponds to the given Halide Target.
std::unique_ptr<llvm::Module> Halide::Internal::get_initial_module_for_target (Target , llvm::LLVMContext * , bool for_shared_jit_runtime = false, bool just_gpu = false)
Create an llvm module containing the support code for a given target.
std::unique_ptr<llvm::Module> Halide::Internal::get_initial_module_for_ptx_device (Target , llvm::LLVMContext * c)
Create an llvm module containing the support code for ptx device.
void Halide::Internal::add_bitcode_to_module (llvm::LLVMContext * context, llvm::Module & module, const std::vector< uint8_t > & bitcode, const std::string & name)
Link a block of llvm bitcode into an llvm module.
Stmt Halide::Internal::loop_carry (Stmt , int max_carried_values = 8)
Reuse loads done on previous loop iterations by stashing them in induction variables instead of redoing the load.
If the loads are predicated, the predicates need to match. Can be an optimization or pessimization depending on how good the L1 cache is on the architecture and how many memory issue slots there are. Currently only intended for Hexagon.
Module Halide::Internal::lower (const std::vector< Function > & output_funcs, const std::string & pipeline_name, const Target & t, const std::vector< Argument > & args, const LinkageType linkage_type, const std::vector< IRMutator2 * > & custom_passes = std::vector< IRMutator2 * >())
Given a vector of scheduled halide functions, create a Module that evaluates it.
Automatically pulls in all the functions f depends on. Some stages of lowering may be target-specific. The Module may contain submodules for computation offloaded to another execution engine or API as well as buffers that are used in the passed in Stmt. Multiple LoweredFuncs are added to support legacy buffer_t calling convention.
Stmt Halide::Internal::lower_main_stmt (const std::vector< Function > & output_funcs, const std::string & pipeline_name, const Target & t, const std::vector< IRMutator2 * > & custom_passes = std::vector< IRMutator2 * >())
Given a halide function with a schedule, create a statement that evaluates it.
Automatically pulls in all the functions f depends on. Some stages of lowering may be target-specific. Mostly used as a convenience function in tests that wish to assert some property of the lowered IR.
void Halide::Internal::lower_test ()
Stmt Halide::Internal::lower_warp_shuffles (Stmt s)
Rewrite access to things stored outside the loop over GPU lanes to use nvidia's warp shuffle instructions.
llvm::Function* Halide::Internal::define_matlab_wrapper (llvm::Module * module, llvm::Function * pipeline_argv_wrapper, llvm::Function * metadata_getter)
Add a mexFunction wrapper definition to the module, calling the function with the name pipeline_name.
Returns the mexFunction definition.
Stmt Halide::Internal::inject_memoization (Stmt s, const std::map< std::string, Function > & env, const std::string & name, const std::vector< Function > & outputs)
Transform pipeline calls for Funcs scheduled with memoize to do a lookup call to the runtime cache implementation, and if there is a miss, compute the results and call the runtime to store it back to the cache.
Should leave non-memoized Funcs unchanged.
Stmt Halide::Internal::rewrite_memoized_allocations (Stmt s, const std::map< std::string, Function > & env)
This should be called after Storage Flattening has added Allocation IR nodes.
It connects the memoization cache lookups to the Allocations so they point to the buffers from the memoization cache and those buffers are released when no longer used. Should not affect allocations for non-memoized Funcs.
ModulusRemainder Halide::Internal::modulus_remainder (Expr e)
For things like alignment analysis, often it's helpful to know if an integer expression is some multiple of a constant plus some other constant.
For example, it is straight-forward to deduce that ((10*x + 2)*(6*y - 3) - 1) is congruent to five modulo six.
We get the most information when the modulus is large. E.g. if something is congruent to 208 modulo 384, then we also know it's congruent to 0 mod 8, and we can possibly use it as an index for an aligned load. If all else fails, we can just say that an integer is congruent to zero modulo one.
Referenced by Halide::Internal::HexagonAlignmentAnalyzer::push().
ModulusRemainder Halide::Internal::modulus_remainder (Expr e, const Scope< ModulusRemainder > & scope)
If we have alignment information about external variables, we can let the analysis know about that using this version of modulus_remainder:
bool Halide::Internal::reduce_expr_modulo (Expr e, int modulus, int * remainder)
Reduce an expression modulo some integer.
Returns true and assigns to remainder if an answer could be found.
Referenced by Halide::Internal::HexagonAlignmentAnalyzer::is_aligned_impl().
bool Halide::Internal::reduce_expr_modulo (Expr e, int modulus, int * remainder, const Scope< ModulusRemainder > & scope)
Reduce an expression modulo some integer.
Returns true and assigns to remainder if an answer could be found.
void Halide::Internal::modulus_remainder_test ()
int64_t Halide::Internal::gcd (int64_t , int64_t)
The greatest common divisor of two integers.
int64_t Halide::Internal::lcm (int64_t , int64_t)
The least common multiple of two integers.
Monotonic Halide::Internal::is_monotonic (Expr e, const std::string & var)
void Halide::Internal::is_monotonic_test ()
bool Halide::Internal::can_parallelize_rvar (const std::string & rvar, const std::string & func, const Definition & r)
Returns whether or not Halide can prove that it is safe to parallelize an update definition across a specific variable.
If this returns true, it's definitely safe. If this returns false, it may still be safe, but Halide couldn't prove it.
void Halide::Internal::check_call_arg_types (const std::string & name, std::vector< Expr > * args, int dims)
Validate arguments to a call to a func, image or imageparam.
bool Halide::Internal::has_likely_tag (Expr e)
Return true if an expression uses a likely tag.
Stmt Halide::Internal::partition_loops (Stmt s)
Partitions loop bodies into a prologue, a steady state, and an epilogue.
Finds the steady state by hunting for use of clamped ramps, or the 'likely' intrinsic.
Stmt Halide::Internal::inject_placeholder_prefetch (Stmt s, const std::map< std::string, Function > & env, const std::string & prefix, const std::vector< PrefetchDirective > & prefetches)
Inject placeholder prefetches to 's'.
This placholder prefetch does not have explicit region to be prefetched yet. It will be computed during call to inject_prefetch.
Stmt Halide::Internal::inject_prefetch (Stmt s, const std::map< std::string, Function > & env)
Compute the actual region to be prefetched and place it to the placholder prefetch.
Wrap the prefetch call with condition when applicable.
Stmt Halide::Internal::reduce_prefetch_dimension (Stmt stmt, const Target & t)
Reduce a multi-dimensional prefetch into a prefetch of lower dimension (max dimension of the prefetch is specified by target architecture).
This keeps the 'max_dim' innermost dimensions and adds loops for the rest of the dimensions. If maximum prefetched-byte-size is specified (depending on the architecture), this also adds an outer loops that tile the prefetches.
std::string Halide::Internal::print_loop_nest (const std::vector< Function > & output_funcs)
Emit some simple pseudocode that shows the structure of the loop nest specified by this pipeline's schedule, and the schedules of the functions it uses.
Referenced by Halide::Internal::GeneratorOutputBase::as(), and Halide::Func::Func().
Stmt Halide::Internal::inject_profiling (Stmt , std::string)
Take a statement representing a halide pipeline insert high-resolution timing into the generated code (via spawning a thread that acts as a sampling profiler); summaries of execution times and counts will be logged at the end.
Should be done before storage flattening, but after all bounds inference.
Expr Halide::Internal::qualify (const std::string & prefix, Expr value)
Prefix all variable names in the given expression with the prefix string.
Expr Halide::Internal::random_float (const std::vector< Expr > &)
Return a random floating-point number between zero and one that varies deterministically based on the input expressions.
Expr Halide::Internal::random_int (const std::vector< Expr > &)
Return a random unsigned integer between zero and 2^32-1 that varies deterministically based on the input expressions (which must be integers or unsigned integers).
Expr Halide::Internal::lower_random (Expr e, const std::vector< std::string > & free_vars, int tag)
Convert calls to random() to IR generated by random_float and random_int.
Tags all calls with the variables in free_vars, and the integer given as the last argument.
std::pair<std::vector<std::string>, std::vector<std::vector<std::string> > > Halide::Internal::realization_order (const std::vector< Function > & outputs, std::map< std::string, Function > & env)
Given a bunch of functions that call each other, determine an order in which to do the scheduling.
This in turn influences the order in which stages are computed when there's no strict dependency between them. Currently just some arbitrary depth-first traversal of the call graph. In addition, determine grouping of functions with fused computation loops. The functions within the fused groups are sorted based on realization order. There should not be any dependencies among functions within a fused group. This pass will also populate the 'fused_pairs' list in the function's schedule. Return a pair of the realization order and the fused groups in that order.
std::vector<std::string> Halide::Internal::topological_order (const std::vector< Function > & outputs, const std::map< std::string, Function > & env)
Given a bunch of functions that call each other, determine a topological order which stays constant regardless of the schedule.
This ordering adheres to the producer-consumer dependencies, i.e. producer will come before its consumers in that order
void Halide::Internal::split_predicate_test ()
Referenced by Halide::Internal::ReductionDomain::same_as().
bool Halide::Internal::is_func_trivial_to_inline (const Function & func)
Return true if the cost of inlining a function is equivalent to the cost of calling the function directly.
Stmt Halide::Internal::remove_dead_allocations (Stmt s)
Find Allocate/Free pairs that are never loaded from or stored to, and remove them from the Stmt.
This doesn't touch Realize/Call nodes and so must be called after storage_flattening.
Stmt Halide::Internal::remove_trivial_for_loops (Stmt s)
Convert for loops of size 1 into LetStmt nodes, which allows for further simplification.
Done during a late stage of lowering.
Stmt Halide::Internal::remove_undef (Stmt s)
Removes stores that depend on undef values, and statements that only contain such stores.
Stmt Halide::Internal::schedule_functions (const std::vector< Function > & outputs, const std::vector< std::vector< std::string >> & fused_groups, const std::map< std::string, Function > & env, const Target & target, bool & any_memoized)
Build loop nests and inject Function realizations at the appropriate places using the schedule.
Returns a flag indicating whether memoization passes need to be run.
template<typename T > std::ostream& Halide::Internal::operator<< (std::ostream & stream, const Scope< T > & s)
Definition at line 269 of file Scope.h.
References Halide::Internal::Scope< T >::const_iterator::name().
Stmt Halide::Internal::select_gpu_api (Stmt s, Target t)
Replace for loops with GPU_Default device_api with an actual device API depending on what's enabled in the target.
Choose the first of the following: opencl, cuda, openglcompute, opengl
void Halide::Internal::simple_autoschedule_test ()
Stmt Halide::Internal::simplify (Stmt , bool remove_dead_lets = true, const Scope< Interval > & bounds = Scope< Interval >::empty_scope(), const Scope< ModulusRemainder > & alignment = Scope< ModulusRemainder >::empty_scope())
Perform a a wide range of simplifications to expressions and statements, including constant folding, substituting in trivial values, arithmetic rearranging, etc.
Simplifies across let statements, so must not be called on stmts with dangling or repeated variable names.
Expr Halide::Internal::simplify (Expr , bool remove_dead_lets = true, const Scope< Interval > & bounds = Scope< Interval >::empty_scope(), const Scope< ModulusRemainder > & alignment = Scope< ModulusRemainder >::empty_scope())
Perform a a wide range of simplifications to expressions and statements, including constant folding, substituting in trivial values, arithmetic rearranging, etc.
Simplifies across let statements, so must not be called on stmts with dangling or repeated variable names.
bool Halide::Internal::can_prove (Expr e)
A common use of the simplifier is to prove boolean expressions are true at compile time.
Equivalent to is_one(simplify(e))
Stmt Halide::Internal::simplify_exprs (Stmt)
Simplify expressions found in a statement, but don't simplify across different statements.
This is safe to perform at an earlier stage in lowering than full simplification of a stmt.
template<typename T > T Halide::Internal::mod_imp (T a, T b) inline
Implementations of division and mod that are specific to Halide.
Use these implementations; do not use native C division or mod to simplify Halide expressions. Halide division and modulo satisify the Euclidean definition of division for integers a and b:
/code (a/b)*b + ab = a 0 <= ab < |b| /endcode
Definition at line 54 of file Simplify.h.
References Halide::abs(), Halide::Runtime::Internal::b, and Halide::Type::is_int().
template<typename T > T Halide::Internal::div_imp (T a, T b) inline
Implementations of division and mod that are specific to Halide.
Use these implementations; do not use native C division or mod to simplify Halide expressions. Halide division and modulo satisify the Euclidean definition of division for integers a and b:
/code (a/b)*b + ab = a 0 <= ab < |b| /endcode
Definition at line 66 of file Simplify.h.
References Halide::Runtime::Internal::b, Halide::Type::bits(), and Halide::Type::is_int().
template<> float Halide::Internal::mod_imp< float > (float a, float b) inline
Definition at line 81 of file Simplify.h.
References Halide::Runtime::Internal::b.
template<> double Halide::Internal::mod_imp< double > (double a, double b) inline
Definition at line 86 of file Simplify.h.
References Halide::Runtime::Internal::b, and Halide::floor().
template<> float Halide::Internal::div_imp< float > (float a, float b) inline
Definition at line 91 of file Simplify.h.
References Halide::Runtime::Internal::b.
template<> double Halide::Internal::div_imp< double > (double a, double b) inline
Definition at line 94 of file Simplify.h.
References Halide::Runtime::Internal::b.
void Halide::Internal::simplify_specializations (std::map< std::string, Function > & env)
Try to simplify the RHS/LHS of a function's definition based on its specializations.
Stmt Halide::Internal::skip_stages (Stmt s, const std::vector< std::string > & order)
Avoid computing certain stages if we can infer a runtime condition to check that tells us they won't be used.
Does this by analyzing all reads of each buffer allocated, and inferring some condition that tells us if the reads occur. If the condition is non-trivial, inject ifs that guard the production.
Stmt Halide::Internal::sliding_window (Stmt s, const std::map< std::string, Function > & env)
Perform sliding window optimizations on a halide statement.
I.e. don't bother computing points in a function that have provably already been computed by a previous iteration.
SolverResult Halide::Internal::solve_expression (Expr e, const std::string & variable, const Scope< Expr > & scope = Scope< Expr >::empty_scope())
Attempts to collect all instances of a variable in an expression tree and place it as far to the left as possible, and as far up the tree as possible (i.e.
outside most parentheses). If the expression is an equality or comparison, this 'solves' the equation. Returns a pair of Expr and bool. The Expr is the mutated expression, and the bool indicates whether there is a single instance of the variable in the result. If it is false, the expression has only been partially solved, and there are still multiple instances of the variable.
Interval Halide::Internal::solve_for_outer_interval (Expr c, const std::string & variable)
Find the smallest interval such that the condition is either true or false inside of it, but definitely false outside of it.
Never returns undefined Exprs, instead it uses variables called "pos_inf" and "neg_inf" to represent positive and negative infinity.
Interval Halide::Internal::solve_for_inner_interval (Expr c, const std::string & variable)
Find the largest interval such that the condition is definitely true inside of it, and might be true or false outside of it.
Expr Halide::Internal::and_condition_over_domain (Expr c, const Scope< Interval > & varying)
Take a conditional that includes variables that vary over some domain, and convert it to a more conservative (less frequently true) condition that doesn't depend on those variables.
Formally, the output expr implies the input expr.
The condition may be a vector condition, in which case we also 'and' over the vector lanes, and return a scalar result.
void Halide::Internal::solve_test ()
Stmt Halide::Internal::split_tuples (Stmt s, const std::map< std::string, Function > & env)
Rewrite all tuple-valued Realizations, Provide nodes, and Call nodes into several scalar-valued ones, so that later lowering passes only need to think about scalar-valued productions.
void Halide::Internal::print_to_html (std::string filename, Stmt s)
Dump an HTML-formatted print of a Stmt to filename.
void Halide::Internal::print_to_html (std::string filename, const Module & m)
Dump an HTML-formatted print of a Module to filename.
Stmt Halide::Internal::storage_flattening (Stmt s, const std::vector< Function > & outputs, const std::map< std::string, Function > & env, const Target & target)
Take a statement with multi-dimensional Realize, Provide, and Call nodes, and turn it into a statement with single-dimensional Allocate, Store, and Load nodes respectively.
Stmt Halide::Internal::storage_folding (Stmt s, const std::map< std::string, Function > & env)
Fold storage of functions if possible.
This means reducing one of the dimensions module something for the purpose of storage, if we can prove that this is safe to do. E.g consider:
f(x) = ...
g(x) = f(x-1) + f(x)
f.store_root().compute_at(g, x);
We can store f as a circular buffer of size two, instead of allocating space for all of it.
bool Halide::Internal::strictify_float (std::map< std::string, Function > & env, const Target & t)
Propagate strict_float intrinisics such that they immediately wrap all floating-point expressions.
This makes the IR nodes context independent. If the Target::StrictFloat flag is specified in target, starts in strict_float mode so all floating-point type Exprs in the compilation will be marked with strict_float. Returns whether any strict floating-point is used in any function in the passed in env.
Expr Halide::Internal::substitute (const std::string & name, const Expr & replacement, const Expr & expr)
Substitute variables with the given name with the replacement expression within expr.
This is a dangerous thing to do if variable names have not been uniquified. While it won't traverse inside let statements with the same name as the first argument, moving a piece of syntax around can change its meaning, because it can cross lets that redefine variable names that it includes references to.
Referenced by Halide::Internal::Function::operator ExternFuncArgument().
Stmt Halide::Internal::substitute (const std::string & name, const Expr & replacement, const Stmt & stmt)
Substitute variables with the given name with the replacement expression within stmt.
Expr Halide::Internal::substitute (const std::map< std::string, Expr > & replacements, const Expr & expr)
Substitute variables with names in the map.
Stmt Halide::Internal::substitute (const std::map< std::string, Expr > & replacements, const Stmt & stmt)
Substitute variables with names in the map.
Expr Halide::Internal::substitute (const Expr & find, const Expr & replacement, const Expr & expr)
Substitute expressions for other expressions.
Stmt Halide::Internal::substitute (const Expr & find, const Expr & replacement, const Stmt & stmt)
Substitute expressions for other expressions.
Expr Halide::Internal::graph_substitute (const std::string & name, const Expr & replacement, const Expr & expr)
Substitutions where the IR may be a general graph (and not just a DAG).
Stmt Halide::Internal::graph_substitute (const std::string & name, const Expr & replacement, const Stmt & stmt)
Substitutions where the IR may be a general graph (and not just a DAG).
Expr Halide::Internal::graph_substitute (const Expr & find, const Expr & replacement, const Expr & expr)
Substitutions where the IR may be a general graph (and not just a DAG).
Stmt Halide::Internal::graph_substitute (const Expr & find, const Expr & replacement, const Stmt & stmt)
Substitutions where the IR may be a general graph (and not just a DAG).
Expr Halide::Internal::substitute_in_all_lets (const Expr & expr)
Substitute in all let Exprs in a piece of IR.
Doesn't substitute in let stmts, as this may change the meaning of the IR (e.g. by moving a load after a store). Produces graphs of IR, so don't use non-graph-aware visitors or mutators on it until you've CSE'd the result.
Stmt Halide::Internal::substitute_in_all_lets (const Stmt & stmt)
Substitute in all let Exprs in a piece of IR.
Doesn't substitute in let stmts, as this may change the meaning of the IR (e.g. by moving a load after a store). Produces graphs of IR, so don't use non-graph-aware visitors or mutators on it until you've CSE'd the result.
void Halide::Internal::target_test ()
Referenced by Halide::Target::maximum_buffer_size().
Stmt Halide::Internal::inject_tracing (Stmt , const std::string & pipeline_name, const std::map< std::string, Function > & env, const std::vector< Function > & outputs, const Target & Target)
Take a statement representing a halide pipeline, inject calls to tracing functions at interesting points, such as allocations.
Should be done before storage flattening, but after all bounds inference.
Stmt Halide::Internal::trim_no_ops (Stmt s)
Truncate loop bounds to the region over which they actually do something.
For examples see test/correctness/trim_no_ops.cpp
Stmt Halide::Internal::unify_duplicate_lets (Stmt s)
Find let statements that all define the same value, and make later ones just reuse the symbol names of the earlier ones.
Stmt Halide::Internal::uniquify_variable_names (Stmt s)
Modify a statement so that every internally-defined variable name is unique.
This lets later passes assume syntactic equivalence is semantic equivalence.
Stmt Halide::Internal::unpack_buffers (Stmt s)
Creates let stmts for the various buffer components (e.g.
foo.extent.0) in any referenced concrete buffers or buffer parameters. After this pass, the only undefined symbols should scalar parameters and the buffers themselves (e.g. foo.buffer).
Stmt Halide::Internal::unroll_loops (Stmt)
Take a statement with for loops marked for unrolling, and convert each into several copies of the innermost statement.
I.e. unroll the loop.
Stmt Halide::Internal::lower_unsafe_promises (Stmt s, const Target & t)
Lower all unsafe promises into either assertions or unchecked code, depending on the target.
template<typename DST , typename SRC , typename std::enable_if< std::is_floating_point< SRC >::value >::type * = nullptr> DST Halide::Internal::safe_numeric_cast (SRC s)
Some numeric conversions are UB if the value won't fit in the result; safe_numeric_cast<>() is meant as a drop-in replacement for a C/C++ cast that adds well-defined behavior for the UB cases, attempting to mimic common implementation behavior as much as possible.
Definition at line 59 of file Util.h.
References Halide::max(), and Halide::min().
template<typename DstType , typename SrcType > DstType Halide::Internal::reinterpret_bits (const SrcType & src)
An aggressive form of reinterpret cast used for correct type-punning.
Definition at line 95 of file Util.h.
References dst, ends_with(), get_env_variable(), make_entity_name(), memcpy(), replace_all(), running_program_name(), split_string(), starts_with(), and unique_name().
std::string Halide::Internal::make_entity_name (void * stack_ptr, const std::string & type, char prefix)
Make a unique name for an object based on the name of the stack variable passed in.
If introspection isn't working or there are no debug symbols, just uses unique_name with the given prefix.
Referenced by Halide::Buffer<>::Buffer(), and reinterpret_bits().
std::string Halide::Internal::get_env_variable (char const * env_var_name)
Get value of an environment variable.
Returns its value is defined in the environment. If the var is not defined, an empty string is returned.
Referenced by reinterpret_bits().
std::string Halide::Internal::running_program_name ()
Get the name of the currently running executable.
Platform-specific. If program name cannot be retrieved, function returns an empty string.
Referenced by reinterpret_bits().
std::string Halide::Internal::unique_name (char prefix)
Generate a unique name starting with the given prefix.
It's unique relative to all other strings returned by unique_name in this process.
The single-character version always appends a numeric suffix to the character.
The string version will either return the input as-is (with high probability on the first time it is called with that input), or replace any existing '$' characters with underscores, then add a '$' sign and a numeric suffix to it.
Note that unique_name('f') therefore differs from unique_name("f"). The former returns something like f123, and the latter returns either f or f$123.
Referenced by Halide::lambda(), and reinterpret_bits().
std::string Halide::Internal::unique_name (const std::string & prefix)
Generate a unique name starting with the given prefix.
It's unique relative to all other strings returned by unique_name in this process.
The single-character version always appends a numeric suffix to the character.
The string version will either return the input as-is (with high probability on the first time it is called with that input), or replace any existing '$' characters with underscores, then add a '$' sign and a numeric suffix to it.
Note that unique_name('f') therefore differs from unique_name("f"). The former returns something like f123, and the latter returns either f or f$123.
bool Halide::Internal::starts_with (const std::string & str, const std::string & prefix)
Test if the first string starts with the second string.
Referenced by reinterpret_bits().
bool Halide::Internal::ends_with (const std::string & str, const std::string & suffix)
Test if the first string ends with the second string.
Referenced by reinterpret_bits().
std::string Halide::Internal::replace_all (const std::string & str, const std::string & find, const std::string & replace)
Replace all matches of the second string in the first string with the last string.
Referenced by reinterpret_bits().
std::vector<std::string> Halide::Internal::split_string (const std::string & source, const std::string & delim)
Split the source string using 'delim' as the divider.
Referenced by reinterpret_bits().
template<typename T , typename Fn > T Halide::Internal::fold_left (const std::vector< T > & vec, Fn f)
Perform a left fold of a vector.
Returns a default-constructed vector element if the vector is empty. Similar to std::accumulate but with a less clunky syntax.
Definition at line 154 of file Util.h.
template<typename T , typename Fn > T Halide::Internal::fold_right (const std::vector< T > & vec, Fn f)
Returns a right fold of a vector.
Returns a default-constructed vector element if the vector is empty.
Definition at line 169 of file Util.h.
template<typename T1 , typename T2 , typename T3 , typename T4 > HALIDE_NO_USER_CODE_INLINE void Halide::Internal::collect_paired_args (std::vector< std::pair< T1, T2 >> & collected_args, const T3 & a1, const T4 & a2) inline
Definition at line 182 of file Util.h.
Referenced by collect_paired_args(), Halide::BoundaryConditions::constant_exterior(), Halide::BoundaryConditions::mirror_image(), Halide::BoundaryConditions::mirror_interior(), Halide::BoundaryConditions::repeat_edge(), and Halide::BoundaryConditions::repeat_image().
template<typename T1 , typename T2 , typename T3 , typename T4 , typename... Args> HALIDE_NO_USER_CODE_INLINE void Halide::Internal::collect_paired_args (std::vector< std::pair< T1, T2 >> & collected_args, const T3 & a1, const T4 & a2, Args &&... args) inline
Definition at line 188 of file Util.h.
References collect_paired_args().
std::string Halide::Internal::extract_namespaces (const std::string & name, std::vector< std::string > & namespaces)
Returns base name and fills in namespaces, outermost one first in vector.
Referenced by halide_handle_cplusplus_type::make().
std::string Halide::Internal::file_make_temp (const std::string & prefix, const std::string & suffix)
Create a unique file with a name of the form prefixXXXXXsuffix in an arbitrary (but writable) directory; this is typically /tmp, but the specific location is not guaranteed.
(Note that the exact form of the file name may vary; in particular, the suffix may be ignored on Windows.) The file is created (but not opened), thus this can be called from different threads (or processes, e.g. when building with parallel make) without risking collision. Note that if this file is used as a temporary file, the caller is responsibly for deleting it. Neither the prefix nor suffix may contain a directory separator.
std::string Halide::Internal::dir_make_temp ()
Create a unique directory in an arbitrary (but writable) directory; this is typically somewhere inside /tmp, but the specific location is not guaranteed.
The directory will be empty (i.e., this will never return /tmp itself, but rather a new directory inside /tmp). The caller is responsible for removing the directory after use.
bool Halide::Internal::file_exists (const std::string & name)
Wrapper for access().
Quietly ignores errors.
void Halide::Internal::assert_file_exists (const std::string & name)
assert-fail if the file doesn't exist.
useful primarily for testing purposes.
void Halide::Internal::assert_no_file_exists (const std::string & name)
assert-fail if the file DOES exist.
useful primarily for testing purposes.
void Halide::Internal::file_unlink (const std::string & name)
Wrapper for unlink().
Asserts upon error.
Quietly ignores errors.
Referenced by Halide::Internal::TemporaryFile::~TemporaryFile().
void Halide::Internal::ensure_no_file_exists (const std::string & name)
Ensure that no file with this path exists.
If such a file exists and cannot be removed, assert-fail.
void Halide::Internal::dir_rmdir (const std::string & name)
Wrapper for rmdir().
Asserts upon error.
FileStat Halide::Internal::file_stat (const std::string & name)
Wrapper for stat().
Asserts upon error.
bool Halide::Internal::add_would_overflow (int bits, int64_t a, int64_t b)
Routines to test if math would overflow for signed integers with the given number of bits.
Referenced by Halide::Internal::TemporaryFile::detach().
bool Halide::Internal::sub_would_overflow (int bits, int64_t a, int64_t b)
Routines to test if math would overflow for signed integers with the given number of bits.
Referenced by Halide::Internal::TemporaryFile::detach().
bool Halide::Internal::mul_would_overflow (int bits, int64_t a, int64_t b)
Routines to test if math would overflow for signed integers with the given number of bits.
Referenced by Halide::Internal::TemporaryFile::detach().
void Halide::Internal::halide_tic_impl (const char * file, int line)
void Halide::Internal::halide_toc_impl (const char * file, int line)
std::vector<Var> Halide::Internal::make_argument_list (int dimensionality)
Make a list of unique arguments for definitions with unnamed arguments.
Referenced by Halide::Func::define_extern(), and Halide::Var::outermost().
Stmt Halide::Internal::find_linear_expressions (Stmt s)
find_linear_expressions(Stmt s) identifies expressions that may be moved out of the generated fragment shader into a varying attribute.
These expressions are tagged by wrapping them in a glsl_varying intrinsic
Stmt Halide::Internal::setup_gpu_vertex_buffer (Stmt s)
Compute a set of 2D mesh coordinates based on the behavior of varying attribute expressions contained within a GLSL scheduled for loop.
This method is called during lowering to extract varying attribute expressions and generate code to evalue them at each mesh vertex location. The operation is performed on the host before the draw call to invoke the shader
Stmt Halide::Internal::vectorize_loops (Stmt s, const Target & t)
Take a statement with for loops marked for vectorization, and turn them into single statements that operate on vectors.
The loops in question must have constant extent.
std::map<std::string, Function> Halide::Internal::wrap_func_calls (const std::map< std::string, Function > & env)
Replace every call to wrapped Functions in the Functions' definitions with call to their wrapper functions.
void Halide::Internal::wrap_legacy_extern_stages (Module m)
Add wrappers for any LoweredFuncs that need them to support backwards compatibility.
This currently wraps extern calls to stages that expect the old buffer_t type.
void Halide::Internal::add_legacy_wrapper (Module m, const LoweredFunc & fn)
Add a wrapper for a LoweredFunc that accepts old buffers and upgrades them.
Variable Documentation
const int64_t Halide::Internal::unknown = std::numeric_limits<int64_t>::min()
Definition at line 22 of file AutoScheduleUtils.h.