Halide: Halide::Internal::Call Struct Reference
Halide::Internal::Call Struct Reference
A function call.
#include <IR.h>
Inherits Halide::Internal::ExprNode< Call >.
Public Types
typedef const char *const ConstString
Public Member Functions
bool is_pure () const
Check if a call node is pure within a pipeline, meaning that the same args always give the same result, and the calls can be reordered, duplicated, unified, etc without changing the meaning of anything.
bool is_intrinsic () const
bool is_intrinsic (ConstString intrin_name) const
bool is_extern () const
Public Member Functions inherited from Halide::Internal::ExprNode< Call >
void accept (IRVisitor *v) const
We use the visitor pattern to traverse IR nodes throughout the compiler, so we have a virtual accept method which accepts visitors.
Expr mutate_expr (IRMutator2 *v) const
ExprNode ()
virtual ~ExprNode ()
Public Member Functions inherited from Halide::Internal::BaseExprNode
BaseExprNode (IRNodeType t)
Public Member Functions inherited from Halide::Internal::IRNode
IRNode (IRNodeType t)
virtual ~IRNode ()
Static Public Member Functions
static Expr make (Type type, const std::string &name, const std::vector< Expr > &args, CallType call_type, FunctionPtr func=FunctionPtr(), int value_index=0, Buffer<> image=Buffer<>(), Parameter param=Parameter())
static Expr make (Function func, const std::vector< Expr > &args, int idx=0)
Convenience constructor for calls to other halide functions.
static Expr make (Buffer<> image, const std::vector< Expr > &args)
Convenience constructor for loads from concrete images.
static Expr make (Parameter param, const std::vector< Expr > &args)
Convenience constructor for loads from images parameters.
Public Attributes
std::string name
std::vector< Expr > args
CallType call_type
FunctionPtr func
int value_index
Buffer image
Parameter param
Public Attributes inherited from Halide::Internal::BaseExprNode
Type type
Public Attributes inherited from Halide::Internal::IRNode
RefCount ref_count
These classes are all managed with intrusive reference counting, so we also track a reference count.
IRNodeType node_type
Each IR node subclass has a unique identifier.
Static Public Attributes
static HALIDE_EXPORT ConstString debug_to_file
static HALIDE_EXPORT ConstString reinterpret
static HALIDE_EXPORT ConstString bitwise_and
static HALIDE_EXPORT ConstString bitwise_not
static HALIDE_EXPORT ConstString bitwise_xor
static HALIDE_EXPORT ConstString bitwise_or
static HALIDE_EXPORT ConstString shift_left
static HALIDE_EXPORT ConstString shift_right
static HALIDE_EXPORT ConstString abs
static HALIDE_EXPORT ConstString absd
static HALIDE_EXPORT ConstString rewrite_buffer
static HALIDE_EXPORT ConstString random
static HALIDE_EXPORT ConstString lerp
static HALIDE_EXPORT ConstString popcount
static HALIDE_EXPORT ConstString count_leading_zeros
static HALIDE_EXPORT ConstString count_trailing_zeros
static HALIDE_EXPORT ConstString undef
static HALIDE_EXPORT ConstString return_second
static HALIDE_EXPORT ConstString if_then_else
static HALIDE_EXPORT ConstString glsl_texture_load
static HALIDE_EXPORT ConstString glsl_texture_store
static HALIDE_EXPORT ConstString glsl_varying
static HALIDE_EXPORT ConstString image_load
static HALIDE_EXPORT ConstString image_store
static HALIDE_EXPORT ConstString make_struct
static HALIDE_EXPORT ConstString stringify
static HALIDE_EXPORT ConstString memoize_expr
static HALIDE_EXPORT ConstString alloca
static HALIDE_EXPORT ConstString likely
static HALIDE_EXPORT ConstString likely_if_innermost
static HALIDE_EXPORT ConstString register_destructor
static HALIDE_EXPORT ConstString div_round_to_zero
static HALIDE_EXPORT ConstString mod_round_to_zero
static HALIDE_EXPORT ConstString call_cached_indirect_function
static HALIDE_EXPORT ConstString prefetch
static HALIDE_EXPORT ConstString signed_integer_overflow
static HALIDE_EXPORT ConstString indeterminate_expression
static HALIDE_EXPORT ConstString bool_to_mask
static HALIDE_EXPORT ConstString cast_mask
static HALIDE_EXPORT ConstString select_mask
static HALIDE_EXPORT ConstString extract_mask_element
static HALIDE_EXPORT ConstString require
static HALIDE_EXPORT ConstString size_of_halide_buffer_t
static HALIDE_EXPORT ConstString strict_float
static HALIDE_EXPORT ConstString unsafe_promise_clamped
static HALIDE_EXPORT ConstString buffer_get_dimensions
static HALIDE_EXPORT ConstString buffer_get_min
static HALIDE_EXPORT ConstString buffer_get_extent
static HALIDE_EXPORT ConstString buffer_get_stride
static HALIDE_EXPORT ConstString buffer_get_max
static HALIDE_EXPORT ConstString buffer_get_host
static HALIDE_EXPORT ConstString buffer_get_device
static HALIDE_EXPORT ConstString buffer_get_device_interface
static HALIDE_EXPORT ConstString buffer_get_shape
static HALIDE_EXPORT ConstString buffer_get_host_dirty
static HALIDE_EXPORT ConstString buffer_get_device_dirty
static HALIDE_EXPORT ConstString buffer_get_type_code
static HALIDE_EXPORT ConstString buffer_get_type_bits
static HALIDE_EXPORT ConstString buffer_get_type_lanes
static HALIDE_EXPORT ConstString buffer_set_host_dirty
static HALIDE_EXPORT ConstString buffer_set_device_dirty
static HALIDE_EXPORT ConstString buffer_is_bounds_query
static HALIDE_EXPORT ConstString buffer_init
static HALIDE_EXPORT ConstString buffer_init_from_buffer
static HALIDE_EXPORT ConstString buffer_crop
static HALIDE_EXPORT ConstString buffer_set_bounds
static HALIDE_EXPORT ConstString trace
static const IRNodeType _node_type = IRNodeType::Call
Detailed Description
A function call.
This can represent a call to some extern function (like sin), but it's also our multi-dimensional version of a Load, so it can be a load from an input image, or a call to another halide function. These two types of call nodes don't survive all the way down to code generation - the lowering process converts them to Load nodes.
Definition at line 457 of file IR.h.
Member Typedef Documentation
typedef const char* const Halide::Internal::Call::ConstString
Definition at line 476 of file IR.h.
Member Enumeration Documentation
enum Halide::Internal::Call::CallType
Enumerator
Image
A load from an input image.
Extern
A call to an external C-ABI function, possibly with side-effects.
ExternCPlusPlus
A call to an external C-ABI function, possibly with side-effects.
PureExtern
A call to a guaranteed-side-effect-free external function.
Halide
A call to a Func.
Intrinsic
A possibly-side-effecty compiler intrinsic, which has special handling during codegen.
PureIntrinsic
A side-effect-free version of the above.
Definition at line 460 of file IR.h.
Member Function Documentation
static Expr Halide::Internal::Call::make (Type type, const std::string & name, const std::vector< Expr > & args, CallType call_type, FunctionPtr func = FunctionPtr(), int value_index = 0, Buffer<> image = Buffer<>(), Parameter param = Parameter()) static
Referenced by Halide::abs(), Halide::absd(), Halide::acos(), Halide::acosh(), Halide::asin(), Halide::asinh(), Halide::atan(), Halide::atan2(), Halide::atanh(), Halide::ceil(), Halide::cos(), Halide::cosh(), Halide::count_leading_zeros(), Halide::count_trailing_zeros(), Halide::div_round_to_zero(), Halide::exp(), Halide::fast_inverse(), Halide::fast_inverse_sqrt(), Halide::floor(), Halide::is_nan(), Halide::lerp(), Halide::likely(), Halide::likely_if_innermost(), Halide::log(), Halide::mod_round_to_zero(), Halide::operator&(), Halide::operator<<(), Halide::operator>>(), Halide::operator^(), Halide::operator|(), Halide::operator~(), Halide::popcount(), Halide::pow(), Halide::random_float(), Halide::random_uint(), Halide::reinterpret(), Halide::round(), Halide::sin(), Halide::sinh(), Halide::sqrt(), Halide::strict_float(), Halide::tan(), Halide::tanh(), Halide::trunc(), and Halide::undef().
static Expr Halide::Internal::Call::make (Function func, const std::vector< Expr > & args, int idx = 0) static
Convenience constructor for calls to other halide functions.
static Expr Halide::Internal::Call::make (Buffer<> image, const std::vector< Expr > & args) inline static
Convenience constructor for loads from concrete images.
Definition at line 574 of file IR.h.
References Halide::Internal::Cast::make(), Halide::Buffer< T >::name(), and Halide::Buffer< T >::type().
static Expr Halide::Internal::Call::make (Parameter param, const std::vector< Expr > & args) inline static
Convenience constructor for loads from images parameters.
Definition at line 579 of file IR.h.
References Halide::Internal::Cast::make(), Halide::Internal::Parameter::name(), and Halide::Internal::Parameter::type().
bool Halide::Internal::Call::is_pure () const inline
Check if a call node is pure within a pipeline, meaning that the same args always give the same result, and the calls can be reordered, duplicated, unified, etc without changing the meaning of anything.
Not transitive - doesn't guarantee the args themselves are pure. An example of a pure Call node is sqrt. If in doubt, don't mark a Call node as pure.
Definition at line 589 of file IR.h.
bool Halide::Internal::Call::is_intrinsic () const inline
Definition at line 595 of file IR.h.
bool Halide::Internal::Call::is_intrinsic (ConstString intrin_name) const inline
Definition at line 600 of file IR.h.
bool Halide::Internal::Call::is_extern () const inline
Definition at line 604 of file IR.h.
Member Data Documentation
std::string Halide::Internal::Call::name
Definition at line 458 of file IR.h.
std::vector<Expr> Halide::Internal::Call::args
Definition at line 459 of file IR.h.
CallType Halide::Internal::Call::call_type
Definition at line 468 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::debug_to_file static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::reinterpret static
Definition at line 477 of file IR.h.
Referenced by Halide::reinterpret().
HALIDE_EXPORT ConstString Halide::Internal::Call::bitwise_and static
Definition at line 477 of file IR.h.
Referenced by Halide::operator&().
HALIDE_EXPORT ConstString Halide::Internal::Call::bitwise_not static
Definition at line 477 of file IR.h.
Referenced by Halide::operator~().
HALIDE_EXPORT ConstString Halide::Internal::Call::bitwise_xor static
Definition at line 477 of file IR.h.
Referenced by Halide::operator^().
HALIDE_EXPORT ConstString Halide::Internal::Call::bitwise_or static
Definition at line 477 of file IR.h.
Referenced by Halide::operator|().
HALIDE_EXPORT ConstString Halide::Internal::Call::shift_left static
Definition at line 477 of file IR.h.
Referenced by Halide::operator<<().
HALIDE_EXPORT ConstString Halide::Internal::Call::shift_right static
Definition at line 477 of file IR.h.
Referenced by Halide::operator>>().
HALIDE_EXPORT ConstString Halide::Internal::Call::abs static
Definition at line 477 of file IR.h.
Referenced by Halide::abs().
HALIDE_EXPORT ConstString Halide::Internal::Call::absd static
Definition at line 477 of file IR.h.
Referenced by Halide::absd().
HALIDE_EXPORT ConstString Halide::Internal::Call::rewrite_buffer static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::random static
Definition at line 477 of file IR.h.
Referenced by Halide::random_float(), and Halide::random_uint().
HALIDE_EXPORT ConstString Halide::Internal::Call::lerp static
Definition at line 477 of file IR.h.
Referenced by Halide::lerp().
HALIDE_EXPORT ConstString Halide::Internal::Call::popcount static
Definition at line 477 of file IR.h.
Referenced by Halide::popcount().
HALIDE_EXPORT ConstString Halide::Internal::Call::count_leading_zeros static
Definition at line 477 of file IR.h.
Referenced by Halide::count_leading_zeros().
HALIDE_EXPORT ConstString Halide::Internal::Call::count_trailing_zeros static
Definition at line 477 of file IR.h.
Referenced by Halide::count_trailing_zeros().
HALIDE_EXPORT ConstString Halide::Internal::Call::undef static
Definition at line 477 of file IR.h.
Referenced by Halide::undef().
HALIDE_EXPORT ConstString Halide::Internal::Call::return_second static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::if_then_else static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::glsl_texture_load static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::glsl_texture_store static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::glsl_varying static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::image_load static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::image_store static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::make_struct static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::stringify static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::memoize_expr static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::alloca static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::likely static
Definition at line 477 of file IR.h.
Referenced by Halide::likely().
HALIDE_EXPORT ConstString Halide::Internal::Call::likely_if_innermost static
Definition at line 477 of file IR.h.
Referenced by Halide::likely_if_innermost().
HALIDE_EXPORT ConstString Halide::Internal::Call::register_destructor static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::div_round_to_zero static
Definition at line 477 of file IR.h.
Referenced by Halide::div_round_to_zero().
HALIDE_EXPORT ConstString Halide::Internal::Call::mod_round_to_zero static
Definition at line 477 of file IR.h.
Referenced by Halide::mod_round_to_zero().
HALIDE_EXPORT ConstString Halide::Internal::Call::call_cached_indirect_function static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::prefetch static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::signed_integer_overflow static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::indeterminate_expression static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::bool_to_mask static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::cast_mask static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::select_mask static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::extract_mask_element static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::require static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::size_of_halide_buffer_t static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::strict_float static
Definition at line 477 of file IR.h.
Referenced by Halide::strict_float().
HALIDE_EXPORT ConstString Halide::Internal::Call::unsafe_promise_clamped static
Definition at line 477 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::buffer_get_dimensions static
Definition at line 527 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::buffer_get_min static
Definition at line 527 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::buffer_get_extent static
Definition at line 527 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::buffer_get_stride static
Definition at line 527 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::buffer_get_max static
Definition at line 527 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::buffer_get_host static
Definition at line 527 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::buffer_get_device static
Definition at line 527 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::buffer_get_device_interface static
Definition at line 527 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::buffer_get_shape static
Definition at line 527 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::buffer_get_host_dirty static
Definition at line 527 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::buffer_get_device_dirty static
Definition at line 527 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::buffer_get_type_code static
Definition at line 527 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::buffer_get_type_bits static
Definition at line 527 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::buffer_get_type_lanes static
Definition at line 527 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::buffer_set_host_dirty static
Definition at line 527 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::buffer_set_device_dirty static
Definition at line 527 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::buffer_is_bounds_query static
Definition at line 527 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::buffer_init static
Definition at line 527 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::buffer_init_from_buffer static
Definition at line 527 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::buffer_crop static
Definition at line 527 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::buffer_set_bounds static
Definition at line 527 of file IR.h.
HALIDE_EXPORT ConstString Halide::Internal::Call::trace static
Definition at line 527 of file IR.h.
FunctionPtr Halide::Internal::Call::func
Definition at line 552 of file IR.h.
int Halide::Internal::Call::value_index
Definition at line 556 of file IR.h.
Buffer Halide::Internal::Call::image
Definition at line 560 of file IR.h.
Parameter Halide::Internal::Call::param
Definition at line 564 of file IR.h.
const IRNodeType Halide::Internal::Call::_node_type = IRNodeType::Call static
Definition at line 610 of file IR.h.
The documentation for this struct was generated from the following file:
IR.h