Halide: Halide::Derivative Struct Reference
Halide::Derivative Struct Reference
Helper structure storing the adjoints Func.
#include <Derivative.h>
Public Member Functions
Func operator() (const Func &func, int update_id=-1, bool bounded=true) const
Func operator() (const Buffer<> &buffer) const
std::vector< Func > funcs (const Func &func) const
Get the entire chain of new synthesized Funcs that compute the derivative of a given user-written Func for the purpose of scheduling.
Public Attributes
std::map< FuncKey, Func > adjoints
Detailed Description
Helper structure storing the adjoints Func.
Use d(func) or d(buffer) to obtain the derivative Func.
Definition at line 25 of file Derivative.h.
Member Function Documentation
Func Halide::Derivative::operator() (const Func & func, int update_id = -1, bool bounded = true) const inline
Definition at line 28 of file Derivative.h.
References Halide::Func::name().
Func Halide::Derivative::operator() (const Buffer<> & buffer) const inline
Definition at line 38 of file Derivative.h.
References Halide::Buffer< T >::name().
std::vector<Func> Halide::Derivative::funcs (const Func & func) const inline
Get the entire chain of new synthesized Funcs that compute the derivative of a given user-written Func for the purpose of scheduling.
Definition at line 47 of file Derivative.h.
References internal_assert, Halide::Func::name(), Halide::Func::num_update_definitions(), Halide::propagate_adjoints(), and Halide::propagate_tangents().
Member Data Documentation
std::map<FuncKey, Func> Halide::Derivative::adjoints
Definition at line 26 of file Derivative.h.
The documentation for this struct was generated from the following file:
Derivative.h