Halide: Halide::Target Struct Reference
Halide::Target Struct Reference
A struct representing a target machine and os to generate code for.
#include <Target.h>
Public Types
Public Member Functions
Target ()
Target (OS o, Arch a, int b, std::vector< Feature > initial_features=std::vector< Feature >())
void set_feature (Feature f, bool value=true)
void set_features (std::vector< Feature > features_to_set, bool value=true)
bool has_feature (Feature f) const
bool features_any_of (std::vector< Feature > test_features) const
bool features_all_of (std::vector< Feature > test_features) const
Target with_feature (Feature f) const
Return a copy of the target with the given feature set.
Target without_feature (Feature f) const
Return a copy of the target with the given feature cleared.
bool has_gpu_feature () const
Is a fully feature GPU compute runtime enabled? I.e.
bool supports_type (const Type &t) const
Does this target allow using a certain type.
bool supports_type (const Type &t, DeviceAPI device) const
Does this target allow using a certain type on a certain device.
bool supports_device_api (DeviceAPI api) const
Returns whether a particular device API can be used with this Target.
bool operator== (const Target &other) const
bool operator!= (const Target &other) const
std::string to_string () const
Convert the Target into a string form that can be reconstituted by merge_string(), which will always be of the form.
int natural_vector_size (const Halide::Type &t) const
Given a data type, return an estimate of the "natural" vector size for that data type when compiling for this Target.
template<typename data_t >
int natural_vector_size () const
Given a data type, return an estimate of the "natural" vector size for that data type when compiling for this Target.
bool has_large_buffers () const
Return true iff 64 bits and has_feature(LargeBuffers).
int64_t maximum_buffer_size () const
Return the maximum buffer size in bytes supported on this Target.
bool supported () const
Was libHalide compiled with support for this target?
Target (const std::string &s)
Given a string of the form used in HL_TARGET (e.g.
Target (const char *s)
Given a string of the form used in HL_TARGET (e.g.
Static Public Member Functions
static bool validate_target_string (const std::string &s)
Check if a target string is valid.
Public Attributes
enum Halide::Target::OS os
enum Halide::Target::Arch arch
int bits
The bit-width of the target machine.
Detailed Description
A struct representing a target machine and os to generate code for.
Definition at line 21 of file Target.h.
Member Enumeration Documentation
enum Halide::Target::OS
The operating system used by the target.
Determines which system calls to generate. Corresponds to os_name_map in Target.cpp.
Enumerator
OSUnknown
Linux
Windows
OSX
Android
IOS
QuRT
NoOS
Definition at line 25 of file Target.h.
enum Halide::Target::Arch
The architecture used by the target.
Determines the instruction set to use. Corresponds to arch_name_map in Target.cpp.
Enumerator
ArchUnknown
X86
ARM
MIPS
Hexagon
POWERPC
Definition at line 30 of file Target.h.
enum Halide::Target::Feature
Optional features a target can have.
Corresponds to feature_name_map in Target.cpp. See definitions in HalideRuntime.h for full information.
Enumerator
JIT
Debug
NoAsserts
NoBoundsQuery
SSE41
AVX
AVX2
FMA
FMA4
F16C
ARMv7s
NoNEON
VSX
POWER_ARCH_2_07
CUDA
CUDACapability30
CUDACapability32
CUDACapability35
CUDACapability50
CUDACapability61
OpenCL
CLDoubles
CLHalf
OpenGL
OpenGLCompute
UserContext
Matlab
Profile
NoRuntime
Metal
MinGW
CPlusPlusMangling
LargeBuffers
HVX_64
HVX_128
HVX_v62
HVX_v65
HVX_v66
HVX_shared_object
FuzzFloatStores
SoftFloatABI
MSAN
AVX512
AVX512_KNL
AVX512_Skylake
AVX512_Cannonlake
TraceLoads
TraceStores
TraceRealizations
D3D12Compute
StrictFloat
LegacyBufferWrappers
TSAN
ASAN
CheckUnsafePromises
FeatureEnd
Definition at line 46 of file Target.h.
Constructor & Destructor Documentation
Halide::Target::Target () inline
Definition at line 104 of file Target.h.
Referenced by Target().
Halide::Target::Target (OS o, Arch a, int b, std::vector< Feature > initial_features = std::vector<Feature>()) inline
Definition at line 105 of file Target.h.
References features_all_of(), features_any_of(), has_feature(), has_gpu_feature(), set_feature(), set_features(), supports_device_api(), supports_type(), Target(), validate_target_string(), with_feature(), and without_feature().
Halide::Target::Target (const std::string & s) explicit
Given a string of the form used in HL_TARGET (e.g.
"x86-64-avx"), construct the Target it specifies. Note that this always starts with the result of get_host_target(), replacing only the parts found in the target string, so if you omit (say) an OS specification, the host OS will be used instead. An empty string is exactly equivalent to get_host_target().
Invalid target strings will fail with a user_error.
Halide::Target::Target (const char * s) explicit
Given a string of the form used in HL_TARGET (e.g.
"x86-64-avx"), construct the Target it specifies. Note that this always starts with the result of get_host_target(), replacing only the parts found in the target string, so if you omit (say) an OS specification, the host OS will be used instead. An empty string is exactly equivalent to get_host_target().
Invalid target strings will fail with a user_error.
Member Function Documentation
static bool Halide::Target::validate_target_string (const std::string & s) static
Check if a target string is valid.
Referenced by Target().
void Halide::Target::set_feature (Feature f, bool value = true)
Referenced by Target().
void Halide::Target::set_features (std::vector< Feature > features_to_set, bool value = true)
Referenced by Target().
bool Halide::Target::has_feature (Feature f) const
Referenced by has_large_buffers(), Halide::Internal::CodeGen_ARM::neon_intrinsics_disabled(), Halide::Internal::schedule_scalar(), and Target().
bool Halide::Target::features_any_of (std::vector< Feature > test_features) const
Referenced by Target().
bool Halide::Target::features_all_of (std::vector< Feature > test_features) const
Referenced by Target().
Target Halide::Target::with_feature (Feature f) const
Return a copy of the target with the given feature set.
This is convenient when enabling certain features (e.g. NoBoundsQuery) in an initialization list, where the target to be mutated may be a const reference.
Referenced by Target().
Target Halide::Target::without_feature (Feature f) const
Return a copy of the target with the given feature cleared.
This is convenient when disabling certain features (e.g. NoBoundsQuery) in an initialization list, where the target to be mutated may be a const reference.
Referenced by Target().
bool Halide::Target::has_gpu_feature () const
Is a fully feature GPU compute runtime enabled? I.e.
is Func::gpu_tile and similar going to work? Currently includes CUDA, OpenCL, Metal and D3D12Compute. We do not include OpenGL, because it is not capable of gpgpu, and is not scheduled via Func::gpu_tile. TODO: Should OpenGLCompute be included here?
Referenced by Halide::Internal::schedule_scalar(), and Target().
bool Halide::Target::supports_type (const Type & t) const
Does this target allow using a certain type.
Generally all types except 64-bit float and int/uint should be supported by all backends.
It is likely better to call the version below which takes a DeviceAPI.
Referenced by Target().
bool Halide::Target::supports_type (const Type & t, DeviceAPI device) const
Does this target allow using a certain type on a certain device.
This is the prefered version of this routine.
bool Halide::Target::supports_device_api (DeviceAPI api) const
Returns whether a particular device API can be used with this Target.
Referenced by Target().
bool Halide::Target::operator== (const Target & other) const inline
Definition at line 177 of file Target.h.
References arch, bits, and os.
bool Halide::Target::operator!= (const Target & other) const inline
Definition at line 184 of file Target.h.
References natural_vector_size(), and to_string().
std::string Halide::Target::to_string () const
Convert the Target into a string form that can be reconstituted by merge_string(), which will always be of the form.
arch-bits-os-feature1-feature2...featureN.
Note that is guaranteed that Target(t1.to_string()) == t1, but not that Target(s).to_string() == s (since there can be multiple strings that parse to the same Target)... unless t1 contains 'unknown' fields (in which case you'll get a string that can't be parsed, which is intentional).
Referenced by operator!=().
int Halide::Target::natural_vector_size (const Halide::Type & t) const
Given a data type, return an estimate of the "natural" vector size for that data type when compiling for this Target.
template<typename data_t > int Halide::Target::natural_vector_size () const inline
Given a data type, return an estimate of the "natural" vector size for that data type when compiling for this Target.
Definition at line 208 of file Target.h.
Referenced by operator!=().
bool Halide::Target::has_large_buffers () const inline
Return true iff 64 bits and has_feature(LargeBuffers).
Definition at line 213 of file Target.h.
References has_feature(), and LargeBuffers.
Referenced by maximum_buffer_size().
int64_t Halide::Target::maximum_buffer_size () const inline
Return the maximum buffer size in bytes supported on this Target.
This is 2^31 - 1 except on 64-bit targets when the LargeBuffers feature is enabled, which expands the maximum to 2^63 - 1.
Definition at line 220 of file Target.h.
References Halide::get_host_target(), Halide::get_jit_target_from_environment(), Halide::get_target_from_environment(), has_large_buffers(), Halide::Internal, supported(), Halide::target_feature_for_device_api(), and Halide::Internal::target_test().
bool Halide::Target::supported () const
Was libHalide compiled with support for this target?
Referenced by maximum_buffer_size().
Member Data Documentation
enum Halide::Target::OS Halide::Target::os
Referenced by Halide::ExternalCode::is_for_cpu_target(), and operator==().
enum Halide::Target::Arch Halide::Target::arch
Referenced by Halide::ExternalCode::is_for_cpu_target(), and operator==().
int Halide::Target::bits
The bit-width of the target machine.
Must be 0 for unknown, or 32 or 64.
Definition at line 40 of file Target.h.
Referenced by Halide::ExternalCode::is_for_cpu_target(), and operator==().
The documentation for this struct was generated from the following file:
Target.h