Halide: Halide::Internal::ScopedBinding< void > Struct Template Reference
Halide::Internal::ScopedBinding< void > Struct Template Reference
#include <Scope.h>
Public Member Functions
ScopedBinding (Scope<> &s, const std::string &n)
ScopedBinding (bool condition, Scope<> &s, const std::string &n)
~ScopedBinding ()
Public Attributes
Scope * scope
std::string name
Detailed Description
template<>
struct Halide::Internal::ScopedBinding< void >
Definition at line 309 of file Scope.h.
Constructor & Destructor Documentation
Halide::Internal::ScopedBinding< void >::ScopedBinding (Scope<> & s, const std::string & n) inline
Definition at line 312 of file Scope.h.
References Halide::Internal::Scope< T >::push().
Halide::Internal::ScopedBinding< void >::ScopedBinding (bool condition, Scope<> & s, const std::string & n) inline
Definition at line 315 of file Scope.h.
References Halide::Internal::Scope< T >::push().
Halide::Internal::ScopedBinding< void >::~ScopedBinding () inline
Definition at line 321 of file Scope.h.
References Halide::Internal::Scope< T >::pop().
Member Data Documentation
Scope* Halide::Internal::ScopedBinding< void >::scope
Definition at line 310 of file Scope.h.
std::string Halide::Internal::ScopedBinding< void >::name
Definition at line 311 of file Scope.h.
The documentation for this struct was generated from the following file:
Scope.h