Halide: Halide::MachineParams Struct Reference
Halide::MachineParams Struct Reference
A struct representing the machine parameters to generate the auto-scheduled code for.
#include <AutoSchedule.h>
Public Member Functions
MachineParams (int32_t parallelism, int32_t llc, int32_t balance)
std::string to_string () const
Convert the MachineParams into canonical string form.
MachineParams (const std::string &s)
Reconstruct a MachineParams from canonical string form.
Static Public Member Functions
static MachineParams generic ()
Default machine parameters for generic CPU architecture.
Public Attributes
Expr parallelism
Maximum level of parallelism avalaible.
Expr last_level_cache_size
Size of the last-level cache (in KB).
Expr balance
Indicates how much more expensive is the cost of a load compared to the cost of an arithmetic operation at last level cache.
Detailed Description
A struct representing the machine parameters to generate the auto-scheduled code for.
Definition at line 16 of file AutoSchedule.h.
Constructor & Destructor Documentation
Halide::MachineParams::MachineParams (int32_t parallelism, int32_t llc, int32_t balance) inline explicit
Definition at line 25 of file AutoSchedule.h.
References Halide::Internal::check_estimates_on_outputs(), Halide::Internal::generate_schedules(), Halide::Internal::inline_all_element_wise_functions(), Halide::Internal::inline_all_trivial_functions(), Halide::Internal, and to_string().
Halide::MachineParams::MachineParams (const std::string & s) explicit
Reconstruct a MachineParams from canonical string form.
Member Function Documentation
static MachineParams Halide::MachineParams::generic () static
Default machine parameters for generic CPU architecture.
std::string Halide::MachineParams::to_string () const
Convert the MachineParams into canonical string form.
Referenced by MachineParams().
Member Data Documentation
Expr Halide::MachineParams::parallelism
Maximum level of parallelism avalaible.
Definition at line 18 of file AutoSchedule.h.
Expr Halide::MachineParams::last_level_cache_size
Size of the last-level cache (in KB).
Definition at line 20 of file AutoSchedule.h.
Expr Halide::MachineParams::balance
Indicates how much more expensive is the cost of a load compared to the cost of an arithmetic operation at last level cache.
Definition at line 23 of file AutoSchedule.h.
The documentation for this struct was generated from the following file:
AutoSchedule.h