Halide: thread_pool_common.h File Reference
thread_pool_common.h File Reference
Classes
struct Halide::Runtime::Internal::work
struct Halide::Runtime::Internal::work_queue_t
Namespaces
Halide
Defines methods for manipulating and analyzing boolean expressions.
Halide::Runtime
Halide::Runtime::Internal
Functions
void * pthread_self ()
WEAK int Halide::Runtime::Internal::clamp_num_threads (int desired_num_threads)
WEAK int Halide::Runtime::Internal::default_desired_num_threads ()
WEAK void Halide::Runtime::Internal::worker_thread_already_locked (work *owned_job)
WEAK void Halide::Runtime::Internal::worker_thread (void *)
WEAK int halide_default_do_task (void *user_context, halide_task_t f, int idx, uint8_t *closure)
WEAK int halide_default_do_par_for (void *user_context, halide_task_t f, int min, int size, uint8_t *closure)
The default versions of do_task and do_par_for.
WEAK int halide_set_num_threads (int n)
Set the number of threads used by Halide's thread pool.
WEAK void halide_shutdown_thread_pool ()
WEAK halide_do_task_t halide_set_custom_do_task (halide_do_task_t f)
WEAK halide_do_par_for_t halide_set_custom_do_par_for (halide_do_par_for_t f)
WEAK int halide_do_task (void *user_context, halide_task_t f, int idx, uint8_t *closure)
WEAK int halide_do_par_for (void *user_context, halide_task_t f, int min, int size, uint8_t *closure)
Variables
WEAK work_queue_t Halide::Runtime::Internal::work_queue = {}
WEAK halide_do_task_t Halide::Runtime::Internal::custom_do_task = halide_default_do_task
WEAK halide_do_par_for_t Halide::Runtime::Internal::custom_do_par_for = halide_default_do_par_for
Function Documentation
void* pthread_self ()
WEAK int halide_default_do_task (void * user_context, halide_task_t f, int idx, uint8_t * closure)
Definition at line 198 of file thread_pool_common.h.
References Halide::Runtime::Internal::work::f.
WEAK int halide_default_do_par_for (void * user_context, halide_task_t task, int min, int size, uint8_t * closure)
The default versions of do_task and do_par_for.
Can be convenient to call from overrides in certain circumstances.
Definition at line 203 of file thread_pool_common.h.
References Halide::Runtime::Internal::work_queue_t::a_team_size, Halide::Runtime::Internal::work::active_workers, Halide::Runtime::Internal::work_queue_t::assert_zeroed(), Halide::Runtime::Internal::clamp_num_threads(), Halide::Runtime::Internal::work::closure, Halide::Runtime::Internal::default_desired_num_threads(), Halide::Runtime::Internal::work_queue_t::desired_num_threads, Halide::Runtime::Internal::work::exit_status, Halide::Runtime::Internal::work::f, halide_cond_broadcast(), halide_mutex_lock(), halide_mutex_unlock(), halide_spawn_thread(), Halide::Runtime::Internal::work_queue_t::initialized, Halide::Runtime::Internal::work_queue_t::jobs, Halide::Runtime::Internal::work::max, Halide::min(), Halide::Runtime::Internal::work_queue_t::mutex, Halide::Runtime::Internal::work::next, Halide::Runtime::Internal::work::next_job, NULL, Halide::Runtime::Internal::work_queue_t::target_a_team_size, Halide::Runtime::Internal::work_queue_t::threads, Halide::Runtime::Internal::work_queue_t::threads_created, Halide::Runtime::Internal::work::user_context, Halide::Runtime::Internal::work_queue_t::wakeup_a_team, Halide::Runtime::Internal::work_queue_t::wakeup_b_team, Halide::Runtime::Internal::work_queue, Halide::Runtime::Internal::worker_thread(), and Halide::Runtime::Internal::worker_thread_already_locked().
WEAK int halide_set_num_threads (int n)
Set the number of threads used by Halide's thread pool.
Returns the old number.
n < 0 : error condition n == 0 : use a reasonable system default (typically, number of cpus online). n == 1 : use exactly one thread; this will always enforce serial execution n > 1 : use a pool of exactly n threads.
Note that the default iOS and OSX behavior will treat n > 1 like n == 0; that is, any positive value other than 1 will use a system-determined number of threads.
(Note that this is only guaranteed when using the default implementations of halide_do_par_for(); custom implementations may completely ignore values passed to halide_set_num_threads().)
Definition at line 286 of file thread_pool_common.h.
References Halide::Runtime::Internal::clamp_num_threads(), Halide::Runtime::Internal::default_desired_num_threads(), Halide::Runtime::Internal::work_queue_t::desired_num_threads, halide_error(), halide_mutex_lock(), halide_mutex_unlock(), Halide::Runtime::Internal::work_queue_t::mutex, NULL, and Halide::Runtime::Internal::work_queue.
WEAK void halide_shutdown_thread_pool ()
Definition at line 303 of file thread_pool_common.h.
References halide_cond_broadcast(), halide_join_thread(), halide_mutex_lock(), halide_mutex_unlock(), Halide::Runtime::Internal::work_queue_t::initialized, Halide::Runtime::Internal::work_queue_t::mutex, Halide::Runtime::Internal::work_queue_t::reset(), Halide::Runtime::Internal::work_queue_t::shutdown, Halide::Runtime::Internal::work_queue_t::threads, Halide::Runtime::Internal::work_queue_t::threads_created, Halide::Runtime::Internal::work_queue_t::wakeup_a_team, Halide::Runtime::Internal::work_queue_t::wakeup_b_team, Halide::Runtime::Internal::work_queue_t::wakeup_owners, and Halide::Runtime::Internal::work_queue.
WEAK halide_do_task_t halide_set_custom_do_task (halide_do_task_t f)
Definition at line 324 of file thread_pool_common.h.
References Halide::Runtime::Internal::custom_do_task, and Halide::Runtime::Internal::work::f.
WEAK halide_do_par_for_t halide_set_custom_do_par_for (halide_do_par_for_t f)
Definition at line 330 of file thread_pool_common.h.
References Halide::Runtime::Internal::custom_do_par_for, and Halide::Runtime::Internal::work::f.
WEAK int halide_do_task (void * user_context, halide_task_t f, int idx, uint8_t * closure)
Definition at line 336 of file thread_pool_common.h.
References Halide::Runtime::Internal::work::closure, Halide::Runtime::Internal::custom_do_task, Halide::Runtime::Internal::work::f, and Halide::Runtime::Internal::work::user_context.
Referenced by Halide::Runtime::Internal::worker_thread_already_locked().
WEAK int halide_do_par_for (void * user_context, halide_task_t f, int min, int size, uint8_t * closure)
Definition at line 341 of file thread_pool_common.h.
References Halide::Runtime::Internal::work::closure, Halide::Runtime::Internal::custom_do_par_for, Halide::Runtime::Internal::work::f, Halide::min(), and Halide::Runtime::Internal::work::user_context.